### ISSUE TITLE
Chrome + SwitchyOmege 使用 SOCKS5 无法连接，需要使用 SOCKS4

### ISSUE THREAD

**Issue by zvrh** [Hagb/docker-easyconnect#101]
当选择 SOCKS5 时打开网站会报 ERR_SOCKS_CONNECTION_FAILED 错误，而切换到 SOCKS4 才能访问。

Docker环境：WSL2 Debian
镜像：docker-easyconnect:7.6.7

**Comment by Hagb** [comment]
emmm 我这里无法复现，用 socks5 可以连接

**Comment by arielherself** [comment]
I also came across this problem today.
