### ISSUE TITLE
断开、重连循环

### ISSUE THREAD

**Issue by hellozehai** [Hagb/docker-easyconnect#102]
大神，我用的docker纯命令行版：docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -p 127.0.0.1:1080:1080 -p 127.0.0.1:8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d vpnaddress -u username -p password" hagb/docker-easyconnect:cli，里面的本地IP做了相应调整，EC_VER=7.6.6.305，但运行成功后，显示如下信息：
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in manual mode
update-alternatives: using /usr/sbin/ip6tables-legacy to provide /usr/sbin/ip6tables (ip6tables) in manual mode
WARNING: logging deactivated (can't log to stdout when daemonized)
auto login is disabled
user "0117105" login successfully!
svpn stop!
auto login is disabled
user "0117105" login successfully!
svpn stop!
auto login is disabled
user "0117105" login successfully!
svpn stop!
auto login is disabled
user "0117105" login successfully!
svpn stop!
auto login is disabled
user "0117105" login successfully!
svpn stop!
auto login is disabled
user "0117105" login successfully!
svpn stop!
auto login is disabled
user "0117105" login successfully!
svpn stop!
总是循环往复，请问是咋回事？谢谢谢谢。

**Comment by hellozehai** [comment]
好吧，我发现了，虽然我们公司用的easyconnect是7.6.6.305版本的，但EC_VER不能用，必须还得用EC_VER=7.6.3才行。但又有一个问题我怎么也弄不了，就是启动docker后，防火墙也添加了1080和8888的端口，但vmware外面的实体机怎么也tcping不通端口。请问这个是咋回事，谢谢。

**Comment by Hagb** [comment]
> 但又有一个问题我怎么也弄不了，就是启动docker后，防火墙也添加了1080和8888的端口，但vmware外面的实体机怎么也tcping不通端口。请问这个是咋回事，谢谢。

当时版本的策略路由表可能还有点问题，如果还有用 easyconnect 的话可以试试最新的容器
