### ISSUE TITLE
请问防火墙该如何开放端口？

### ISSUE THREAD

**Issue by helloBeren** [Hagb/docker-easyconnect#103]
您好，请问一下，我是在 VMware 虚拟机里的 centos 系统里跑的 docker 纯命令行版，虚拟机是桥接模式，centos 的防火墙也用命令firewall-cmd --permanent --add-port=1080/tcp 开了 1080 和 8888 端口，但 vmware 外部的主机就是无法连接 1080 和 8888 端口，tcping 也不通，请问有什么办法吗？感激

**Comment by Hagb** [comment]
在虚拟机本地能访问这两个端口码？如果可以，可以参照 https://github.com/Hagb/docker-easyconnect/blob/master/doc/route.md 确定一下是不是 docker 的问题

**Comment by Hagb** [comment]
另外启动容器的参数是什么？

**Comment by hellozehai** [comment]
环境及配置检查截图：
1.我们公司使用的easyconnect软件版本：
![1](https://user-images.githubusercontent.com/49972690/152362363-ff16c63d-3a15-406e-90ec-11cd02a03cc1.png)
2.启动容器的参数：
![2](https://user-images.githubusercontent.com/49972690/152362431-517cd81e-e983-4c13-b1ad-1241989900f6.png)
3.容器内部busybox ifconfig命令结果：
![7](https://user-images.githubusercontent.com/49972690/152362623-66e7842a-645e-4996-bf2c-9d0ba1c4d22d.png)
4.容器内部ip route结果：
![3](https://user-images.githubusercontent.com/49972690/152362751-2c0998dc-a33c-420c-9247-89971156e5b8.png)
5.容器内部iptables -S及iptables -S -t nat结果：
![4](https://user-images.githubusercontent.com/49972690/152362871-e2492227-5b7b-4576-af05-f8c242fdf951.png)
6.容器内部ping及traceroute公司内网服务器结果，测试都通：
![5-2](https://user-images.githubusercontent.com/49972690/152363123-ebad9fe0-b5f8-4a6f-bbe6-a588aa2e1808.png)
![5](https://user-images.githubusercontent.com/49972690/152363150-70edfea0-5519-4051-b56c-7c3695f87fda.png)
7.docker外层centos虚拟机中能测通docker的1080和8888端口，结果：
![10](https://user-images.githubusercontent.com/49972690/152366962-8e6a2e3b-02b7-4e9e-9378-effae453b8c6.png)
8.但是docker外层centos虚拟机中运行ping及traceroute命令无法连通通公司服务器，已运行iptables -I POSTROUTING -d 172.17.0.2 -p tcp -m tcp --dport 1080 -j MASQUERADE -t nat
命令，结果：
![11](https://user-images.githubusercontent.com/49972690/152367025-f750c48b-8eb1-4704-85a2-074165db633d.png)
![6](https://user-images.githubusercontent.com/49972690/152367043-516c7664-2830-4270-8c22-beb0316d42d2.png)

**Comment by Hagb** [comment]
> 但 vmware 外部的主机就是无法连接 1080 和 8888 端口，tcping 也不通，请问有什么办法吗

在宿主机能够连接吗？

**Comment by hellozehai** [comment]
1.虚拟机容器外指的是运行docker的centos虚拟机吗？无法连接，无法ping通公司内网服务器。是直接ping吗？还是需要额外设置一下？
2.宿主机是指运行VMware workstation的最外层的windows系统吗？这个更不行了，连1080和8888端口不通。

**Comment by Hagb** [comment]
> 1.虚拟机容器外指的是运行docker的centos虚拟机吗？无法连接，无法ping通公司内网服务器。是直接ping吗？还是需要额外设置一下？ 

比如通过以下命令访问一个内网网站
```
http_proxy=socks5h://172.17.0.2 curl http://某内网网站
```

**Comment by Hagb** [comment]
> 2.宿主机是指运行VMware workstation的最外层的windows系统吗？这个更不行了，连1080和8888端口不通。

能提供一下虚拟机 `iptables-save` 的输出吗？

**Comment by hellozehai** [comment]
> > 1.虚拟机容器外指的是运行docker的centos虚拟机吗？无法连接，无法ping通公司内网服务器。是直接ping吗？还是需要额外设置一下？
> 
> 是的，是指 centos 虚拟机。需要额外配置一下，比如通过以下命令访问一个内网网站（其中 http_proxy 变量显式指定了代理）
> 
> ```
> http_proxy=socks5h://172.17.0.2:1080 curl http://某内网网站
> ```

这个命令可以正确curl到结果，但是用“http_proxy=socks5h://172.17.0.2:1080 ping 内网服务器IP”这样的命令就无法ping通，请问这是怎么回事？

**Comment by hellozehai** [comment]
> > 2.宿主机是指运行VMware workstation的最外层的windows系统吗？这个更不行了，连1080和8888端口不通。
> 
> 能提供一下虚拟机 `iptables-save` 的输出吗？
![13](https://user-images.githubusercontent.com/49972690/152509448-1f53a713-9ddb-493c-8cf0-1aff4e31d6ef.png)

**Comment by Hagb** [comment]
> 这个命令可以正确curl到结果，但是用“http_proxy=socks5h://172.17.0.2:1080 ping 内网服务器IP”这样的命令就无法ping通，请问这是怎么回事？

因为 ping 并不接受 http_proxy 环境变量。可以在虚拟机里运行下面的命令添加路由：
```
ip route add 内网服务器IP via 172.17.0.2 mtu 1400
```
之后再用 ping 来测试。

---

CentOS 这个 iptables 有点长… 我一下子没看出有什么问题（有一些规则我也不是太清楚其行为）。在 VMware workstation 外的实体机上用是虚拟机而不是容器的地址来访问的是吧？

**Comment by hellozehai** [comment]
1.看来还是centos虚拟机中的路由表可能有问题，“ip route add 内网服务器IP via 172.17.0.2 mtu 1400”这条命令起作用了。
2.windows上用虚拟机地址访问还是不通，1080和8888端口也不通，是需要在centos中的防火墙开启这两个端口吗？还是需要做什么操作？
3.另外，真的太感谢您的帮助了。

**Comment by hellozehai** [comment]
现在的情况是，centos虚拟机内可以正常访问公司内网服务器了，但外面的windows怎么连接进去？Windows怎么访问公司内网服务器？谢谢

**Comment by Hagb** [comment]
从 CentOS 的 iptables 规则上看没什么问题… 试一试运行
```
docker run -ti -p 1081:1081 hagb/docker-easyconnect:cli busybox httpd -vfp 1081
```
然后从 Windows 上用浏览器访问虚拟机的 ip:1081 看看会不会加载出 404 的页面？

（正常情况下应该会有）

**Comment by hellozehai** [comment]
不知道什么原因，今天从头再配置一遍，突然就一切很顺利，就成功了。回想整个过程，其实就是在虚拟机中安装centos系统、安装docker、然后运行三条命令：1、touch ~/.easyconn ；2、 docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -p 1080:1080 -p 8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d vpnaddress -u username -p password" hagb/docker-easyconnect:cli ；3、 iptables -I POSTROUTING -d 172.17.0.2 -p tcp -m tcp --dport 1080 -j MASQUERADE -t nat  、再然后就成功了，windows也可以通过代理进入公司内网了，晕。
超级感谢您的所有帮助。
********************************************************************************************************************
但紧接着又有一些新的问题请教，就是域名解析的问题。我们公司内网有域名解析服务器，怎么实现公司资源走docker代理进内网，其他资源不走代理全部走互联网？
目前我做的努力：
1、chrome+SwitchyOmega ：可以实现公司域名的解析走代理进内网，但存在两个问题，一个是docker代理服务器关闭后，公司域名的解析就失败了，另一个问题是大量纯IP内网资源还得需要维护进SwitchyOmega的规则列表中，但这个IP量很大，维护困难；而且这种方式即使回到公司内网环境，访问也会失败。这种方式需要手动再编辑SwitchyOmega代理规则才可以正常。
2、使用Proxifier代理程序，添加规则：公司域名及公司IP走代理，其他直连，但测试后发现，不知道什么原因，IP可以走代理进内网，域名无法访问。我可以提供Proxifier License Key，方便的话您可以测试一下。
