### ISSUE TITLE
@shmille 提供的命令行版客户端 deb 包，每次登录的账户都是上次的账户

### ISSUE THREAD

**Issue by PinkR1ver** [Hagb/docker-easyconnect#106]
这个easyconnect的配置文件在哪呢，现在每次登录rvpn.zju.edu.cn的账户都是默认的,同时显示：
`auth failed, please check if the vpn address is valid and reachable!
user "318010****@zju.edu.cn" login FAILED!`

**Comment by PinkR1ver** [comment]
很奇怪，我等了一会它好了

**Comment by lishoujun** [comment]
你使用的命令是什么样的？把敏感信息去掉发出来看看吧。 我用的也是命令行版本  很好用

**Comment by PinkR1ver** [comment]
> 你使用的命令是什么样的？把敏感信息去掉发出来看看吧。 我用的也是命令行版本 很好用

我这个版本命令就三个，easyconn login，logout和query。（或者还有我不知道的指令？）
问题出在logout应该并没有完全的logout，我多次logout后就不存在我账户信息保存的问题了

**Comment by PinkR1ver** [comment]
> 

Thanks, 对于linux每个文件咋配置确实还是没有掌握，thanks
