### ISSUE TITLE
easyconnect登录后代理端口被关闭（并不）

### ISSUE THREAD

**Issue by CYTMWIA** [Hagb/docker-easyconnect#11]
使用情况：  
部署在家里服务器中，通过v2ray将外部访问转发到easyconnect  

问题描述：  
未登录时，代理端口是打开的且可以正常使用（可以访问无需代理的页面）  
登录后，代理端口被关闭（无论页面是否需要代理，均无法访问）（报错`read/write on closed pipe`）  
注销后，代理端口恢复正常  

运行环境：  
- 系统 **部署于pve的ubuntu 16.04 server**
- 使用镜像
  - hagb/docker-easyconnect:7.6.7  
  - v2fly/v2fly-core:latest (4.32.0)

其他：  
之前是在ubuntu 16.04 desktop部署的，可以正常使用，但不久前服务器被我配置坏了  
于是我重装了系统，顺便把使用的系统镜像也换成了server版  
这其中是否有什么联系呢  

此外，easyconnect的服务端是可用的，这点是经过验证的（朋友在Windows下可正常使用官方的easyconnect并连接）  

---

docker-easyconnect启动参数
```bash
docker run \
    -d \
    --name ▮▮数据删除▮▮ \
    --device /dev/net/tun \
    --cap-add NET_ADMIN \
    -e PASSWORD=▮▮数据删除▮▮ \
    -e ECPASSWORD=▮▮数据删除▮▮ \
    -v $HOME/▮▮数据删除▮▮/ecdata:/root \
    -p 5901:5901 \
    -p 4600:1080 \
    --restart unless-stopped \
    hagb/docker-easyconnect:7.6.7
```

<br>

docker-easyconnect输出（全部）
```
rm: cannot remove '/usr/share/sangfor/EasyConnect/resources/conf/easy_connect.json': No such file or directory
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
/usr/bin/xauth:  file /root/.Xauthority does not exist
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.

New '32854b9d32b2:1 (root)' desktop at :1 on machine 32854b9d32b2

Starting applications specified in flwm
Log file is /root/.vnc/32854b9d32b2:1.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd 32854b9d32b2:1 to connect to the VNC server.

Nov  6 13:55:56 (1604670956.409357) danted[458]: warning: checkconfig(): setting the unprivileged uid to 0 is not recommended for security reasons
```

<br>

v2ray输出（正常/未登录）
```
2020/11/06 14:16:10 [Info] [437636436] v2ray.com/core/proxy/vmess/inbound: received request for tcp:▮▮URL▮▮:443
2020/11/06 14:16:10 [Info] [437636436] v2ray.com/core/app/dispatcher: taking detour [▮▮TAG▮▮] for [tcp:▮▮URL▮▮:443]
2020/11/06 14:16:10 [Info] [437636436] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:magi.lan:4600
2020/11/06 14:16:10 ▮请求代理的IP▮:60851 accepted tcp:▮▮URL▮▮:443 [▮▮TAG▮▮]
```

<br>

v2ray输出（异常/登录 ）
```
2020/11/06 13:56:45 [Warning] [3944754685] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 4
2020/11/06 13:56:45 [Info] [3944754685] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
```

**Comment by Hagb** [comment]
> 通过v2ray将外部访问转发到easyconnect

这是指？（是开了 v2ray 的服务端然后将服务端进来的流量转发到 easyconnect 吗？）
另外实现的过程中除了上面的描述还做了什么别的操作吗？

**Comment by CYTMWIA** [comment]
> > 通过v2ray将外部访问转发到easyconnect
> 
> 这是指？（是开了 v2ray 的服务端然后将服务端进来的流量转发到 easyconnect 吗？）
> 另外实现的过程中除了上面的描述还做了什么别的操作吗？

是的，因为我认为单纯的socks5放在公网上不安全，所以就加了个v2ray并使用vmess协议  
v2ray内也设置了分流，部分域名是走easyconnect的，其余直连，这也方便我访问家里内网  
设置走easyconnect的域名有部分是无需代理也能访问的（用来测试代理端口是否开启且可用）  

额外操作应该是没有的

---

v2ray对应outbound设置
```
{
    "protocol": "socks",
    "tag": "▮▮TAG▮▮",
    "settings": {
        "servers": [
            {
                "address": "magi.lan",
                "port": 4600
            }
        ]
    }
}
```

**Comment by Hagb** [comment]
能否提供以下信息：

1. v2fly 的容器与 easyconnect 的容器是运行在同一个服务器上吗？
2. 对 docker 的网络有没有进行一些什么配置？
3. v2fly 服务端的网络环境下运行
    ``` shell
    ALL_PROXY=socks5://magi.lan:4600 curl 某要走easyconnect的网页
    ```
    输出什么？

**Comment by CYTMWIA** [comment]
> 能否提供以下信息：
> 
> 1. v2fly 的容器与 easyconnect 的容器是运行在同一个服务器上吗？
> 2. 对 docker 的网络有没有进行一些什么配置？
> 3. v2fly 服务端的网络环境下运行
>     ``` shell
>     ALL_PROXY=socks5://magi.lan:4600 curl 某要走easyconnect的网页
>     ```
>     输出什么？

1. 是的，运行在同一个服务器上。其中magi是主机名，访问magi.lan实际就是访问本机

2. 没有，docker安装后我就开始部署这些东西了，没有改过docker的设置

3. 现在手边暂时没电脑，中午回去测试

**Comment by Hagb** [comment]
> 是的，运行在同一个服务器上。其中magi是主机名，访问magi.lan实际就是访问本机

我没搞错的话，docker 默认的网络设置中容器之间是不能相互访问的。
方便的话 3 里面说的命令可以试试在宿主机和 v2fly 容器里都运行一下，看看各自的现象。

**Comment by CYTMWIA** [comment]
> 我没搞错的话，docker 默认的网络设置中容器之间是不能相互访问的。

确实容器间是不能直接访问的  
所以我使用了主机名+".lan"，并把容器的特定端口映射到服务器上  
这样就可以和路由器上的DNS配合，达成容器间的通信  
这是我在之前的ubuntu desktop就使用的方案，应该是没问题的  

---

> 3. v2fly 服务端的网络环境下运行
>    ```shell
>    ALL_PROXY=socks5://magi.lan:4600 curl 某要走easyconnect的网页
>    ```
>    输出什么？

**在服务器主机运行（未登录）**
```
$ ALL_PROXY=socks5://magi.lan:4600 curl ▮可直连的URL▮
正常返回

$ ALL_PROXY=socks5://magi.lan:4600 curl ▮需代理的URL▮
curl: (6) Could not resolve host: ▮需代理的域名▮
```
<br>

**在服务器主机运行（登录）**
```
$ ALL_PROXY=socks5://magi.lan:4600 curl ▮可直连的URL▮
正常返回 #这跟我在笔记本上浏览器的结果怎么不一样？浏览器提示“关闭了连接”

$ ALL_PROXY=socks5://magi.lan:4600 curl ▮需代理的URL▮
curl: (6) Could not resolve host: ▮需代理的域名▮
```
<br>

**在v2ray容器运行（未登录）**  
由于容器内没有curl，于是我就用wget代替了  
不过由于我没找到给wget设置socks代理的方法，所以在此仅测试对代理端口的联通性  
下面的v2ray输出同理
```
$ sudo docker exec -it v2ray wget magi.lan:4600
Connecting to magi.lan:4600 (192.168.6.198:4600)
wget: error getting response: Connection reset by peer #端口是可以连接的

$ sudo docker exec -it v2ray wget magi.lan:4601 #这是一个被关闭的端口，用于与开放端口对比输出
Connecting to magi.lan:4601 (192.168.6.198:4601)
wget: can't connect to remote host (192.168.6.198): Connection refused #连接被拒绝
```
<br>

**在v2ray容器运行（登录）**
```
$ sudo docker exec -it v2ray wget magi.lan:4600 #有两种可能的输出

Connecting to magi.lan:4600 (192.168.6.198:4600) #这是其一
wget: error getting response: Invalid argument

Connecting to magi.lan:4600 (192.168.6.198:4600) #这是其二
wget: error getting response: Resource temporarily unavailable
```

---

我已经懵逼了，现在是什么情况？？？  
通过观察 **在v2ray容器运行（登录）** 输出，似乎端口并没有被关闭  
而观察 **在服务器主机运行（登录）** 输出，竟然还可以访问无需代理的页面，进一步验证端口的开放  
但与此同时，我在浏览器（设置了到v2ray的代理）访问同一个页面得到的结果却是“似乎 ▮可直连的域名▮ 关闭了连接”

---

又做了下测试，浏览器竟然连上了▮可直连的域名▮，且v2ray的输出正常  
但对于▮需代理的域名▮，依旧无法访问，v2ray输出如下
```
2020/11/07 05:29:01 [Info] [3833706596] v2ray.com/core/proxy/vmess/inbound: received request for tcp:▮需代理的域名▮:80
2020/11/07 05:29:01 [Info] [3833706596] v2ray.com/core/app/dispatcher: taking detour [swpu-vpn] for [tcp:▮需代理的域名▮:80]
2020/11/07 05:29:01 [Info] [3833706596] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:magi.lan:4600
2020/11/07 05:29:01 125.70.254.72:56789 accepted tcp:▮需代理的域名▮:80 [swpu-vpn]
2020/11/07 05:29:01 [Warning] [3833706596] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 4
2020/11/07 05:29:01 [Info] [3833706596] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
```

**Comment by Hagb** [comment]
好迷啊…… 7.6.3 上没出现在这样的现象，我这里没有 7.6.7 版 easyconnect 的测试条件没法进行测试……
看看在 easyconnect 容器里能不能发访问需的代理的域名？
``` shell
docker run \
    -ti \
    --name ▮▮数据删除▮▮ \
    --device /dev/net/tun \
    --cap-add NET_ADMIN \
    -e PASSWORD=▮▮数据删除▮▮ \
    -e ECPASSWORD=▮▮数据删除▮▮ \
    -v $HOME/▮▮数据删除▮▮/ecdata:/root \
    -p 5901:5901 \
    -p 4600:1080 \
    --restart unless-stopped \
    hagb/docker-easyconnect:7.6.7
    su -
```
进入容器 shell，运行 `start.sh &` 待其登录之后看看能不能在容器里访问需代理的地址。
顺带可以看看 `ip route` 输出结果。

**Comment by Hagb** [comment]
我这儿写错了。`su -`（会覆盖环境变量）改为 `sh`

On November 7, 2020 2:13:55 PM GMT+08:00, "Hagb (Guo Junyu 郭俊余)" <notifications@github.com> wrote:
>好迷啊…… 7.6.3 上没出现在这样的现象，我这里没有 7.6.7 版 easyconnect 的测试条件没法进行测试……
>看看在 easyconnect 容器里能不能发访问需的代理的域名？
>``` shell
>docker run \
>    -ti \
>    --name ▮▮数据删除▮▮ \
>    --device /dev/net/tun \
>    --cap-add NET_ADMIN \
>    -e PASSWORD=▮▮数据删除▮▮ \
>    -e ECPASSWORD=▮▮数据删除▮▮ \
>    -v $HOME/▮▮数据删除▮▮/ecdata:/root \
>    -p 5901:5901 \
>    -p 4600:1080 \
>    --restart unless-stopped \
>    hagb/docker-easyconnect:7.6.7
>    su -
>```
>进入容器 shell，运行 `start.sh &` 待其登录之后看看能不能在容器里访问需代理的地址。
>顺带可以看看 `ip route` 输出结果。
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Hagb/docker-easyconnect/issues/11#issuecomment-723398488
--
---------
郭俊余(Guo Junyu) - Hagb - https://hagb.name/
自由/开源软件用户 / A free/libre and open software user
OpenPGP public key: https://hagb.name/key.asc
(Fingerprint: 40B5 42D3 636C F9D1 F599 C40A 5080 8599 9444 643A)

**Comment by CYTMWIA** [comment]
嗯……这样貌似进不去shell，start.sh一直没有结束  
我继续用原来的参数启动了easyconnect容器，并安装了curl
```
在未登录时，连接▮可直连的域名▮成功
登录后，无论是▮可直连的域名▮还是▮需代理的域名▮均无法连接
注销后，连接▮可直连的域名▮成功
```

唉……深信服的这软件真坑，在外乱改系统设置，在容器里又不好好工作……
我想我们还是别花费太多时间在这好了  
我用虚拟机凑合吧，有空再在ubuntu desktop里试试  

无论如何，感谢你的付出  
谢谢

**Comment by Hagb** [comment]
参看 [doc/route.md](https://github.com/Hagb/docker-easyconnect/issues/11)，应该可以解决了
