### ISSUE TITLE
建议 README 增加赞助按钮或二维码

### ISSUE THREAD

**Issue by lishoujun** [Hagb/docker-easyconnect#111]
一个项目想要长期活跃，除了作者本身的兴趣，来自用户的激励也是非常重要的。  
建议增加赞助按钮，或者收款二维码，方便有能力的用户支持作者。

**Comment by Hagb** [comment]
首先感谢支持！心领了。第二次收到类似请求，很感动。

容许我说一下自己的想法。

TLDR: 这个项目有它的一些特殊性，我自己能做的实际上非常有限，个人接受赞助受之有愧，同时法律上不知道会不会有法律风险（考虑到该项目直接使用了深信服的专有二进制）（当然，我对这方面的法律确实是不了解的）。

在维护这个项目的过程中，很多问题因为主观或客观的原因难以复现、难以调试，从而我个人也难以解决：

1. 和 EasyConnect 本身的特性或缺陷有关的问题：EasyConnect 的很多行为我们并不是十分清楚，部分的这类问题可以靠一些 hack 来解决，其他则需要深信服主动修复才能有效解决（比如非 x86 架构支持、命令行版本的短信验证码支持）
2. 和特定服务端的配置有关问题：服务器的地址、登录名、密码是敏感信息，但没有这类信息又难以直接复现、调试问题，而据我所知除了购买深信服的服务，又没有办法搭建深信服客户端来调试，所以许多这类问题只好由用户自行解决
3. 和用户特定环境的有关的问题：比如 Mac、WSL 以及一些专用环境（如 NAT）下的网络（路由、iptables）问题，我个人难以搭建环境来复现（其实也和我自己的精力有关，比如用虚拟机装 Windows 和黑苹果搭建环境来调试还是可行）
