### ISSUE TITLE
能否支持验证码认证呢？

### ISSUE THREAD

**Issue by Good0007** [Hagb/docker-easyconnect#112]
WARNING: logging deactivated (can't log to stdout when daemonized)
auto login is disabled
Next authentication is "SMS Authentication"
But we don't support it

**Comment by Hagb** [comment]
验证码认证请使用图形界面客户端

**Comment by lishoujun** [comment]
这是easyconnect cli版本本身不支持。

**Comment by Hagb** [comment]
与 #78 重复
