### ISSUE TITLE
M1 Mac Air上，danted无法启动

### ISSUE THREAD

**Issue by fzs001** [Hagb/docker-easyconnect#113]
如题，M1 Mac Air上使用7.6.3-VNC版本，可以成功登录Easyconnect，但只能在docker内ssh使用公司内网，无法启动代理为Mac Air转发流量。

docker的logs一直反复输出以下信息：
```
Feb  5 09:55:05 (1644054905.968534) danted[11458]: error: serverinit(): sched_getscheduler(2): failed to retrieve current cpuscheduling policy: Function not implemented

Feb  5 09:55:05 (1644054905.981203) danted[11458]: alert: mother[1/1]: shutting down
```
感觉是因为danted无法启动？

而且手动输入danted也是得到上面两条信息。

请问大家有什么思路吗？不胜感激!

**Comment by Hagb** [comment]
试试把这里面的 deb 包拷进容器里安装（`dpkg -i deb包路径`）？
使用了 `ac_cv_func_sched_setscheduler=no` 环境变量和 https://gitlab.traverse.com.au/muvirt/muvirt-feed/-/commit/ce1798e915181e6c1f3ba735b254b37b84261303 的补丁来编译。

[dante.zip](https://github.com/Hagb/docker-easyconnect/files/8008205/dante.zip)

**Comment by fzs001** [comment]
安装dante后问题解决了，非常感谢🙏

**Comment by ErickWei** [comment]
> 

可以告知一下具体部署步骤吗？M1 pro，小白请教

**Comment by fzs001** [comment]
> 

部署步骤就按照项目主页的介绍就可以了，有什么额外的困难吗？

**Comment by ErickWei** [comment]
> 

部署成功了。但是时不时会抽风，比如隔一段时间VNC可能就连不上了，VPN也可能突然连不上。或者电脑待机了一下再开启，也会出现这些情况。感觉不是很稳定。你遇到过类似的情况吗？

**Comment by fzs001** [comment]
我使用频率不高，目前一切正常，没有遇到什么问题

**Comment by fzs001** [comment]
> 

最近我的也会是不是抽风了，好像是ec自己莫名其妙断了，导致没有tun0网卡
```
Feb 26 04:12:44 (1645848764.006163) danted[16494]: error: /etc/danted.conf: problem on line 2 near token "tun0": could not resolve hostname "tun0": Name or service not known.  Please see the Dante manual for more information
Feb 26 04:12:44 (1645848764.009737) danted[16494]: alert: mother[1/1]: shutting down
```
