### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by 778299972** [Hagb/docker-easyconnect#115]
连接上vpn输入服务器地址 
提示Loading login configuration
等待一会就会显示Request failed. Please try again later.
这是什么原因呢 服务器地址带http,https,不带协议都试过了

**Comment by 778299972** [comment]
我使用的镜像版本是
![图片](https://user-images.githubusercontent.com/74100166/153536545-ec346b7f-b473-4417-bac2-b094d13c29b3.png)

**Comment by Hagb** [comment]
问题还存在吗？看起来似乎是客户端和服务端的版本不匹配

**Comment by 778299972** [comment]
> 问题还存在吗？看起来似乎是客户端和服务端的版本不匹配

切换版本就好了 谢谢
