### ISSUE TITLE
latest连接成功 无法开启代理

### ISSUE THREAD

**Issue by 778299972** [Hagb/docker-easyconnect#116]
我在vpn连接成功后 控制台输出这样的日志
![image](https://user-images.githubusercontent.com/74100166/153540985-69ba5cef-2c81-45ae-a695-41806c89a557.png)
这是bug吗？

下面是我的启动
docker run --device /dev/net/tun  --cap-add NET_ADMIN -ti -e PASSWORD=xxxx -v $HOME/.ecdata:/root -p 5901:5901 -p 1080:1080 -p 8888:8888 hagb/docker-easyconnect:latest

**Comment by Hagb** [comment]
感谢反馈！在 d1debe2 解决了。最新镜像已经推送到 dockerhub（可用 `docker pull hagb/docker-easyconnect` 拉取）

**Comment by 778299972** [comment]
> 
非常感谢 
![image](https://user-images.githubusercontent.com/74100166/153548031-0de45b19-5a7a-4734-8d8f-9df7d34f2249.png)
这个警告是什么原因？

**Comment by Hagb** [comment]
> > 
> 
> 非常感谢 ![image](https://user-images.githubusercontent.com/74100166/153548031-0de45b19-5a7a-4734-8d8f-9df7d34f2249.png) 这个警告是什么原因？

这个警告是 EasyConnect 的前端发出的，不影响使用。（具体是什么原因我也不太清楚）
