### ISSUE TITLE
不能开多个容器启动多个easyConnect吗

### ISSUE THREAD

**Issue by mi53** [Hagb/docker-easyconnect#117]
有多个vpn地址，需要开多个easyConnect。当前在Mac os m1上，开不了两个容器。

**Comment by Hagb** [comment]
目前只能一个容器一个 EasyConnect

**Comment by Hagb** [comment]
> 当前在Mac os m1上，开不了两个容器。

是说 m1 上的 docker 只支持一个容器，还是说是 EasyConnect 的容器只开得了一个？如果是后者，请附上容器启动日志
