### ISSUE TITLE
M1 Mac应用安装成功，访问内网资源失败

### ISSUE THREAD

**Issue by ErickWei** [Hagb/docker-easyconnect#118]
m1 mac，越狱Iphone，砸壳ec。通过PlayCover和Sideloadly安装。

ec应用能成功登录，但是mac系统里无法连接内网资源。

Visit resources failure, please relogin vpn and allow l3vpn permission!
<img width="260" alt="Snipaste_2022-02-16_11-18-11" src="https://user-images.githubusercontent.com/62826892/154189722-06b379c5-aa8f-47bf-89bf-e97ead52339b.png">

这个不知道怎么破！

@purocean @Hagb 

感觉Android/iOS客户端可能是比较好的解决方案.

我司强制最新版本,Linux版本均不可用,Android/iOS客户端看起来没版本限制(因为多年也不更新).

_Originally posted by @arthurire in https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-779679849_

**Comment by purocean** [comment]
我现在告别EC了。不过我后来的解决方案是在 ios 上使用 vpn，然后使用自己编译的 [Tehering](https://github.com/rickyzhang82/tethering) 监听端口，电脑同一个内网用代理访问。

**Comment by Hagb** [comment]
> 我司强制最新版本,Linux版本均不可用,Android/iOS客户端看起来没版本限制(因为多年也不更新).

`7.6.7` 和 `7.6.8` 可用吗？另外是否可以提供一下相应的 Windows 版，不知道从 win 版里面找配置文件。

**Comment by purocean** [comment]
> 我现在告别EC了。不过我后来的解决方案是在 ios 上使用 vpn，然后使用自己编译的 [Tehering](https://github.com/rickyzhang82/tethering) 监听端口，电脑同一个内网用代理访问。

对了，针对电脑上需要走全局vpn代理的，我使用了ios版小火箭，算是曲线救国

**Comment by ivanfei-1** [comment]
> m1 mac，越狱Iphone，砸壳ec。通过PlayCover和Sideloadly安装。
> 
> ec应用能成功登录，但是mac系统里无法连接内网资源。
> 
> Visit resources failure, please relogin vpn and allow l3vpn permission! <img alt="Snipaste_2022-02-16_11-18-11" width="260" src="https://user-images.githubusercontent.com/62826892/154189722-06b379c5-aa8f-47bf-89bf-e97ead52339b.png">
> 
> 这个不知道怎么破！
> 
> @purocean @Hagb
> 
> 感觉Android/iOS客户端可能是比较好的解决方案.
> 
> 我司强制最新版本,Linux版本均不可用,Android/iOS客户端看起来没版本限制(因为多年也不更新).
> 
> _Originally posted by @arthurire in [#25 (comment)](https://github.com/docker-easyconnect/docker-easyconnect/issues/25#issuecomment-779679849)_

iOS客户端需要企业开发者证书签名才能接管MacOS（新版big sur 及之后版本）的代理配置，个人开发者和自己签名不行。如果是这个问题的话可以查看playcover的ec启动日志时看到
如果手头有的话可以签一下试试，可能是可以使用的
