### ISSUE TITLE
使用纯命令行启动提示 not a device node

### ISSUE THREAD

**Issue by whiteS18** [Hagb/docker-easyconnect#119]
我在docker官网安装了docker for windows 使用的是hyper-v来运行docker，当我复制ReadMe的命令之后，改了url和用户名密码，
-e CLI_OPTS="-d https://ip:port -u username-p password"
打印了错误：
docker: Error response from daemon: error gathering device information while adding custom device "D": not a device node
请问我的命令是哪里有问题吗？还需改改什么吗？

**Comment by Hagb** [comment]
能发一下完整的 docker 命令吗？

**Comment by whiteS18** [comment]
> 能发一下完整的启动 docker 容器命令吗？

docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -p 127.0.0.1:1080:1080 -p 127.0.0.1:8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d https://ip:port -u 账号 -p 密码" hagb/docker-easyconnect:cli

**Comment by whiteS18** [comment]
> 能发一下完整的启动 EasyConnect 容器的 docker 命令吗？
另外，使用图形界面启动的命令也是这个提示

**Comment by whiteS18** [comment]
> 能发一下完整的启动 EasyConnect 容器的 docker 命令吗？

所以这个是啥原因，需要我换成wsl2嘛？

**Comment by Hagb** [comment]
> > 能发一下完整的启动 EasyConnect 容器的 docker 命令吗？
> 
> 所以这个是啥原因，需要我换成wsl2嘛？

我也不知道是什么原因，没有在 Windows 上用过 docker… 感觉和 D 盘有关？（我也不清楚）

**Comment by whiteS18** [comment]
> 
我刚刚看了下，跟docker有关的也没在d盘...都放在C盘了

**Comment by whiteS18** [comment]
> > > 能发一下完整的启动 EasyConnect 容器的 docker 命令吗？
> > 
> > 
> > 所以这个是啥原因，需要我换成wsl2嘛？
> 
> 我也不知道是什么原因，没有在 Windows 上用过 docker… 感觉和 D 盘有关？（我也不清楚）

我登陆到wsl2的ubuntu系统执行命令，提示iptable有问题，但是用户登陆成功，以下是提示：
```
WARNING: logging deactivated (can't log to stdout when daemonized)
iptables v1.8.2 (nf_tables): Chain 'MASQUERADE' does not exist
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables): Couldn't load match `state':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain INPUT
auto login is disabled
```

**Comment by whiteS18** [comment]
已解决
https://github.com/Hagb/docker-easyconnect/issues/79#issuecomment-952664418

**Comment by zhugechina** [comment]
> 已解决 [#79 (comment)](https://github.com/Hagb/docker-easyconnect/issues/79#issuecomment-952664418)

我也遇到同样的问题，请问你是怎么解决的
