### ISSUE TITLE
MAC M1 pro是否有合适的版本

### ISSUE THREAD

**Issue by dinga1981** [Hagb/docker-easyconnect#120]
我目前在用的M1 pro芯片的MacBook Pro，公司的VPN版本是7.6.3，按操作完成后，目前可以正常使用了，但是容器一直有个AMD64的警报
<img width="390" alt="image" src="https://user-images.githubusercontent.com/17311550/155321957-365b48fe-ebdc-4643-80cd-34574ff479fc.png">
同时资源占用特别高，基本CPU占用达到25%以上，内存占用800MB以上。
之前也尝试过纯命令行的版本，但是公司登录时需要证书登录，在命令行下一直报错，读取不到证书
请教各位有什么建议吗，谢谢。

**Comment by Hagb** [comment]
>  之前也尝试过纯命令行的版本，但是公司登录时需要证书登录，在命令行下一直报错，读取不到证书

如果使用命令行 easyconnect，docker 启动时加参数 `-v 证书本地路径:/root/cert`，easyconnect 询问证书时写 `/root/cert` 行不行？

**Comment by dinga1981** [comment]
> > 之前也尝试过纯命令行的版本，但是公司登录时需要证书登录，在命令行下一直报错，读取不到证书
> 
> 如果使用命令行 easyconnect，docker 启动时加参数 `-v 证书本地路径:/root/cert`，easyconnect 询问证书时写 `/root/cert` 行不行？

不行，跟之前报的一样的错误
cert pathname: /root/cert/1.pfx
cert password: 123456
import certificate failed, reason: !
user "xxxx" login FAILED!
svpn stop!

**Comment by Hagb** [comment]
> 不行，跟之前报的一样的错误
> cert pathname: /root/cert/1.pfx
> cert password: 123456
> import certificate failed, reason: !
> user "xxxx" login FAILED!
> svpn stop!

在容器里运行下 `ls /root/cert/1.pfx` 看看文件在不在？

**Comment by Hagb** [comment]
关于命令行版本的证书，之前 #48 有相关讨论

**Comment by Hagb** [comment]
图形界面版本可以尝试使用 https://github.com/Hagb/docker-easyconnect/issues/128#issuecomment-1078708095

**Comment by Hagb** [comment]
现在有 arm64 原生版本，可以试一试：https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1256860002
以及该 issue 与 #99 重复

**Comment by 1980892504** [comment]
可以链接vpn，但是不能链接资源
