### ISSUE TITLE
账户密码中如果有特殊字符(!@?&...) 如何使用命令行版本将密码加入CLI_OPTS中?

### ISSUE THREAD

**Issue by ErickWei** [Hagb/docker-easyconnect#121]
如题。

**Comment by Hagb** [comment]
用 bash 的语法进行转义。如 `!@?&``\"'` :
```bash
printf -v escaped_passwd %q '!@?&``\"'\'
docker ... -e CLI_OPTS="-d vpnaddress -u username -p $escaped_passwd" ...
```
其中 `printf -v escaped_passwd %q '!@?&``"'\'` 是将 `!@?&``"'`  转义后的字符串(```\!@\?\&\`\`\\\"\'```)存入 `escaped_passwd` 变量。（注意 `printf` 那个参数也要进行转义才能传给 `printf`…）

如果实在弄不清楚，运行下面的代码并输入密码
```bash
read -rp "Input password: " passwd
printf %q "$passwd"
```
输出的内容就可以用来作为前面  `printf -v escaped_passwd %q` 的参数。
如输入 `!@?&``\"'`，输出 ```\!@\?\&\`\`\\\"\'```，然后
```bash
printf -v escaped_passwd %q \!@\?\&\`\`\\\"\'
docker ... -e CLI_OPTS="-d vpnaddress -u username -p $escaped_passwd" ...
```

PS: 将 CLI_OPTS 传给 easyconnect 的代码在
https://github.com/Hagb/docker-easyconnect/blob/d1debe2dfcbba5210b7ee5a401a8380f01d362a4/docker-root/usr/local/bin/start-sangfor.sh#L22
