### ISSUE TITLE
m1 下用 docker 运行，iptables 输出 Operation not supported

### ISSUE THREAD

**Issue by watermelon11** [Hagb/docker-easyconnect#123]
(Update: 问题在 https://github.com/Hagb/docker-easyconnect/issues/123#issuecomment-1059969313 被定位)
刚买的m1，mac os 12.1 由于历史原因公司的vpn版本比较老
使用docker运行无界面版，使用proxifier无法上网
![image](https://user-images.githubusercontent.com/28687015/156233455-9139659e-8363-4d4f-a4e0-84a4652ac8a9.png)

![image](https://user-images.githubusercontent.com/28687015/156233545-35e825e6-f17c-4f93-a397-94735bfedd0c.png)

代理使用的是proxifier

使用docker运行界面版，无法连接上
<img width="641" alt="image" src="https://user-images.githubusercontent.com/28687015/156232385-3df82da3-6bc9-407d-82a0-00be60841c32.png">
7.6.3版本的

![image](https://user-images.githubusercontent.com/28687015/156232676-e84ac4b0-0215-41e5-a416-20d160a9e040.png)
7.6.7版本的
求助呀！！！！！

**Comment by Hagb** [comment]
无界面版试试把参数中的 `-p 127.0.0.1:1080:1080` 改成 `-p 1080`

**Comment by watermelon11** [comment]
> 无界面版试试把参数中的 `-p 127.0.0.1:1080:1080` 改成 `-p 1080`
<img width="446" alt="image" src="https://user-images.githubusercontent.com/28687015/156385607-1fbecfe9-7644-4b26-bd5e-77b632fbac40.png">

改了没用容器内就不能访问，windows连上了就可以访问10.88.25.61这个ip

**Comment by Hagb** [comment]
看看在容器内 `ip route` 和 `busybox ifconfig` 的输出？

**Comment by Hagb** [comment]
看看在容器内 `ip route` 和 `busybox ifconfig` 的输出？

**Comment by watermelon11** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/28687015/156397236-f77bae71-962c-428a-93c1-635a36f21ae8.png">

**Comment by Hagb** [comment]
那就是没连上。`docker logs 容器名` 输出什么？

> <img alt="image" width="570" src="https://user-images.githubusercontent.com/28687015/156397236-f77bae71-962c-428a-93c1-635a36f21ae8.png">

**Comment by watermelon11** [comment]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/28687015/156398196-14b4e60c-13bf-4dbf-9702-55b0308ec245.png">

但是我在日志上看提示是连接成功的....

**Comment by Hagb** [comment]
> <img alt="image" width="825" src="https://user-images.githubusercontent.com/28687015/156398196-14b4e60c-13bf-4dbf-9702-55b0308ec245.png">
> 
> 但是我在日志上看提示是连接成功的....

你试试给启动参数加上 `-e IPTABLES_LEGACY=1`

**Comment by Hagb** [comment]
把用户名、密码这些敏感信息隐去，启动容器完整的命令行是怎么样的？

**Comment by watermelon11** [comment]
docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -p 1080 -e EC_VER=7.6.7 -e CLI_OPTS="-d xxx -u dengzhongqing -p xxx" hagb/docker-easyconnect:cli

我的启动命令是这个 把127.0.0.1:1080:1080改成了1080

**Comment by Hagb** [comment]
> docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -p 1080 -e EC_VER=7.6.7 -e CLI_OPTS="-d xxx -u dengzhongqing -p xxx" hagb/docker-easyconnect:cli
> 
> 我的启动命令是这个 把127.0.0.1:1080:1080改成了1080

`EC_VER=7.6.7` 里的 `7.6.7` 改成 `7.6.3` 和 `7.6.8` 试试

**Comment by watermelon11** [comment]
都是试过了。不行QAQ

**Comment by watermelon11** [comment]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/28687015/156926528-d2f9f574-37ca-42de-8495-54f95a3c7e2a.png">

不知道是不是iptable的问题我查阅了一下[route.md](https://github.com/Hagb/docker-easyconnect/blob/master/doc/route.md)这个文档，但是mac没有iptable命令。求教解决方案，不甚感谢。

**Comment by Hagb** [comment]
我没有 m1，无法对这种情况进行测试… 看看容器里运行 `iptables-nft-save` 和 `iptables-legacy-save` 分别输出什么？

**Comment by Hagb** [comment]
看起来可能和 #125  类似。
可以试试使用非 amd64 版本的，详见 https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1044213653

**Comment by Hagb** [comment]
现在有 arm64 原生版本，可以试一试：https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1256860002
以及与 #99 重复
