### ISSUE TITLE
7.6.7在腾讯云服务器上首次运行成功，容器重启后显示version is not matching

### ISSUE THREAD

**Issue by zhubinsheng** [Hagb/docker-easyconnect#124]
client version and server software version is not matching

**Comment by zhubinsheng** [comment]
https://github.com/Hagb/docker-easyconnect/issues/88#issuecomment-999200224
此方法可能有效 但是没明白问题的具体原因

**Comment by zhubinsheng** [comment]
如何有效处理这个问题阿阿

**Comment by kongfei605** [comment]
```grep 'need update'  /usr/share/sangfor/EasyConnect/resources/logs/ECAgent.log``` 看下输出
```
[2022-03-23 01:25:31][I][ 314][GetApiResult][ApiNeedUpdateImplementor] force update version is 7.6.7.5, server version is 7.6.7.4, need update 
```


然后去conf目录 做一下替换

```sed -i 's/7.6.7.5/7.6.7.3/g' pkg_version.xml ```替换的版本，必须小于7.6.7.4 ，等于7.6.7.4不行。 

问题可解。

**Comment by redjumper** [comment]
镜像如果不是最新的，重新拉取下，删除~/.ecdata/重新创建

**Comment by kongfei605** [comment]
> 镜像如果不是最新的，重新拉取下，删除~/.ecdata/重新创建

我提供的是不需要删除 ~/.ecdata目录，解决verion is not matching的方法。
