### ISSUE TITLE
在 Docker 中运行 EasyConnect 会不会导致内网不安全?

### ISSUE THREAD

**Issue by lyc8503** [Hagb/docker-easyconnect#126]
如题, EasyConnect 本身并不开源, 即使在 Docker 中运行也能访问到局域网其他设备, 如果局域网还有其他服务是否有可能因为 EasyConnect 的管理者配置不当或者 EasyConnect 本身有漏洞而使局域网其他服务被暴露受到攻击?

**Comment by Hagb** [comment]
emmm 这里说的内网指的是宿主机所在的内网，还是 vpn 那一侧的内网？
前者可以通过限定容器能访问宿主机网络的范围来降低风险。

**Comment by lyc8503** [comment]
我指的是宿主机侧的内网, 连接 vpn 时强制要求打开 ip fowarding, 那我研究一下 docker iptables 的设置, 感谢.
