### ISSUE TITLE
cli版本登录之后提示成功却一直在循环stop和登录

### ISSUE THREAD

**Issue by lusao-xg** [Hagb/docker-easyconnect#130]
![image](https://user-images.githubusercontent.com/28584937/160223324-c90b7536-bc47-4e4f-8066-6cce52b52fc0.png)

启动命令:
```
docker run --rm --device /dev/net/tun --cap-add NET_ADMIN -tid  --name *  -p 4444:8888 -e IPTABLES_LEGACY=1 -e EC_VER=7.6.8 -e CLI_OPTS=" -d https://* -u *-p *" hagb/docker-easyconnect:cli 
```

之前还可以，现在成这样了，有没有解决方案

**Comment by Hagb** [comment]
试试 `-d` 参数后面直接写 ip 或域名，不加 `https://`？

**Comment by lusao-xg** [comment]
> 

已经尝试只使用ip了，还是这样的问题

**Comment by lusao-xg** [comment]
> 试试 `-d` 参数后面直接写 ip 或域名，不加 `https://`？

已经尝试只使用ip了，还是这样的问题

**Comment by Hagb** [comment]
看看 `EC_VER` 改成另外两个取值试一试？如果还是不行的话或许可以看看 /usr/share/sangfor/EasyConnect/resouces/logs 里的日志有没有什么有用的信息

**Comment by lusao-xg** [comment]
> 看看 `EC_VER` 的取值改成另外两个版本试一试？如果还是不行的话或许可以看看 /usr/share/sangfor/EasyConnect/resouces/logs 里的日志有没有什么有用的信息

![image](https://user-images.githubusercontent.com/28584937/160233139-8f2f71ad-3c6a-48ec-aaa3-5006878c5156.png)
以上是`cat svpnservice.log`
![image](https://user-images.githubusercontent.com/28584937/160233164-bcbfa320-a848-4141-a5c6-d5fc9112d5c0.png)
以上是`cat easyconn.log`
不知道有什么问题吗？

**Comment by lusao-xg** [comment]
要不要我帮相关的配置发给你，你测试一下

发自我的iPhone
