### ISSUE TITLE
Automate the login process of the VNC client when using VNC protocol to communicate with docker-easyconnect container.

### ISSUE THREAD

**Issue by hongyi-zhao** [Hagb/docker-easyconnect#14]
I try to find some script/API based method, say, using python, for automating the login process of VNC client but still haven't found any good solutions.

Do you have any good idea for this problem?

Regards,
HY

**Comment by Hagb** [comment]
Are "remember password" option and "auto login" option in EasyConnect available?

**Comment by hongyi-zhao** [comment]
I don't mean the connection process of EasyConnect itself, instead, I mean the login operation of VNC client. Obviously, you must first log into the remote VNC server before starting the EasyConnect client.

**Comment by Hagb** [comment]
Do you mean automatic login to VNC after starting the VNC server and before starting EasyConnect?

-----
> Obviously, you must first log into the remote VNC server before starting the EasyConnect client.

For login in EasyConnect, it is not needed to log into VNC before EasyConnect is started.
And after "auto login" option of EasyConnect is enabled, it will even be unnecessary to log in VNC, because after EasyConnect is started, the login of EasyConnect will be automatically done.

**Comment by Hagb** [comment]
https://linux.die.net/man/1/vncviewer
`-passwd` parameter of vncviewer may help.

**Comment by hongyi-zhao** [comment]
1. I really can't find any "auto login" option for EasyConnect on the login GUI of EasyConnect client included in your docker image published on docker hub. See the screenshot I observed:

![image](https://user-images.githubusercontent.com/11155854/99074482-c9a0bd00-25f2-11eb-87ab-70b7a542b216.png)

2. It seems the RealVNC's vncviewer is more convenient to automatically preserve the login credentials.

**Comment by Hagb** [comment]
> I really can't find any "auto login" option for EasyConnect on the login GUI of EasyConnect client included in your docker image published on docker hub. See the screenshot I observed:

Maybe #7 can help.
And refer to https://github.com/Hagb/docker-easyconnect/pull/7#issuecomment-668639071 .

**Comment by hongyi-zhao** [comment]
Wonderful and graceful ideas!
