### ISSUE TITLE
宿主机关闭ipv6，danted报错无法启动

### ISSUE THREAD

**Issue by redjumper** [Hagb/docker-easyconnect#140]
宿主机关闭ipv6，使用最新镜像hagb/docker-easyconnect:7.6.7，一直报以下错误，danted未能启动

> Apr 14 02:46:46 (1649904406.234595) danted[769]: warning: bindinternal(): could not create IPv6 address socket(2): Address family not supported by protocol
> Apr 14 02:46:46 (1649904406.234892) danted[769]: error: serverinit(): failed to bind internal addresses: Address family not supported by protocol
> Apr 14 02:46:46 (1649904406.235108) danted[769]: alert: mother[1/1]: shutting down

```
root@easyconnect:/# ip -f inet6 -o addr
root@easyconnect:/# ip -f inet -o addr
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: tun0    inet 10.17.1.1/24 scope global tun0\       valid_lft forever preferred_lft forever
174: eth0    inet 172.18.2.2/24 brd 172.18.2.255 scope global eth0\       valid_lft forever preferred_lft forever
```
修改danted.conf删除internal ipv6的配置后，danted正常启动
```
root@easyconnect:/# cat /run/danted.conf
internal: 0.0.0.0 port = 1080
external: tun0
external: lo
external: eth0

external.rotation: route
socksmethod: none
clientmethod: none
client pass {
        from: 0/0 to: 0/0
}
socks pass {
        from: 0/0 to: 0.0.0.0/0
}
```

**Comment by Hagb** [comment]
> 有个疑问，danted的配置文件里internal为何不和external一样直接使用接口，这样不用判断是ipv4还是ipv6
> 以下是测试的配置文件，参考了官方文档的[Minimal server configuration](https://www.inet.no/dante/doc/1.4.x/config/server.html)

是个好主意（当时没有考虑到这种方式，也没考虑到在无 ipv6 支持的情况下会无法启动），这之前我的思路是通过判断容器有没有 ipv6 支持来改配置文件。
欢迎提交 PR（抱歉最近太忙了所以这些 issue 都还没处理）。

可以将：
https://github.com/Hagb/docker-easyconnect/blob/66ec0313e077d20222c12b3eea1a44740b89d8ae/docker-root/usr/local/bin/start.sh#L11
改成
```
	externals="${externals}external: $iface\\ninternal: $iface port = 1080\\n"
```
（如果提交 PR 的话，同时最好把 `externals` 变量和下面几行与 docker-root/etc/danted.conf.sample 里的 `#external-lines` 也改了，以免 `external` 这个名称让人产生混淆）
