### ISSUE TITLE
the client version and server software version is not matching

### ISSUE THREAD

**Issue by jiudaa** [Hagb/docker-easyconnect#151]
因为需要短信验证码，只能使用vnc图形界面版，但是尝试了7.6.3和7.6.7，打开vnc之后 输入服务器地址，都是显示"the client version and server software version is not matching"，这是为什么啊？

**Comment by twiceyuan** [comment]
有任何进展吗，我们公司 VPN 地址浏览器打开也是 http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb，和 url 中一致，但下载后依然提示版本不匹配。

也尝试了重新 build image，没有用

**Comment by Hagb** [comment]
尝试删除宿主机的 `~/.ecdata` 或者不挂载 `~/.ecdata` 到容器的 `/root`

**Comment by twiceyuan** [comment]
感谢，这个问题已经解决，但登录账号之后 EasyConnect 窗口就消失了，看起来像崩溃。在 log 里也没有看到报错信息

**Comment by crazyhulk** [comment]
有同样的问题，“尝试删除宿主机的 ~/.ecdata 或者不挂载 ~/.ecdata 到容器的 /root” 没有效果
