### ISSUE TITLE
我在manjaro 中使用 docker easyconnect 出现如下错误

### ISSUE THREAD

**Issue by yinxiulong** [Hagb/docker-easyconnect#16]
rm: cannot remove '/usr/share/sangfor/EasyConnect/resources/conf/easy_connect.json': No such file or directory
No protocol specified

**Comment by Hagb** [comment]
Hi. What is your command to run the container?

**Comment by yinxiulong** [comment]
docker run  --device /dev/net/tun \
	 --cap-add NET_ADMIN -ti -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.config/bvpn:/root/.Xauthority \
	 -e EXIT=1 \
	 -e DISPLAY=$DISPLAY \
	  -e URLWIN=1 \
	  -e TYPE=x11 \
	  -v ~/.config/bvpn:/root -p 127.0.0.1:1080:1080 hagb/docker-easyconnect

**Comment by Hagb** [comment]
> ```
> docker run  --device /dev/net/tun \
>  --cap-add NET_ADMIN -ti -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.config/bvpn:/root/.Xauthority \
>  -e EXIT=1 \
>  -e DISPLAY=$DISPLAY \
>   -e URLWIN=1 \
>   -e TYPE=x11 \
>   -v ~/.config/bvpn:/root -p 127.0.0.1:1080:1080 hagb/docker-easyconnect
> ```

Try to run `xhost +LOCAL:` before running the container.

**Comment by yinxiulong** [comment]
xhost + 192.168.1.112
bash: xhost：未找到命令

**Comment by yinxiulong** [comment]
xhost + 192.168.1.112
192.168.1.112 being added to access control list

**Comment by Hagb** [comment]
> xhost + 192.168.1.112
> 192.168.1.112 being added to access control list

Does the error `No protocol specified` still appear?
I think you should use `xhost +LOCAL:` word for word but not `xhost + 192.168.1.112`.

**Comment by yinxiulong** [comment]
我看了一个网友的脚本这样用的。
#!/usr/bin/env bash

SOCK5_PORT=1080
SOCK5_HOST=127.0.0.1
IP=`ifconfig |grep "inet "|grep broadcast|awk '{print $2}'|cut -d/ -f1`

xhost + $IP

cat << EOF >> ~/.ssh/config
# bvpn begin
Host git.corp.example.com
  ProxyCommand=nc -X 5 -x $SOCK5_HOST:$SOCK5_PORT %h %p
# bvpn end
EOF

docker run --rm \
	--device /dev/net/tun \
	--cap-add NET_ADMIN \
	-v ~/.config/bvpn:/root \
	-e DISPLAY=$IP:0 \
	-e TYPE=x11 \
	-e EXIT=1 \
	-p $SOCK5_HOST:$SOCK5_PORT:$SOCK5_PORT \
	hagb/docker-easyconnect:vncless

sed -i'' -e '/# bvpn begin/,/# bvpn end/ d' ~/.ssh/config

xhost - $IP


运行后报错
172.17.0.1 being added to access control list
192.168.1.112 being added to access control list
Unable to find image '192.168.1.112:0' locally
docker: Error response from daemon: pull access denied for 192.168.1.112, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
172.17.0.1 being removed from access control list
192.168.1.112 being added to access control list

**Comment by yinxiulong** [comment]
```
我看了一个网友的脚本这样用的。
#!/usr/bin/env bash

SOCK5_PORT=1080
SOCK5_HOST=127.0.0.1
IP=ifconfig |grep "inet "|grep broadcast|awk '{print $2}'|cut -d/ -f1

xhost + $IP

cat << EOF >> ~/.ssh/config

bvpn begin
Host git.corp.example.com
ProxyCommand=nc -X 5 -x $SOCK5_HOST:$SOCK5_PORT %h %p

bvpn end
EOF

docker run --rm
--device /dev/net/tun
--cap-add NET_ADMIN
-v ~/.config/bvpn:/root
-e DISPLAY=$IP:0
-e TYPE=x11
-e EXIT=1
-p $SOCK5_HOST:$SOCK5_PORT:$SOCK5_PORT
hagb/docker-easyconnect:vncless

sed -i'' -e '/# bvpn begin/,/# bvpn end/ d' ~/.ssh/config

xhost - $IP


```

运行后报错
```
172.17.0.1 being added to access control list
192.168.1.112 being added to access control list
Unable to find image '192.168.1.112:0' locally
docker: Error response from daemon: pull access denied for 192.168.1.112, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
172.17.0.1 being removed from access control list
192.168.1.112 being added to access control list
```

**Comment by Hagb** [comment]
ummm… 你是在什么环境（如操作系统）下使用？

**Comment by yinxiulong** [comment]
![image](https://user-images.githubusercontent.com/26619335/99046245-72d4bc80-25cd-11eb-9be1-95ffe20984cc.png)

**Comment by Hagb** [comment]
运行 `xhost +LOCAL:` 后再运行容器，报错有没有解决吗？

**Comment by yinxiulong** [comment]
我用的manjaro 系统 ，我在easyconnect 社区看到你这个工具，所以打算试试。结果发现还有点搞不定

**Comment by yinxiulong** [comment]
这是现在提示的结果    
  docker run  --device /dev/net/tun  --cap-add NET_ADMIN -ti -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.config/bvpn:/root/.Xauthority  -e EXIT=1  -e DISPLAY=192.168.1.112:0   -e URLWIN=1   -e TYPE=x11   -v ~/.config/bvpn:/root -p 127.0.0.1:1080:1080 hagb/docker-easyconnect
rm: cannot remove '/usr/share/sangfor/EasyConnect/resources/conf/easy_connect.json': No such file or directory

**Comment by Hagb** [comment]
`rm: cannot remove '/usr/share/sangfor/EasyConnect/resources/conf/easy_connect.json': No such file or directory` 这个报错可以忽略。接下来有没有弹出窗口或者输出别的报错？

**Comment by yinxiulong** [comment]
没弹窗窗口。 DISPLAY 这个环境好一直没懂明白。需要安装什么吗？

**Comment by yinxiulong** [comment]
```
docker run  --device /dev/net/tun \
>          --cap-add NET_ADMIN -ti \
>          -v /tmp/.X11-unix:/tmp/.X11-unix  \
>          -v ~/.config/bvpn:/root/.Xauthority \
>          -e EXIT=1  -e DISPLAY=unix:0  \
>          -e URLWIN=1   -e TYPE=x11  \
>          -v ~/.config/bvpn:/root -p 127.0.0.1:1080:1080 hagb/docker-easyconnect

```
我把 DISPLAY 改成 -e DISPLAY=unix:0  就 窗口弹出来了。vpn 也链接了，但是我本地的网络依然不能链接远程的机器。

**Comment by Hagb** [comment]
> 没弹窗窗口。

有点怪…… 终端输出了什么？
另外，如果还是不行的话，试试先把原来的容器关掉，再新开一个终端，然后运行
``` bash
xhost +LOCAL:
docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.Xauthority:/root/.Xauthority -e EXIT=1 -e DISPLAY=$DISPLAY -e URLWIN=1 -e TYPE=x11 -v $HOME/.ecdata:/root -p 127.0.0.1:1080:1080 hagb/docker-easyconnect
```
看看行不行?（会不会弹出个 EasyConnect 的窗口）

> DISPLAY 这个环境好一直没懂明白。需要安装什么吗？

不需要安装额外的东西。这个东西是指定 x11 server 的（这里是用于告诉 EasyConnect 它的界面往那儿显示用的）。

**Comment by Hagb** [comment]
> 但是我本地的网络依然不能链接远程的机器。

可以使用 socks 代理 `127.0.0.1:1080` 来连接。

**Comment by yinxiulong** [comment]
![Uploading image.png…]()

**Comment by yinxiulong** [comment]
这样代理吗？ 没生效呢

**Comment by Hagb** [comment]
> Uploading image.png…

图没被传上来呢似乎

**Comment by yinxiulong** [comment]
![image](https://user-images.githubusercontent.com/26619335/99049430-ccd78100-25d1-11eb-9250-07981c84a3bd.png)

**Comment by yinxiulong** [comment]
这样配置了，vpn依然不能访问对方资源

**Comment by yinxiulong** [comment]
我好像找到原因了。是因为这个的原因 
![image](https://user-images.githubusercontent.com/26619335/99049819-44a5ab80-25d2-11eb-9402-01419bb8db7c.png)
我浏览器开启的谷歌上网助手。导致的，我把这个谷歌上网助手关了后，可以vpn可以访问对方的资源了

**Comment by yinxiulong** [comment]
很谢谢你。高手

**Comment by yinxiulong** [comment]
弹窗的界面是英文，中文是乱码。有解决方法吗？

**Comment by Hagb** [comment]
> 弹窗的界面是英文，中文是乱码。有解决方法吗？

TL;DR：可以给容器启动的命令里加上参数 `--mount type=bind,source=/usr/share/fonts/,target=/usr/share/fonts/,readonly` （不要在 `hagb/docker-easyconnect` 之后加）

参看 [README](https://github.com/Hagb/docker-easyconnect/blob/master/README.md):
> ## 无法显示中文
>
> 原因是 image 内无中文字体。可以通过修改 EasyConnect 前端的语言为英语来绕过中文显示的问题。也可以安装或挂载中文字体进容器中。
>
> 详见 #2。
