### ISSUE TITLE
Client version is inconsistent with server

### ISSUE THREAD

**Issue by MrAru** [Hagb/docker-easyconnect#160]
![Screenshot_20220720_015345](https://user-images.githubusercontent.com/26517155/179817506-e259c3a9-6f6f-4841-9196-0b7ac7b62fbb.png)

Client version: hagb/docker-easyconnect:7.6.7

The client version downloaded from the official page is EasyConnect_x64_7_6_7_3.deb (https://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb).
Any workaround?

**Comment by Hagb** [comment]
It seems that the local EasyConnect is outdated. Try to rebuild the image or pull the latest image (the image in DockerHub was just rebuilt).

**Comment by MrAru** [comment]
Thanks for your quick reply. This issue was addressed with the latest image.
