### ISSUE TITLE
M1 Mac 运行失败，qemu-x86_64 找不到文件

### ISSUE THREAD

**Issue by lealaxy** [Hagb/docker-easyconnect#167]
> 请问ARM版安装命令是什么？我用的安装命令是：docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -p 1080:1080 -p 8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d vpnaddress -u username -p password" hagb/dock er-easyconnect:cli，但是提示错误： ![QQ截图20220218170057](https://user-images.githubusercontent.com/49972690/154651244-9b6f47f7-ab3b-437d-b219-a488b5f28dd7.png)

哦我没有把arm镜像上传dockerhub，需要下载 https://github.com/Hagb/docker-easyconnect/tree/non-amd64 分支并使用
```shell
docker image build -f Dockerfile.fake-hwaddr -t fake-hwaddr .
docker image build --tag hagb/docker-easyconnect -f Dockerfile.cli .
```
自行编译。

之后再用
```
docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -p 1080:1080 -p 8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d vpnaddress -u username -p password" hagb/docker-easyconnect
```
运行

_Originally posted by @Hagb in https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1044213653_

**Comment by lealaxy** [comment]
我按照 #25 的方式在M1 Mac上编译了easyconnect，但是运行时报qemu错误

WARNING: logging deactivated (can't log to stdout when daemonized)
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
svpn stop!

**Comment by Hagb** [comment]
> > 请问ARM版安装命令是什么？我用的安装命令是：docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -p 1080:1080 -p 8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d vpnaddress -u username -p password" hagb/dock er-easyconnect:cli，但是提示错误： ![QQ截图20220218170057](https://user-images.githubusercontent.com/49972690/154651244-9b6f47f7-ab3b-437d-b219-a488b5f28dd7.png)
> 
> 哦我没有把arm镜像上传dockerhub，需要下载 https://github.com/Hagb/docker-easyconnect/tree/non-amd64 分支并使用
> 
> ```shell
> docker image build -f Dockerfile.fake-hwaddr -t fake-hwaddr .
> docker image build --tag hagb/docker-easyconnect -f Dockerfile.cli .
> ```
> 
> 自行编译。
> 
> 之后再用
> 
> ```
> docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -p 1080:1080 -p 8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d vpnaddress -u username -p password" hagb/docker-easyconnect
> ```
> 
> 运行
> 
> _Originally posted by @Hagb in [#25 (comment)](https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1044213653)_

从日志上看，运行的时候用的是 dockerhub 上的镜像。编译的时候 tag 是 `hagb/docker-easyconnect`，故而运行的时候不要带上 `:cli`

另外现版本 qemu 有内存溢出的 bug，如需 workaround 版本请用 `thread_reuse` 分支

**Comment by lealaxy** [comment]
ok，我编译了`thread_reuse`分支之后可以在M1芯片上运行了
