### ISSUE TITLE
The last GitHub Actions build failed

### ISSUE THREAD

**Issue by lujiajing1126** [Hagb/docker-easyconnect#168]
https://github.com/Hagb/docker-easyconnect/runs/7820173979?check_suite_focus=true

Would you pls rerun this action? Thx!

**Comment by lujiajing1126** [comment]
Also, local build failed. A workaround would be download manually the deb file.

**Comment by Hagb** [comment]
Thanks for reminding! I have successfully rerun the action. The problem seems temporary.
