### ISSUE TITLE
关于知网IP登录

### ISSUE THREAD

**Issue by cache0928** [Hagb/docker-easyconnect#172]
使用docker走socks代理后，可以访问内网，但是学校提供的知网貌似限定IP范围，无法代理登录，请问是否有什么方法可以实现？

**Comment by Hagb** [comment]
检查一下知网给出你当前的 ip 和 ip.cn 显示的 ip 是否同一个？我这里测试发现如果事先在没开代理的时候上了知网，再开代理上知网知网可能会获取到错误的 ip，清除了 cookie 之后就能够正常登录了（原理未知）

**Comment by cache0928** [comment]
@Hagb 请问你docker开启之后是如何使用socks代理？配置系统的代理还是使用surge或者clash之类的按规则代理知网？

**Comment by cache0928** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/7350995/187805171-d394f1bb-d120-4344-a6cd-b0405c5886bd.png">
@Hagb 我通过Surge配置`DOMAIN-SUFFIX,cnki.net,VPN`规则来代理知网，发现图中3个请求一直会超时，虽然显示登录成功，但是无法使用知网，包括搜索论文都会超时

**Comment by Hagb** [comment]
> @Hagb 请问你docker开启之后是如何使用socks代理？配置系统的代理还是使用surge或者clash之类的按规则代理知网？

在浏览器里配置的代理。我没用过 surge

**Comment by cache0928** [comment]
根据规则细分是否走代理之后好像可以了
