### ISSUE TITLE
Easyconnect识别为MAC系统

### ISSUE THREAD

**Issue by chenlong1231** [Hagb/docker-easyconnect#174]
现登录后识别为MAC系统，请问如何修改才能让easyconnect识别为Linux系统？谢谢了

**Comment by Hagb** [comment]
请问在哪里可以看这个？我没有找到

**Comment by Hagb** [comment]
> 请问在哪里可以看这个？我没有找到

我似乎找到了，但我们学校的服务器好像有点问题看不到那个

**Comment by chenlong1231** [comment]
感谢回复！在历史消息中可以看到登录的状态，如果在咱们docker内登录显示的是MAC客户端。
![Login_status](https://user-images.githubusercontent.com/2703862/187839759-017b9934-bb43-46e9-a0f6-8ab8bc64bab9.png)

**Comment by Hagb** [comment]
感谢反馈！一开始发现 7.6.3 无法复现，7.6.7 可以复现，最终还是翻客户端的源码翻到了原因。将 `"sys_type": "linux"` 写入 `/root/conf/easy_connect.json` 就好（原本这个文件由客户端自动生成的就没有这个问题，但是为了把语言设成英语所以由容器化的脚本生成了），客户端默认没拿到 `sys_type` 值的话会认为自己在 Mac 下

**Comment by chenlong1231** [comment]
非常感谢修复！
