### ISSUE TITLE
wsl2环境报错

### ISSUE THREAD

**Issue by CECoffee** [Hagb/docker-easyconnect#178]
iptables v1.8.2 (nf_tables): Chain 'MASQUERADE' does not exist
Try 'iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables): Couldn't load match 'state':No such file or directory

Try 'iptables -h' or 'iptables --help' for more information.
iptables v1.8.2 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain INPUT

**Comment by Hagb** [comment]
尝试加上 `-e IPTABLES_LEGACY=1` 参数来启动容器

**Comment by CECoffee** [comment]
已解决
