### ISSUE TITLE
系统代理开了后。只能浏览器能用，其他应用都不能用，如 navicat  都链接不了

### ISSUE THREAD

**Issue by yinxiulong** [Hagb/docker-easyconnect#18]
系统代理开了后。只能浏览器能用，其他应用都不能用，如 navicat  都链接不了，难道所有需要用vpn 的应用都需要开代理才可以用吗

**Comment by Hagb** [comment]
socks 是非透明代理，只有支持 socks 代理的应用能够直接使用。
如果应用不支持 socks 或者不方便设置，这里给出了几种我所知的方案以供参考：
- [proxychains](https://github.com/rofl0r/proxychains-ng)
- 将 socks 代理转为支持更广泛的 http 代理：如 [polipo](https://github.com/jech/polipo)
- [基于路由表和 ip forwarding 的透明代理](https://hagb.name/2020/06/26/easyconnect-proxy.html)

**Comment by yinxiulong** [comment]
我试验了这个   [基于路由表和ip forward的透明代理  ] 这个方法。 vpn 能用，但是不能上网了。执行这些命令的时候，报错 
sudo ip route flush table 3
sudo ip route add table 3 default via "$IP" mtu "$MTU"
sudo ip rule add iif lo table 3 

报错内容，
 sudo ip route add table 3 default via "$IP" mtu "$MTU"
[sudo]  的密码：
Error: any valid address is expected rather than "".

**Comment by Hagb** [comment]
> 我试验了这个 [基于路由表和ip forward的透明代理 ] 这个方法。 vpn 能用，但是不能上网了。执行这些命令的时候，报错

意思是说在容器外能访问 vpn 的网络但是不能访问互联网，还是说只有容器内能访问网络了？
执行`sudo ip rule del iif lo table 3`可以使这三条命令的修改不生效。

> sudo ip route flush table 3
> sudo ip route add table 3 default via "$IP" mtu "$MTU"
> sudo ip rule add iif lo table 3
> 
> 报错内容，
> sudo ip route add table 3 default via "$IP" mtu "$MTU"
> [sudo] 的密码：
> Error: any valid address is expected rather than "".

这是把这三条命令单独拿出来执行了吗？
如果是单独执行的话，`$IP`处填写容器的 ip（或者把`IP`变量设为容器 ip），`$MTU` 一般是 `1480`。

**Comment by yinxiulong** [comment]
容器外能访问VPN的网络，但是百度等用不了 yinxiulong 邮箱：yinxiulong@aliyun.com 签名由 网易邮箱大师 定制 在2020年11月19日 00:44，Hagb (Guo Junyu 郭俊余) 写道： 我试验了这个 [基于路由表和ip forward的透明代理 ] 这个方法。 vpn 能用，但是不能上网了。执行这些命令的时候，报错 意思是说在容器外能访问 vpn 的网络但是不能访问互联网，还是说只有容器内能访问网络了？ 执行sudo ip rule del iif lo table 3可以使这三条命令的修改不生效。 sudo ip route flush table 3 sudo ip route add table 3 default via "$IP" mtu "$MTU" sudo ip rule add iif lo table 3 报错内容， sudo ip route add table 3 default via "$IP" mtu "$MTU" [sudo] 的密码： Error: any valid address is expected rather than "". 这是把这三条命令单独拿出来执行了吗？ 如果是单独执行的话，$IP处填写容器的 ip（或者把IP变量设为容器 ip），$MTU 一般是 1480。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yinxiulong** [comment]
sudo ip rule del iif lo table 3执行了这行命令还是不生效。我进容器看mtu为1400 yinxiulong 邮箱：yinxiulong@aliyun.com 签名由 网易邮箱大师 定制 在2020年11月19日 00:49，yinxiulong@aliyun.com 写道： 容器外能访问VPN的网络，但是百度等用不了 yinxiulong 邮箱：yinxiulong@aliyun.com 签名由 网易邮箱大师 定制 在2020年11月19日 00:44，Hagb (Guo Junyu 郭俊余) 写道： 我试验了这个 [基于路由表和ip forward的透明代理 ] 这个方法。 vpn 能用，但是不能上网了。执行这些命令的时候，报错 意思是说在容器外能访问 vpn 的网络但是不能访问互联网，还是说只有容器内能访问网络了？ 执行sudo ip rule del iif lo table 3可以使这三条命令的修改不生效。 sudo ip route flush table 3 sudo ip route add table 3 default via "$IP" mtu "$MTU" sudo ip rule add iif lo table 3 报错内容， sudo ip route add table 3 default via "$IP" mtu "$MTU" [sudo] 的密码： Error: any valid address is expected rather than "". 这是把这三条命令单独拿出来执行了吗？ 如果是单独执行的话，$IP处填写容器的 ip（或者把IP变量设为容器 ip），$MTU 一般是 1480。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yinxiulong** [comment]
```
sudo ip route flush table 3
sudo ip route add table 3 default via "$IP" mtu "$MTU"
sudo ip rule add iif lo table 3
```
没有单独执行，是运行脚本的时候执行的。 刚我执行了sudo ip route flush table 3 这条命令，可以访问外网了，但是vpn 的网络又不能访问了。

**Comment by Hagb** [comment]
> ```
> sudo ip route flush table 3
> sudo ip route add table 3 default via "$IP" mtu "$MTU"
> sudo ip rule add iif lo table 3
> ```
> 
> 没有单独执行，是运行脚本的时候执行的。 刚我执行了sudo ip route flush table 3 这条命令，可以访问外网了，但是vpn 的网络又不能访问了。

那此时容器内能不能访问外网？
如果不能，说明容器的规则如此，设置路由表时可以把`sudo ip route add table 3 default via "$IP" mtu "$MTU"`里的`default`改为需要走 vpn 的地址（或网段），其他连接就不会从容器经过。

**Comment by yinxiulong** [comment]
default改为需要走 vpn 的地址（或网段）  如这样吗？  172.112.0.0/24

**Comment by yinxiulong** [comment]
改了default 可以了，很谢谢你这么晚了还帮我解决问题
