### ISSUE TITLE
断线自动重连机制开关

### ISSUE THREAD

**Issue by ghdefe** [Hagb/docker-easyconnect#180]
## 描述
在网络不稳定的情况下，出现vpn网络暂时不可用，过段时间会恢复。此时docker-easyconnect检测到掉线，会自动重启进程，导致需要重新登录。

## 建议
提供一个开关，由用户决定是否需要掉线自动重启线程

**Comment by Hagb** [comment]
尝试 `-e EXIT=1` 参数

**Comment by ghdefe** [comment]
> 尝试 `-e EXIT=1` 参数用于关闭自动重连

设置EXIT参数后还是会退出，EXIT参数是不是用于设置重连次数，如果小于0则退出容器。是不是应该设置成wait而不是exit

> docker-root/usr/local/bin/start.sh
```
...
[ -n "$EXIT" ] && MAX_RETRY=0
...
```

> docker-root/usr/local/bin/start-sangfor.sh
```
	# 自动重连
	((MAX_RETRY<0)) && exit

	# 清除的残余进程，它们可能会妨碍下次的启动。
	killall CSClient svpnservice 2> /dev/null
	kill %1 %2 2> /dev/null
	sleep 4
```

**Comment by Hagb** [comment]
> 设置EXIT参数后还是会退出，EXIT参数是不是用于设置重连次数，如果小于0则退出容器。是不是应该设置成wait而不是exit

@ghdefe  “设置EXIT参数后还是会退出” 意思是？预期现象是设了 `EXIT=1` 之后不会自动重连且退出客户端后会自动关闭容器。实际情况是刚刚发现在这里有个 bug，这行的 MAX_RETRY 应该加个 export 设成环境变量才能传导到 start-sangfor.sh
https://github.com/Hagb/docker-easyconnect/blob/70156b22b1f7b6267ba954aa217ed6ce13e2c18a/docker-root/usr/local/bin/start.sh#L60

> EXIT参数是不是用于设置重连次数，如果小于0则退出容器。

`MAX_RETRY` 用于限制重连次数，设为 0 则是不进行进行重连。

> 是不是应该设置成wait而不是exit

这里用 `exit` 而不是 `wait` 是因为如果 vpn 正在运行中的话，脚本会阻塞在上面而不会运行到下面。

**Comment by ghdefe** [comment]
@Hagb 设置参数后还是会退出: 设置了EXIT=1，vpn断线时，仍然会被kill然后重新打开登录页面。应该跟你描述的一样，是因为最大重连次数变量没有传递导致的。

我有一个新问题
### 现象
在vpn出现网络波动时，vpn在运行中，但脚本不会阻塞而是直接进行重连。
### 具体描述
我使用的是有前端的版本，我理解`sslservice.sh`是启动后端服务，`/usr/share/sangfor/EasyConnect/EasyConnect`是前端服务。猜想是`sslservice.sh`在运行，但前端`/usr/share/sangfor/EasyConnect/EasyConnect`由于某些原因退出了（可能是easyConnect本身的bug或feature导致）。
https://github.com/Hagb/docker-easyconnect/blob/70156b22b1f7b6267ba954aa217ed6ce13e2c18a/docker-root/usr/local/bin/start-sangfor.sh#L9-L17

### 建议
设置变量使得它不直接退出容器，而是一直等待（这可能会导致用户无法感知vpn异常）。现在vpn暂时不可用，过段时间我修改一下这个脚本验证是否可以通过这个方式绕过网络波动导致的掉线问题
> docker-root/usr/local/bin/start-sangfor.sh
```shell
[ -n "$DO_NOT_EXIT" ] && wait
```

**Comment by Hagb** [comment]
突然想起在 `develop` 分支中为了实现更精确的控制，直接调用了相应的守护进程而没有使用 `sslservice.sh`；此外下载了 electron 官方版本而非使用随着 EasyConnect 分发的 electron。

`develop` 的 docker 镜像可用 docker pull hagb/docker-easyconnect:dev-7.6.3 或 hagb/docker-easyconnect:dev-7.6.7 获取

请问是否方便测试一下 `develop` 分支中
- 前端会不会自动关闭
- 会不会自动重连（我猜测自动重连有可能是 `EasyMonitor` 导致的）
