### ISSUE TITLE
为啥要把easyconnect放在docker中运行？

### ISSUE THREAD

**Issue by X-F-L** [Hagb/docker-easyconnect#188]
为啥要把easyconnect放在docker中运行再做个代理，让宿主机访问VPN网络资源。本人测试过在手机上登录VPN之后在手机上直接开启socks5代理，通过电脑可以访问VPN内网资源

**Comment by lyfer233** [comment]
> 为啥要把easyconnect放在docker中运行再做个代理，让宿主机访问VPN网络资源。本人测试过在手机上登录VPN之后在手机上直接开启socks5代理，通过电脑可以访问VPN内网资源

可以详细说明一下怎么整吗？ 是Android手机吗

**Comment by LouisTay** [comment]
正解。更好的形式其实是比如你在校内有一台内网机器，配合一台公网服务器，搭建frp服务可以直接有一个socks5代理，也可以实现socks5代理的身份认证。

**Comment by Hagb** [comment]
在 Android 中运行确实也是一个思路。

我做这个镜像最主要的原因是 EasyConnect 是闭源的，不放心直接运行，况且它还需要 root 权限。另外 EasyConnect 做的很多操作都有点粗放（或者说粗野），比如劫持所有 dns 查询。
