### ISSUE TITLE
需要一个新版本：7.6.7.4

### ISSUE THREAD

**Issue by shenzhuangzhi1** [Hagb/docker-easyconnect#192]

**Comment by Hagb** [comment]
能提供客户端下载地址吗？从版本号来看只是深信服的一个小更新，估计重新构建一下镜像就可以。docker hub 上的镜像刚刚也进行了感谢，docker pull 下最新的镜像应该就可以了

**Comment by jackieLiu** [comment]
应该是Linux版本没有更新，直接提示与服务器版本不一致。

**Comment by Hagb** [comment]
> 应该是Linux版本没有更新，直接提示与服务器版本不一致。

试试不挂载 `/root`？（去掉 `-v xxxx:/root` 参数）

**Comment by jackieLiu** [comment]
https://github.com/Hagb/docker-easyconnect/issues/192#issuecomment-1321012736
可以，多谢。

**Comment by jackieLiu** [comment]
> 

可以了，多谢。

**Comment by jackieLiu** [comment]
> 试试不挂载 /root？（去掉 -v xxxx:/root 参数）
可以了，删除旧的配置，就可以了，多谢。

**Comment by Hagb** [comment]
> > 能提供客户端下载地址吗？从版本号来看只是深信服的一个小更新，url 应该还是没变，估计重新构建一下镜像就可以。docker hub 上的镜像刚刚也进行了感谢，docker pull 下最新的镜像应该就可以了
> 
> 如果可以的话，是否可以提供一个邮箱，我把客户端发一下，您那边直接打包更新到您的docker hub，这样也方便大家一起用，您意下如何？

@shenzhuangzhi1 谢谢，我的邮箱是 hagb AT hagb.name（顺带请确保是最新版的客户端，深信服可能会对客户端进行一些小更新的情况下不改变 url，事实上那么多次更新也没有见过它改变 url）。不过深信服虽然更新到 `7.6.7.x`（x>3），下载地址依然还是 http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb 没变。你那儿的最新版本的下载地址和这个相同吗？（方便的话可以和客户端下载地址一起发吗？）

**Comment by shenzhuangzhi1** [comment]
> > > 能提供客户端下载地址吗？从版本号来看只是深信服的一个小更新，url 应该还是没变，估计重新构建一下镜像就可以。docker hub 上的镜像刚刚也进行了感谢，docker pull 下最新的镜像应该就可以了
> > 
> > 
> > 如果可以的话，是否可以提供一个邮箱，我把客户端发一下，您那边直接打包更新到您的docker hub，这样也方便大家一起用，您意下如何？
> 
> @shenzhuangzhi1 谢谢，我的邮箱是 hagb AT hagb.name（顺带请确保是最新版的客户端，深信服可能会对客户端进行一些小更新的情况下不改变 url，事实上那么多次更新也没有见过它改变 url）。不过深信服虽然更新到 `7.6.7.x`（x>3），下载地址依然还是 http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb 没变。你那儿的最新版本的下载地址和这个相同吗？（方便的话可以和客户端下载地址一起发吗？）

我使用的是macOS可以下载到最新的7.6.7.4，但是deb包却如你所言。我建议保持这个issue为open和pin状态，直到该问题解决，防止出现同类问题的同时，增加该问题的醒目程度，以加速该问题的解决，毕竟众人拾柴火焰高嘛

**Comment by Hagb** [comment]
> 我使用的是macOS可以下载到最新的7.6.7.4，但是deb包却如你所言。我建议保持这个issue为open和pin状态，直到该问题解决，防止出现同类问题的同时，增加该问题的醒目程度，以加速该问题的解决，毕竟众人拾柴火焰高嘛

现在情况其实是这样（我之前可能描述得不太清楚，不知道我们理解是不是一样）。
deb 包虽然 url 里面的文件名一直是 `EasyConnect_x64_7_6_7_3.deb`，但其实内容已经变了很多次，更新到 `7.6.7.x`（x>3）了。

我刚刚在 http://download.sangfor.com.cn/download/product/sslvpn/pkg/pkg_version.xml 上看了看 Linux 版已经更新到 `7.6.7.7`（这和 deb 包本身的版本一致），Mac 更到 `7.6.7.9`。

你说的 `7.6.7.4` 或许是服务端的自定义版本？或者因为服务端本身的版本比较久所以客户端才落后于最新版么？

此外，`docker pull` 最新版的 `7.6.7` 镜像，然后以不挂载 `/root`（去掉 -v xxxx:/root 参数）的方式运行，能否连接上服务端。如果不能，有什么提示？

**Comment by Hagb** [comment]
@shenzhuangzhi1 我刚刚看了一下，mac 那个包也是 url 不变但是版本在更新的情况，mac 包的 url 保持在 <http://download.sangfor.com.cn/download/product/sslvpn/pkg/mac_767/EasyConnect_7_6_7_4.dmg>（可以检查一下你服务端提供的下载地址是不是这个），虽然文件名上看是· `7.6.7.4`，但是实际上是 `7.6.7.9`（目前）。这个版本应该可以在 EasyConnect 的某个文件夹里的 `./Resources/conf/Version.xml` 看到

**Comment by shenzhuangzhi1** [comment]
> > 我使用的是macOS可以下载到最新的7.6.7.4，但是deb包却如你所言。我建议保持这个issue为open和pin状态，直到该问题解决，防止出现同类问题的同时，增加该问题的醒目程度，以加速该问题的解决，毕竟众人拾柴火焰高嘛
> 
> @shenzhuangzhi1 现在情况其实是这样（我之前可能描述得不太清楚，不知道我们理解是不是一样）。 deb 包虽然 url 里面的文件名一直是 `EasyConnect_x64_7_6_7_3.deb`，但其实内容已经变了很多次，更新到 `7.6.7.x`（x>3）了。
> 
> 我刚刚在 http://download.sangfor.com.cn/download/product/sslvpn/pkg/pkg_version.xml 上看了看 Linux 版已经更新到 `7.6.7.7`（这和 deb 包本身的版本一致），Mac 更到 `7.6.7.9`。
> 
> 你说的 `7.6.7.4` 或许是服务端的自定义版本？或者因为服务端本身的版本比较旧所以客户端才落后于最新版么？
> 
> 此外，`docker pull` 最新版的 `7.6.7` 镜像，然后以不挂载 `/root`（去掉 -v xxxx:/root 参数）的方式运行，能否连接上服务端？如果不能，有什么提示？

这个服务端的版本应该不是很旧，因为我们是新项目。使用的也是新的logo（比较亮的那一个）
自定义我觉得不太可能，因为功能是一样的，并没有其他我已知版本的那种总特性，
我从未使用过 `-v`

**Comment by shenzhuangzhi1** [comment]
> @shenzhuangzhi1 我刚刚看了一下，mac 那个包也是 url 不变但是版本在更新的情况，mac 包的 url 保持在 http://download.sangfor.com.cn/download/product/sslvpn/pkg/mac_767/EasyConnect_7_6_7_4.dmg（可以检查一下你服务端提供的下载地址是不是这个），虽然文件名上看是· `7.6.7.4`，但是实际上是 `7.6.7.9`（目前）。这个版本应该可以在 EasyConnect 的某个文件夹里的 `./Resources/conf/Version.xml` 看到

mac版的文件内容是这样的：
```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
<alias>mac_767</alias>
<version>7.6.7.9</version>
<svn>_</svn>
</root>
```

**Comment by shenzhuangzhi1** [comment]
> @shenzhuangzhi1 我刚刚看了一下，mac 那个包也是 url 不变但是版本在更新的情况，mac 包的 url 保持在 http://download.sangfor.com.cn/download/product/sslvpn/pkg/mac_767/EasyConnect_7_6_7_4.dmg（可以检查一下你服务端提供的下载地址是不是这个），虽然文件名上看是· `7.6.7.4`，但是实际上是 `7.6.7.9`（目前）。这个版本应该可以在 EasyConnect 的某个文件夹里的 `./Resources/conf/Version.xml` 看到

所以我需要使用`7.6.7.9`版本的client吗？

**Comment by Hagb** [comment]
> 所以我需要使用`7.6.7.9`版本的client吗？

@shenzhuangzhi1  emmm 其实 Linux 和 Mac 要求的客户端版本是有差异的（见 <http://download.sangfor.com.cn/download/product/sslvpn/pkg/pkg_version.xml>，里面 `force_update_le` 项应该就是强制需要更新的版本），Linux 用最新的就好

**Comment by shenzhuangzhi1** [comment]
> 
最新版的linux的GUI版本可以更新一下吗？

**Comment by Hagb** [comment]
> 最新版的linux的GUI版本可以更新一下吗？

@shenzhuangzhi1  dockrer hub 上的镜像已是最新，如果自己构建的话直接在 master 分支上进行构建就行（可能需要关闭构建缓存）。

**Comment by Flagami** [comment]
> @shenzhuangzhi1 我刚刚看了一下，mac 那个包也是 url 不变但是版本在更新的情况，mac 包的 url 保持在 http://download.sangfor.com.cn/download/product/sslvpn/pkg/mac_767/EasyConnect_7_6_7_4.dmg（可以检查一下你服务端提供的下载地址是不是这个），虽然文件名上看是· `7.6.7.4`，但是实际上是 `7.6.7.9`（目前）。这个版本应该可以在 EasyConnect 的某个文件夹里的 `./Resources/conf/Version.xml` 看到

🙋我确认过了，就是这个url

**Comment by Flagami** [comment]
> @shenzhuangzhi1 我刚刚看了一下，mac 那个包也是 url 不变但是版本在更新的情况，mac 包的 url 保持在 http://download.sangfor.com.cn/download/product/sslvpn/pkg/mac_767/EasyConnect_7_6_7_4.dmg（可以检查一下你服务端提供的下载地址是不是这个），虽然文件名上看是· `7.6.7.4`，但是实际上是 `7.6.7.9`（目前）。这个版本应该可以在 EasyConnect 的某个文件夹里的 `./Resources/conf/Version.xml` 看到

那么这种情况下，该用哪个版本呢？
