### ISSUE TITLE
部分资源无法访问问题

### ISSUE THREAD

**Issue by qiweifan** [Hagb/docker-easyconnect#195]
宿主机：Apple M1 Pro macOS 13.0.1 (22A400)

Docker Desktop：4.9.0 (80466)

镜像：hagb/docker-easyconnect:7.6.3

问题描述：

​		在使用带vnc的7.6.3版本镜像时，有个资源172.21.50.113（同网段其他资源无问题）一直无法访问，在直接安装easyconnect7.6.3客户端的情况下是可以的，所以可确定不是服务端的问题，容器内部安装的tcpdump可能是因为CPU架构的原因无法抓包一直提示“tcpdump: tunl0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Function not implemented”。

​		在宿主机发请求并在宿主机tcpdump抓包时发现发出SYN包后就没有任何回复了。

​		请问这种情况可能会是什么原因？应该如何排查问题？

**Comment by Hagb** [comment]
> ​ 请问这种情况可能会是什么原因？应该如何排查问题？

可能是容器中路由的问题，可以看看在容器中运行 `ip route get 172.21.50.113` 看看是不是从 tun0 走。

**Comment by qiweifan** [comment]
> 

之前用curl --interface tun0命令试过访问该资源也是不行，本地路由表中也没有改资源，相临的172.21.50.112都是有的。

**Comment by Hagb** [comment]
> 之前用curl --interface tun0命令试过访问该资源也是不行，本地路由表中也没有这个IP，相临的172.21.50.112都是有的。 @Hagb

试试手动把这个 ip 加入容器里的路由表呢？一般是 `ip route add 172.21.50.113 via 网关 dev tun0`（可参照其他路由）
