### ISSUE TITLE
vnc 显示不全

### ISSUE THREAD

**Issue by cfeitong** [Hagb/docker-easyconnect#201]
![image](https://user-images.githubusercontent.com/8102200/206894032-ca48c2d0-d29a-4388-b4ca-475851175cf3.png)
如图所示，vnc连接后界面显示不全，是否可以考虑加个vnc分辨率的环境变量？

**Comment by Hagb** [comment]
感谢反馈和提议。已经加入 `VNC_SIZE` 环境变量，可以通过 `宽x高` 的格式来设置。
此外，默认分辨率已经调整为 7.6.7 登录后的默认窗口大小 `1110x620`（似乎是这个，待验证）。
