### ISSUE TITLE
可否将ip forward方式细化一下

### ISSUE THREAD

**Issue by libra146** [Hagb/docker-easyconnect#203]
通过socks5的方式已经运行成功，但是除了浏览器还有其他的程序需要使用vpn，但是不确定如何使用
另外这里有个问题，就是路由表都是通过ip的方式来指定的下一跳，但是应该如何将dns包转发到docker中呢？希望作者能提供一些思路，谢谢～

**Comment by Hagb** [comment]
> 另外这里有个问题，就是路由表都是通过ip的方式来指定的下一跳，但是应该如何将dns包转发到docker中呢？希望作者能提供一些思路，谢谢～

这里将 dns 包转发到 docker 的意思是？
EasyConnect 的 dns 服务器是通过对本地发出的 dns 查询进行 dnat 进行来做的：
```bash
iptables -t nat -A OUTPUT -p 17 -m udp ! --sport 7789 --dport 53 -j REDIRECT --to-ports 5373
```

如果要通过容器访问其他 dns 服务器，那么就需要将这条规则删掉。

**Comment by libra146** [comment]
> > 另外这里有个问题，就是路由表都是通过ip的方式来指定的下一跳，但是应该如何将dns包转发到docker中呢？希望作者能提供一些思路，谢谢～
> 
> 这里将 dns 包转发到 docker 的意思是？ EasyConnect 的 dns 服务器是通过对本地发出的 dns 查询进行 dnat 进行来做的：
> 
> ```shell
> iptables -t nat -A OUTPUT -p 17 -m udp ! --sport 7789 --dport 53 -j REDIRECT --to-ports 5373
> ```
> 
> 如果要通过容器的代理访问其他 dns 服务器，那么就需要将这条规则删掉。

是我糊涂了，我是想如果想通过docker提供的socks5代理访问某一个域名的话，应该怎么解决域名解析的问题，因为可能是内网的域名，无法在公网的dns解析，当时是想，怎么才能把dns请求转发进docker进行dns解析。。。

后来才想起来用了socks5代理默认就是通过代理去解析域名，🤣哈哈哈，可以忽略这条了，感谢大佬回复～

**Comment by TurnOffNOD** [comment]
> > 另外这里有个问题，就是路由表都是通过ip的方式来指定的下一跳，但是应该如何将dns包转发到docker中呢？希望作者能提供一些思路，谢谢～
> 
> 这里将 dns 包转发到 docker 的意思是？ EasyConnect 的 dns 服务器是通过对本地发出的 dns 查询进行 dnat 进行来做的：
> 
> ```shell
> iptables -t nat -A OUTPUT -p 17 -m udp ! --sport 7789 --dport 53 -j REDIRECT --to-ports 5373
> ```
> 
> 如果要通过容器的代理访问其他 dns 服务器，那么就需要将这条规则删掉。

这个啥时候能兼容nftables?
