### ISSUE TITLE
请问现在有mac m1上成功的相对稳定的案例吗？

### ISSUE THREAD

**Issue by wjfu99** [Hagb/docker-easyconnect#206]
现在 develop 分支支持从上面的 zip 包地址（https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1233369467 ）中提取 deb 包:
```shell
docker image build -f Dockerfile.build -t hagb/docker-easyconnect:build .
docker image build --build-arg EC_URL=zip包下载地址 --build-arg EC_DEB_PATH=deb包在zip包中的路径 --tag hagb/docker-easyconnect -f Dockerfile .
```
如 arm64 的 M761-M766R1（7.6.3）版：
```shell
docker image build -f Dockerfile.build -t hagb/docker-easyconnect:build .
docker image build \
    --build-arg EC_URL=https://download.sangfor.com.cn/download/product/sslvpn/SSLVPN%E4%BF%A1%E5%88%9B%E5%AE%A2%E6%88%B7%E7%AB%AF/%E7%BB%9F%E4%BF%A1UOS%20%E9%B2%B2%E9%B9%8F%20SSL%20VPN%E5%AE%A2%E6%88%B7%E7%AB%AF.zip \
    --build-arg EC_DEB_PATH=UOS_EasyConnect_arm64.deb \
    --tag hagb/docker-easyconnect -f Dockerfile .
```
arm64 的 M767+（7.6.7）版：
```shell
docker image build -f Dockerfile.build -t hagb/docker-easyconnect:build .
docker image build \
    --build-arg EC_URL=https://download.sangfor.com.cn/download/product/sslvpn/SSLVPN%E4%BF%A1%E5%88%9B%E5%AE%A2%E6%88%B7%E7%AB%AF/%E7%BB%9F%E4%BF%A1UOS%20%E6%B5%B7%E6%80%9D%E9%BA%92%E9%BA%9F990%20SSL%20VPN%E5%AE%A2%E6%88%B7%E7%AB%AF.zip \
    --build-arg EC_DEB_PATH=02-升级包及安装文件/EasyConnect_UOS_arm64-20220302.deb \
    --tag hagb/docker-easyconnect -f Dockerfile .
```
请反馈使用情况

_Originally posted by @Hagb in https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1256860002_

按照这里的方案手动编译了，但是还是遇到很有issue中遇到的打开vnc界面一链接就提示需要刷新页面的问题。

**Comment by PaleNeutron** [comment]
是不是客户端版本问题，我也是m1，用7.6.7没有问题（除了docker间歇性抽风）

**Comment by wjfu99** [comment]
> 是不是客户端版本问题，我也是m1，用7.6.7没有问题（除了docker间歇性抽风）

@PaleNeutron 请问你是用arm版本手动构建的吗？可否方便提供一下您使用的是在哪个分支下那个命令构建成功的？因为看之前的issue有提供好几个版本的arm构建指令，试了几个都不太行。

**Comment by PaleNeutron** [comment]
develop分支手动构建的，构建命令就是你issue里的这个

**Comment by wjfu99** [comment]
> develop分支手动构建的，构建命令就是你issue里的这个

又重新编译了一下，已经成功了，谢谢。就是网速超级慢，慢速只有200k😂

**Comment by PaleNeutron** [comment]
VPN一般都这样吧，尤其是用的人多的情况下，能跑就行，要什么自行车🚴‍♀️。😂

**Comment by wjfu99** [comment]
> VPN一般都这样吧，尤其是用的人多的情况下，能跑就行，要什么自行车🚴‍♀️。😂

主要直接用学校提供的easy connect跑满1000mbps是没问题。平时我都直接全局挂着vpn，反正基本没网速上限。现在慢太多了，不打算折腾了，已经打算向深信服屈服了。🥹🥲，不过还是感谢兄弟。

**Comment by Flagami** [comment]
> ```shell
> docker image build \
>     --build-arg EC_URL=https://download.sangfor.com.cn/download/product/sslvpn/SSLVPN%E4%BF%A1%E5%88%9B%E5%AE%A2%E6%88%B7%E7%AB%AF/%E7%BB%9F%E4%BF%A1UOS%20%E6%B5%B7%E6%80%9D%E9%BA%92%E9%BA%9F990%20SSL%20VPN%E5%AE%A2%E6%88%B7%E7%AB%AF.zip \
>     --build-arg EC_DEB_PATH=02-升级包及安装文件/EasyConnect_UOS_arm64-20220302.deb \
>     --tag hagb/docker-easyconnect -f Dockerfile .
> ```

❗️❗️构建错误  Docker version 24.0.6, build ed223bc
RUN /tmp/build-scripts/install-vpn-gui.sh:
0.092 wget: bad address ''
------
Dockerfile:31
--------------------
  29 |     ARG VPN_URL ELECTRON_URL USE_VPN_ELECTRON VPN_DEB_PATH
  30 |     
  31 | >>> RUN /tmp/build-scripts/install-vpn-gui.sh
  32 |     
  33 |     COPY ./docker-root /
--------------------
ERROR: failed to solve: process "/bin/sh -c /tmp/build-scripts/install-vpn-gui.sh" did not complete successfully: exit code: 1

**Comment by Hagb** [comment]
现在可以直接用 dockerhub 上的镜像了，其中已经包含了 arm64 的镜像

**Comment by Hagb** [comment]
即直接 docker pull hagb/docker-easyconnect:7.6.3 或 7.6.7。（另：cli 版本没有 arm64 原生的）

**Comment by AndSonder** [comment]
> 即直接 docker pull hagb/docker-easyconnect:7.6.3 或 7.6.7。（另：cli 版本没有 arm64 原生的）

@Hagb 请问 cli 版本有没有arm64原生的呀，想只用命令行，不想用vnc去登录
