### ISSUE TITLE
先感谢大神的辛苦工作，提一个 bug，关于 7.6.7 的自动登录的问题

### ISSUE THREAD

**Issue by hexid26** [Hagb/docker-easyconnect#21]
您好，我是在 mac 的 bigsur 上使用您制作的镜像。
https://hub.docker.com/r/hagb/docker-easyconnect
tag 分别为 7.6.7 和 vncless-7.6.7 （目前来看应该是最新的，12 月 11 日推送的）
我将本机的一个目录（.config/easyconnect）挂载到容器的/root 目录中，正常运行登录后，会在我的本机目录下生成
easy_connect.json
.config/
.pki/
一个文件和两个目录，其中 easy_connect.json 中只有一行信息，就是设置成 en 文的设置。其它目录文件若干

但是奇怪的是，容器 rm 之后，自动登录无法使用。莫非还有别的目录要挂载。
我的启动命令如下：

```sh
IP=`ifconfig |grep "inet "|grep broadcast|awk '{print $2}'|cut -d/ -f1|head -1`
xhost + ${IP}
docker run -it --rm --device /dev/net/tun --cap-add NET_ADMIN -e EXIT=1 -e DISPLAY=${IP}:0 -e URLWIN=1 -e TYPE=x11 -v ~/.config/easyconnect:/root -p ${SOCK5_PORT}:1080 hagb/docker-easyconnect:vncless-7.6.7
xhost - $IP
```

**Comment by Hagb** [comment]
Hi，我这里没测试过 7.6.7（无测试条件），能否提供以下信息：

- 有没有“自动登录”的复选框？（某些服务端的配置不允许自动登录，见 https://github.com/Hagb/docker-easyconnect/pull/7#issuecomment-668639071 ）
- 若有“自动登录”复选框并已勾选，去掉容器启动参数中的` -e EXIT=1 ` 选项，EasyConnect 客户端成功登录后，重启客户端（容器不关闭）是否能够自动登录？
- 容器 rm 后，再启动容器，服务器、用户名、密码是否有保存下来？

**Comment by hexid26** [comment]
@Hagb 你好，我刚才又测试了一下
我挂载了两个目录，可以自动登录了（测试镜像为 hagb/docker-easyconnect:vncless-7.6.7）
-v ~/.config/easyconnect:/root
-v ~/.config/sangfor:/usr/share/sangfor/EasyConnect/resources/conf

之前我只挂在了第一条，里面的 json 文件应该是只有语言配置项。
第二条挂载直接挂载可能会导致 ec hang住。在不挂载的情况下，启动容器，登录 ec，然后把容器内的`/usr/share/sangfor/EasyConnect/resources/conf`的文件 copy 出来，再挂载就可以实现自动登录了。
感谢您的付出，解决了大麻烦！

**Comment by Hagb** [comment]
感谢反馈！
我改了一下，试试 develop 分支 build 出来的能不能在只挂载 `/root` 时实现自动登陆？
``` shell
git clone https://github.com/Hagb/docker-easyconnect.git --branch=develop
cd docker-easyconnect/
docker image build --build-arg EC_URL=$(cat ec_urls/7.6.7.txt) --tag hagb/docker-easyconnect -f Dockerfile.vncless .
```

**Comment by hexid26** [comment]
@Hagb 您好，刚刚试了一下，只使用了一个挂载
-v ~/.config/easyconnect:/root
初次启动空目录挂载没有问题，执行登录（勾选自动登录）后重启容器，可以自动登录，没有问题的。
我看是直接把 conf 写出来了，可以的👍

**Comment by hexid26** [comment]
7.6.7的镜像可以重推一波了😀

**Comment by Hagb** [comment]
👌

**Comment by shenqihui** [comment]
根据这个mr增加了自动登录 👍

**Comment by moeshin** [comment]
docker compose stop 关闭容器时，sync_ec2volume 没有调用。
