### ISSUE TITLE
Mac m1 arm64版本 图形界面标点乱码 网址识别不了

### ISSUE THREAD

**Issue by oouhei** [Hagb/docker-easyconnect#214]
![IMG_4824](https://user-images.githubusercontent.com/104722055/212447177-e89049f9-df05-4dfa-8c1e-82ec6ab225d5.jpg)
冒号句号不光是无法显示，直接识别不了，进不去下一步，少数时候可以显示。有没有同样情况的，请问如何解决？

**Comment by Hagb** [comment]
用的是什么镜像？（Arm64 推荐使用 https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1256860002 的方式构建原生镜像。）

**Comment by oouhei** [comment]
> 用的是什么镜像？（Arm64 推荐使用 https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1256860002 的方式构建原生镜像。）

就是这里的原生镜像

**Comment by oouhei** [comment]
有办法了，按caps lock键可以切换可识别的标点。

**Comment by Hagb** [comment]
> 有办法了，按caps lock键可以切换可识别的标点。

诶这是什么原理？输入法导致把全角的输入进去了吗？
