### ISSUE TITLE
用户登录成功，但是代理插件出错

### ISSUE THREAD

**Issue by yinhao-art** [Hagb/docker-easyconnect#218]
使用情景：在腾讯云服务器上运行docker-easyconnect,自己在Windows笔记本 谷歌浏览器通过插件访问知网
Linux服务器：ubuntu 20.04
docker-easyconnect版本：
![image](https://user-images.githubusercontent.com/117789267/212801559-1d33f712-8ab5-49bd-bf23-03343541df92.png)
用户登录成功截图
![image](https://user-images.githubusercontent.com/117789267/212801863-a02e21b7-3d5a-4857-abc6-01f247e04e3d.png)
浏览器插件配置(打码的是腾讯云服务器的ip)
![image](https://user-images.githubusercontent.com/117789267/212802238-aa45a820-9899-4a21-9291-27f0891c55a8.png)
报错截图
![image](https://user-images.githubusercontent.com/117789267/212803444-91082da7-4e68-4d85-925d-71ee998e2e10.png)

云服务器端口占用情况
![image](https://user-images.githubusercontent.com/117789267/212802707-ba09af1f-033e-4419-b057-069a6af483ee.png)

**Comment by yinhao-art** [comment]
腾讯云控制台端口已开放
![image](https://user-images.githubusercontent.com/117789267/212803698-bf41ddf1-09da-4b32-9635-b71be08d6ca1.png)

**Comment by yinhao-art** [comment]
解决了重装系统，拉库命令哪里换成0.0.0.0

**Comment by Hagb** [comment]
问题解决了吗？那个 1080 端口转发的参数 `-p 127.0.0.1:1080:1080` 改成 `-p 1080:1080` 才能被本机以外的设备访问。
此外，可以用 `SOCKS_USER` 和 `SOCKS_PASSWD` 环境变量来设置 socks5 的用户、密码（`-e SOCKS_USER=用户名 -e SOCKS_PASSWD=密码`），不然直接开放出来太危险了。

**Comment by yinhao-art** [comment]
解决了 麻烦您了，没有事的 我就和我同学使用



---原始邮件---
发件人: "Hagb (Junyu Guo ***@***.***&gt;
发送时间: 2023年1月17日(周二) 下午5:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Hagb/docker-easyconnect] 用户登录成功，但是代理插件出错 (Issue #218)




 
问题解决了吗？那个 1080 端口转发的参数 -p 127.0.0.1:1080:1080 改成 -p 1080:1080 才能被本机以外的设备访问。
 此外，可以用 SOCKS_USER 和 SOCKS_PASSWD 环境变量来设置 socks5 的用户、密码（-e SOCKS_USER=用户名 -e SOCKS_PASSWD=密码），不然直接开放出来太危险了。

**Comment by Hagb** [comment]
> 没有事的 我就和我同学使用

有些攻击者会扫端口的

**Comment by qllokirin** [comment]
> 

谢谢，找了半天原因在这
我也是用云服务器搭建docker，我用的是vnc版，但是vnc一直链接不上，原来是要把127.0.0.1:5901:5901改成5901:5901
感谢这条issue
