### ISSUE TITLE
修改usage.md文档中关于x11功能的说明

### ISSUE THREAD

**Issue by JHees** [Hagb/docker-easyconnect#223]
希望在usage.md -> 服务说明 -> X11 socket（仅限图形界面版）中关于容器参数的说明中，加入`-e TYPE=x11`参数。可以方便使用者获知使用x11需要添加TYPE参数，非常感谢。

以下是文档位置链接：
[https://github.com/Hagb/docker-easyconnect/blob/master/doc/usage.md#x11-socket%E4%BB%85%E9%99%90%E5%9B%BE%E5%BD%A2%E7%95%8C%E9%9D%A2%E7%89%88](url)

**Comment by Hagb** [comment]
感谢反馈！是否方便提交一个 PR？

**Comment by JHees** [comment]
已经pr了，#224
不太了解其他选项，没有修改文档其他部分，仅在关于x11的说明处加入了`-e TYPE=x11`

感谢作者的支持和贡献
