### ISSUE TITLE
vnc版本可行，cli版本无法登录

### ISSUE THREAD

**Issue by ReCodeLife** [Hagb/docker-easyconnect#227]
试了readme里面的vnc版本，设置代理之后可以正常访问。
使用cli无法访问
命令行输出如下
![image](https://user-images.githubusercontent.com/48639311/215263452-19797b12-1057-40df-ac87-8287333ba716.png)
页面如下
![image](https://user-images.githubusercontent.com/48639311/215263483-24208de2-a502-4b27-98ff-28c9bcb235c2.png)
我认为我的配置应该没有问题，应该如何排查

**Comment by Hagb** [comment]
尝试添加 `-e IPTABLES_LEGACY=1` 参数
