### ISSUE TITLE
群晖nas http代理速度很慢

### ISSUE THREAD

**Issue by ubadly** [Hagb/docker-easyconnect#232]
socks正常，秒开的速度，但我切换为http的之后打开一个页面就得十秒之上，几乎是不可用的状态
创建指令如下
`docker run --name vpn  --device /dev/net/tun --rm --cap-add NET_ADMIN -ti -p 5438:1080 -p 5538:8888 -e EC_VER=7.6.3 -e IPTABLES_LEGACY=1 -e CLI_OPTS="-d 1xx.x.xx.1xx:4433 -u 4xxxxx1 -p HxxxxxJ" hagb/docker-easyconnect:cli`

提这个issue的原因是我通过pac（http:// 远程类型，非file://）针对多个的网址、多个代理分发不同的代理地址，但是貌似ie浏览器已经不支持socks代理，edge，chrome等浏览器可以正常使用，但我们用的网站必须用ie才能使用，所以想要切换为http代理还请开发者能帮忙排查一下原因，两台nas都是这样的问题

**Comment by Hagb** [comment]
试一下使用其他下载工具或者其他浏览器，通过 http 代理能不能正常访问页面？

**Comment by ubadly** [comment]
没找到原因，只能重复的创建和删除容器，直到能正常使用
