### ISSUE TITLE
登入成功一次后再次使用显示 already logged in 并无法使用

### ISSUE THREAD

**Issue by romienjoy** [Hagb/docker-easyconnect#237]
首次登入成功以后，不论是docker start 还是把容器删了然后重新run一个都会变成这个样子。不存在在其它地方登入的问题，更换了EC的版本也不行，传参用 -d 或者像下图这样直接输入都一样，是不是我的使用方法有问题？操作系统是win11，装了给Linux的subsystem，Ubuntu 22.04.2TLS, 用的docker desktop，参考教程是 https://zhuanlan.zhihu.com/p/389894063 这篇
<img width="1110" alt="无标题" src="https://user-images.githubusercontent.com/126132213/220813175-2ded6ec8-7d96-423c-a39a-ff4b3087f1f5.png">
这是命令
`docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -v $HOME/.easyconn:/root/.easyconn -p 127.0.0.1:10180:1080 -e EC_VER=7.6.8 hagb/docker-easyconnect:cli`

**Comment by lns103** [comment]
是不是开了代理？我之前也有这个问题，关闭系统代理，或者在docker desktop设置里打开代理设置并留空即可
![image](https://user-images.githubusercontent.com/49310852/221520750-6bbc8073-975b-4a70-8ec0-0a3bebdc3769.png)

**Comment by romienjoy** [comment]
> 是不是开了代理？我之前也有这个问题，关闭系统代理，或者在docker desktop设置里打开代理设置并留空即可 ![image](https://user-images.githubusercontent.com/49310852/221520750-6bbc8073-975b-4a70-8ec0-0a3bebdc3769.png)

解决了，厉害啊哥
