### ISSUE TITLE
[error] Next authentication is "Token Authentication" 

### ISSUE THREAD

**Issue by berwinjoule** [Hagb/docker-easyconnect#238]
I can you the deb package by our organization, the link as follow:

X86: https://drive.cvte.com/p/DcIV5e0QiRIYoZ8M 
X64: https://drive.cvte.com/p/DS2dVfMQiRIYo58M

please help check this issue, the problem is our organization need 2fa verify

now the log prompt: Next authentication is "Token Authentication"

_Originally posted by @BerwinJoule in https://github.com/Hagb/docker-easyconnect/issues/45#issuecomment-1445875680_

**Comment by Hagb** [comment]
The CLI version supports only password authentication
