### ISSUE TITLE
第二次登录提示版本不匹配，需要删除conf文件夹才可以

### ISSUE THREAD

**Issue by libra146** [Hagb/docker-easyconnect#239]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/17448639/221771604-37c51ef7-2d8d-4385-bd87-d91e3bdb9c73.png">
如图所示，第一次正常登录后，退出vpn再登录，就会卡在检测版本这里，会提示版本不匹配，让下载新版本，第一次登录没有这个问题，版本检测直接就过了

**Comment by libra146** [comment]
我的临时解决方案是：
将dockerfile的最后一行
`CMD ["start.sh"]`
改成
`CMD rm -r /root/conf || true && start.sh`

**Comment by libra146** [comment]
> 我的临时解决方案是： 将dockerfile的最后一行 `CMD ["start.sh"]` 改成 `CMD rm -r /root/conf || true && start.sh`

貌似更新完这个方案也不可用了，除了删除容器重建暂时还没其他解决方案😂

**Comment by minghaoL1** [comment]
我用 develop 分支构建的 M1 mac 版本也遇到这个问题，目前的 hack 是按照某个 issue（我忘了 = =）上写的降低`.ecdata/conf/pkg_version.xml` 文件里的版本号，例如 7.6.7.6 => 7.6.7.1，目前没遇到问题 : )

**Comment by Hagb** [comment]
8a1dd3b5644716dd9f664b23fa1bab2e4fcb3555 加入了一个环境变量选项 `DISABLE_PKG_VERSION_XML`，设为非空时会将 `pkg_version.xml` 指向 `/dev/null`，阻止 EasyConnect 进行版本检查。
可以试一下从最新的源码构建或者使用 dockerhub 上的最新镜像，带上 `-e DISABLE_PKG_VERSION_XML=1` 看看问题还会不会出现。
