### ISSUE TITLE
与服务器版本不匹配

### ISSUE THREAD

**Issue by wulaladamowang** [Hagb/docker-easyconnect#24]
我用docker安装之后，运行example 依旧是显示与服务器版本不匹配，宿主机器为ubuntu18

**Comment by Hagb** [comment]
这里的 EasyConnect 镜像有 `7.6.3` 和 `7.6.7` 两个版本，是否两个版本的都不兼容？

**Comment by wulaladamowang** [comment]
是的，和在ubuntu18的商店中下载的easyconnect 的效果一样，显示不匹配

**Comment by Hagb** [comment]
能否提供一下你那边的服务端给出的 Linux 版 EasyConnect 下载地址

**Comment by wulaladamowang** [comment]
http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb
谢谢

**Comment by wulaladamowang** [comment]
(node:20590) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
在程序启动时候会显示，此时还没有输入地址

**Comment by Hagb** [comment]
这是 `7.6.3` 版的地址。
如果使用 `7.6.3` 的容器依然显示不匹配，尝试把登陆消息持久化的目录删掉（如 `README.md` 的例子里的`$HOME/.ecdata`，可能需要使用 root 权限来删）或者不挂载这个目录（如 `README.md` 的例子里去掉参数 `-v $HOME/.ecdata:/root`），然后再开一次 `7.6.3` 容器，看看能不能登上去

**Comment by wulaladamowang** [comment]
谢谢 问题解决了 ，我使用了7.6.7版本的删掉参数 -v $HOME/.ecdata:/root，可以使用了
7.6.3版本的删掉参数也不能使用。

**Comment by Hagb** [comment]
那好奇怪啊…… 最后居然是 7.6.7……
问题解决了我给 close 了哈
