### ISSUE TITLE
能不能单独写一个文档说明一下对苹果M1芯片的支持情况以及用法,issues里很杂乱

### ISSUE THREAD

**Issue by ceylog** [Hagb/docker-easyconnect#250]

**Comment by ErickWei** [comment]
哈哈哈  确实有点哈，我都忘记自己是怎么使用起来的。
我的清况：只能使用 VNC 版本，CLI 版本会自动断联。（这个可能与公司的 VPN 配置有关）

这是我之前做的笔记，供参考。
自行编译编译Arm版镜像

- 下载Docker配置 [[Link](https://github.com/Hagb/docker-easyconnect/tree/non-amd64)](https://github.com/Hagb/docker-easyconnect/tree/non-amd64)
- 进入到配置文件夹，执行以下命令

```docker

docker image build -f Dockerfile.fake-hwaddr -t fake-hwaddr .
docker image build --tag hagb/docker-easyconnect -f Dockerfile.cli .
```

- 执行以下命令创建EasyConnect容器

```docker
docker run --device /dev/net/tun --name=EasyConnect_CLI_ARM --cap-add NET_ADMIN -ti -p 1080:1080 -p 8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d serverIP -u username -p password" hagb/docker-easyconnect
```

**Comment by ceylog** [comment]
> 哈哈哈 确实有点哈，我都忘记自己是怎么使用起来的。 我的清况：只能使用 VNC 版本，CLI 版本会自动断联。（这个可能与公司的 VPN 配置有关）
> 
> 这是我之前做的笔记，供参考。 自行编译编译Arm版镜像
> 
> * 下载Docker配置 [[Link](https://github.com/Hagb/docker-easyconnect/tree/non-amd64)](https://github.com/Hagb/docker-easyconnect/tree/non-amd64)
> * 进入到配置文件夹，执行以下命令
> 
> ```
> 
> docker image build -f Dockerfile.fake-hwaddr -t fake-hwaddr .
> docker image build --tag hagb/docker-easyconnect -f Dockerfile.cli .
> ```
> 
> * 执行以下命令创建EasyConnect容器
> 
> ```
> docker run --device /dev/net/tun --name=EasyConnect_CLI_ARM --cap-add NET_ADMIN -ti -p 1080:1080 -p 8888:8888 -e EC_VER=7.6.3 -e CLI_OPTS="-d serverIP -u username -p password" hagb/docker-easyconnect
> ```

哈哈 感谢大佬 我试试

**Comment by Hagb** [comment]
现在 M1 等 arm64 的设备可以直接使用 `hagb/docker-easyconnect:dev-7.6.7` 等 tag 中带 `dev` 字样的镜像，详见 https://hub.docker.com/r/hagb/docker-easyconnect/tags 。
现在计划不久之后将 `develop` 分支合并到 `master` 分支，届时可以直接使用不带 `dev` 的镜像。

**Comment by xieqing0428** [comment]
> 现在 M1 等 arm64 的设备可以直接使用 `hagb/docker-easyconnect:dev-7.6.7` 等 tag 中带 `dev` 字样的镜像，详见 https://hub.docker.com/r/hagb/docker-easyconnect/tags 。
> 现在计划不久之后将 `develop` 分支合并到 `master` 分支，届时可以直接使用不带 `dev` 的镜像。

好像不支持纯命令行？

**Comment by Hagb** [comment]
> 好像不支持纯命令行？

是的。纯命令行只有 amd64 版本。

**Comment by jiangliuhong** [comment]
> 现在 M1 等 arm64 的设备可以直接使用 `hagb/docker-easyconnect:dev-7.6.7` 等 tag 中带 `dev` 字样的镜像，详见 https://hub.docker.com/r/hagb/docker-easyconnect/tags 。 现在计划不久之后将 `develop` 分支合并到 `master` 分支，届时可以直接使用不带 `dev` 的镜像。

m2芯片，使用dev-7.6.3导入证书失败，我执行`docker cp ./xxxx.p12 96f7f14e99ab:/usr/share/sangfor/EasyConnect/resources/user_cert/xxxx.p12`命令，将证书拷贝到`/usr/share/sangfor/EasyConnect/resources/user_cert/`目录后，再进行导入成功了。
