### ISSUE TITLE
请问可以上传一个 7.6.7 VNC Arm64 版本的容器到 docker hub 吗?

### ISSUE THREAD

**Issue by ErickWei** [Hagb/docker-easyconnect#258]
如题,请问可以上传一个 7.6.7 VNC Arm64 版本的容器到 docker hub 吗?

**Comment by LarryBug** [comment]
你是不是也是M1/2芯片遇到提醒？
![image](https://github.com/Hagb/docker-easyconnect/assets/4980453/ce401f2e-889c-479c-b7e0-22aac05cdc5d)

**Comment by Hagb** [comment]
现在 dockerhub 上已经 push 了 `develop` 分支的 arm64 镜像。可以试一下重新 `docker pull hagb/docker-easyconnect:dev-7.6.7` 后使用 `hagb/docker-easyconnect:dev-7.6.7`（应该要加 `-e DISABLE_PKG_VERSION_XML=1` 参数）

**Comment by ErickWei** [comment]
> 现在 docker hub 上已经 push 了 `develop` 分支的 arm64 镜像。可以试一下重新 `docker pull hagb/docker-easyconnect:dev-7.6.7` 后使用 `hagb/docker-easyconnect:dev-7.6.7`（应该要加 `-e DISABLE_PKG_VERSION_XML=1` 参数）

感谢大神,可以用了,确实要加`-e DISABLE_PKG_VERSION_XML=1` ,否则会检查并要求更新

**Comment by ErickWei** [comment]
> 你是不是也是M1/2芯片遇到提醒？ ![image](https://user-images.githubusercontent.com/4980453/247876661-ce401f2e-889c-479c-b7e0-22aac05cdc5d.png)

我使用新上传的 dev-7.6.7 版本可以这个正常使用了.
另外你可以不使用 vnc-viewer ,直接 `command+k`,然后输入`vnc://127.0.0.1:5901`就可以连接,又可以少安装一个软件
