### ISSUE TITLE
客户端只支持特定的网页通过代理连接

### ISSUE THREAD

**Issue by kettly1260** [Hagb/docker-easyconnect#259]
学校用的easyconnect，但是只有特定的链接才能通过客户端进行连接，其他的必须要使用web-vpn认证或者必须通过弹出的资源列表点进去才可以正常访问。请问有没有办法解决这个问题

**Comment by Einskai** [comment]
可以尝试使用 https://github.com/Hagb/docker-easyconnect/issues/229 这个方法把资源列表代理出来？我自己测试过是可以这样搞的，不知道能不能解决你的问题。

**Comment by Hagb** [comment]
可以尝试 https://github.com/Hagb/docker-easyconnect/issues/226 介绍的方式

**Comment by Hagb** [comment]
我好像读明白了，是不是对特定链接外的资源也进行代理的意思？这个是在服务端那边就规定好的，并且服务端也会做验证，用简单的方式无解。如果想把 web-vpn 也变成代理的形式，可以尝试 https://github.com/CoolSpring8/rwppa .
