### ISSUE TITLE
VNC访问始终版本不匹配

### ISSUE THREAD

**Issue by LarryBug** [Hagb/docker-easyconnect#261]
docker拉了vpn后，启动后，用VNC访问始终说版本不匹配；
点更新也不行，求助！！！
这个版本肯定是对的
![image](https://github.com/Hagb/docker-easyconnect/assets/4980453/54bf9e2b-313f-48d3-a64d-b87e783149bd)

**Comment by Hagb** [comment]
试试去掉启动时的 `-e $HOME/.ecdata:/root` 参数（如果有）?

**Comment by Hagb** [comment]
> 试试去掉启动时的 `-e $HOME/.ecdata:/root` 参数（如果有）?

如果依然不行，尝试加上 `-e DISABLE_PKG_VERSION_XML=1` 参数来绕过版本检测

**Comment by LarryBug** [comment]
> 

加上绕过这个是启动了，但是VNC几个端口都访问不到呢……
![image](https://github.com/Hagb/docker-easyconnect/assets/4980453/674df52b-5e99-46a9-b80f-248ea571bb2e)

**Comment by Hagb** [comment]
> > 
> 
> 加上绕过这个是启动了，但是VNC几个端口都访问不到呢…… ![image](https://user-images.githubusercontent.com/4980453/248164040-674df52b-5e99-46a9-b80f-248ea571bb2e.png)

是登录之后才访问不到吗? 另外刚刚重新生成并上传了镜像，可以 `docker pull hagb/docker-easyconnect:7.6.7` 来重新 pull，之后按理来说就不需要绕过版本检测了。

**Comment by LarryBug** [comment]
sudo docker run -d --restart=always --restart=on-failure --device /dev/net/tun --cap-add NET_ADMIN -ti -e PASSWORD=xxxx -e NODANTED=1 -e DISABLE_PKG_VERSION_XML=1 -v $HOME/.ecdata:/root -p 0.0.0.0:6901:5901 -p 0.0.0.0:9080:1080 -p 0.0.0.0:9999:8888 hagb/docker-easyconnect:7.6.7
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
144c88014457f147d446f3a242c6a1c923ede47bf44a4e80886fb5ed6a3c1492
--
我是arm m2芯片的，我docker启动了，但是用VNC连不上这个VPN
0.0.0.0:5901或者6901或者其他端口都试过了
![image](https://github.com/Hagb/docker-easyconnect/assets/4980453/d36f5a9e-370a-4117-b609-4187b0ef807f)

**Comment by Hagb** [comment]
最后那个问题应该是由于架构不同而引起的。
现在 docker hub 上已经 push 了 develop 分支的 arm64 镜像。可以试一下重新 `docker pull hagb/docker-easyconnect:dev-7.6.7` 后使用 `hagb/docker-easyconnect:dev-7.6.7`（应该要加 `-e DISABLE_PKG_VERSION_XML=1` 参数）

**Comment by LarryBug** [comment]
感谢大佬，用arm的编译了可以了
