### ISSUE TITLE
求解答

### ISSUE THREAD

**Issue by Einskai** [Hagb/docker-easyconnect#262]
start-sangfor.sh的第12行是会监听ECAgent.log的变化，但出现"\\[Register\\]cms client connect failed"的时候会执行sslservice.sh
理论上只要执行一次第12行就可以一直监听下去了。为什么第12行需要放在while循环里面，每一次代理挂了之后都会重新执行第12行呢？
现在“每一次代理挂了之后都会重新执行第12行”会造成长时间运行之后出现“Too many open files”（ https://github.com/Hagb/docker-easyconnect/issues/253 ）的问题，因为每一次重启代理都会加一个监听，但是旧的监听却还保持着，造成重启多了之后会超出文件打开限制。
这里能不能把第12行挪到循环外面，或者加一个参数标记一下，不重复执行第12行呀？（我对shell不是很熟，不确定这样搞会不会有什么不良后果）

**Comment by Hagb** [comment]
这是针对 7.6.3 版本的一个 workaround，参照了 https://blog.51cto.com/u_13226459/2476193 。
7.6.3 每次登录时都需要这个 workaround 处理，7.6.7 应该是没有这个问题了。

**Comment by Einskai** [comment]
感谢回复，up主加油。
