### ISSUE TITLE
无法使用Socks5访问容器

### ISSUE THREAD

**Issue by Entropie0** [Hagb/docker-easyconnect#267]
首先感谢大佬制作封印容器
我是在WSL2下的docker中尝试封印无果，固使用Vmware

我的环境是vmware debian-12.0.0
docker是
`user@debian:~$ docker -v
Docker version 24.0.2, build cb74dfc
`

docker ps 如下
`user@debian:~$ docker ps
CONTAINER ID   IMAGE                         COMMAND                   CREATED          STATUS          PORTS                     NAMES
06a93645fcb8   hagb/docker-easyconnect:cli   "/bin/sh -c '_EC_CLI…"   13 minutes ago   Up 13 minutes   0.0.0.0:23333->1080/tcp   Econ
`

docker run如下
`docker run --name Econ --privileged --cap-add NET_ADMIN -ti -v $HOME/.easyconn:/root/.easyconn -p 0.0.0.0:23333:1080 -e IPTABLES_LEGACY=1 -e EC_VER=7.6.8 hagb/docker-easyconnect:cli`

启动后报
`WARNING: logging deactivated (can't log to stdout when daemonized)
user "ZYGS020" auto login successfully
`

在尝试使用过7.6.3、7.6.7、7.6.8后均无法在容器中启动tun0
容器内busybox ifconfig 如下
`root@06a93645fcb8:/usr/local/bin# busybox ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02
          inet addr:172.17.0.2  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:316 errors:0 dropped:0 overruns:0 frame:0
          TX packets:286 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:73601 (71.8 KiB)  TX bytes:24364 (23.7 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:517 errors:0 dropped:0 overruns:0 frame:0
          TX packets:517 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:117920 (115.1 KiB)  TX bytes:117920 (115.1 KiB)

`
容器内ip route如下
`root@06a93645fcb8:/usr/local/bin# ip route
default via 172.17.0.1 dev eth0
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2
`

容器内iptables-save如下
`root@06a93645fcb8:/usr/local/bin# iptables-save
# Generated by iptables-save v1.8.2 on Sun Jul  2 13:53:26 2023
*filter
:INPUT ACCEPT [152:7600]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1391:172856]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -p tcp -j ACCEPT
-A INPUT -i eth0 -p tcp -j ACCEPT
-A INPUT -p tcp -j DROP
COMMIT
# Completed on Sun Jul  2 13:53:26 2023
# Generated by iptables-save v1.8.2 on Sun Jul  2 13:53:26 2023
*nat
:PREROUTING ACCEPT [2:133]
:INPUT ACCEPT [1:60]
:OUTPUT ACCEPT [75:3750]
:POSTROUTING ACCEPT [75:3750]
:SANGFOR_OUTPUT - [0:0]
-A OUTPUT -j SANGFOR_OUTPUT
-A POSTROUTING -o tun0 -j MASQUERADE
-A SANGFOR_OUTPUT -d 8.8.9.137/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.137/32 -p tcp -m tcp --dport 8081 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.46/32 -p tcp -m tcp --dport 8085 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.48/32 -p tcp -m tcp --dport 8084 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.137/32 -p tcp -m tcp --dport 3000 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.137/32 -p tcp -m tcp --dport 12333 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.137/32 -p tcp -m tcp --dport 9002 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.137/32 -p tcp -m tcp --dport 9879 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.172/32 -p tcp -m tcp --dport 9002 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.172/32 -p tcp -m tcp --dport 9703 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.137/32 -p tcp -m tcp --dport 3355 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.137/32 -p tcp -m tcp --dport 18081 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.60/32 -p tcp -m tcp --dport 8103 -j DNAT --to-destination 127.0.0.1:4440
-A SANGFOR_OUTPUT -d 8.8.9.60/32 -p tcp -m tcp --dport 8107 -j DNAT --to-destination 127.0.0.1:4440
COMMIT
# Completed on Sun Jul  2 13:53:26 2023
`

在vmware debian中curl测试得到
`user@debian:~$ curl -v -x 'socks5://localhost:23333' 8.8.9.137
*   Trying 127.0.0.1:23333...
* Connected to localhost (127.0.0.1) port 23333 (#0)
* Recv failure: 连接被对方重设
* SOCKS4: Failed receiving initial SOCKS5 response: Failure when receiving data from the peer
* Closing connection 0
curl: (97) Recv failure: 连接被对方重设
`

打算在容器中使用detect-tun.sh手动起tun，报错如下
`Jul  2 14:13:17 (1688307197.411243) danted[5835]: alert: mother[1/1]: shutting down
Jul  2 14:13:22 (1688307202.418767) danted[5854]: warning: int_ifname2sockaddr(): interface "tun0" has no usable IP-addresses configured
Jul  2 14:13:22 (1688307202.419416) danted[5854]: error: /etc/danted.conf: problem on line 2 near token "tun0": could not resolve hostname "tun0": Temporary failure in name resolution.  Please see the Dante manual for more information
Jul  2 14:13:22 (1688307202.419444) danted[5854]: alert: mother[1/1]: shutting down
Jul  2 14:13:27 (1688307207.426632) danted[5874]: warning: int_ifname2sockaddr(): interface "tun0" has no usable IP-addresses configured
Jul  2 14:13:27 (1688307207.427272) danted[5874]: error: /etc/danted.conf: problem on line 2 near token "tun0": could not resolve hostname "tun0": Temporary failure in name resolution.  Please see the Dante manual for more information
Jul  2 14:13:27 (1688307207.427303) danted[5874]: alert: mother[1/1]: shutting down
`

vmware debian中是启动了tun模块的
`user@debian:~$ lsmod | grep tun
tun                    61440  0
`

不知什么原因容器中的tun模块无法启动
劳烦大佬帮忙瞧瞧

**Comment by Hagb** [comment]
emmm看起来 easyconnect 连防火墙都设好了，但是却没有开起 tun。这个恐怕得到 easyconnect 的日志 `/usr/share/sangfor/EasyConnect/resources/logs` 里面去找原因，尤其是 `svpnservice.log` 的。
也有一种可能是，你连接的 easyconnect 服务器不提供三层 vpn，所有的资源都是协议层（如 http）的（`SANGFOR_OUTPUT` 里面那一堆就是做这件事情的）。
可以试试使用 `dev` 分支的镜像（可以直接 docker pull，tag 为 `dev-版本号` 如 `dev-7.6.7`、`dev-cli`，近期会合并进 master 分支），socks5 不再需要 vpn 把 tun0 开起来才能启动。
