### ISSUE TITLE
mac m2 arm64vnc版本无法登陆提示升级客户端 amd64vnc版本可以登陆但socks5无法连接

### ISSUE THREAD

**Issue by Cheney1209** [Hagb/docker-easyconnect#271]
7.6.3版本均不能登录
arm64使用的dev-7.6.7，提示升级客户端
amd64版本7.6.7登陆和短信验证顺利，但不能转发socks5

docker exec kind_johnson busybox ifconfig

eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02  
          inet addr:172.17.0.2  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:65535  Metric:1
          RX packets:4579 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3481 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:3887920 (3.7 MiB)  TX bytes:3859322 (3.6 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:5772 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5772 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:964458 (941.8 KiB)  TX bytes:964458 (941.8 KiB)

docker run --cap-add NET_ADMIN --device /dev/net/tun -e CHECK_SYSTEM_ONLY=1 hagb/docker-easyconnect:7.6.7

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Cannot talk to rtnetlink: Operation not supported
Cannot talk to rtnetlink: Operation not supported
Cannot send dump request: Operation not supported
Can't find available method to automatically set route for opening ports (refer to https://github.com/Hagb/docker-easyconnect/tree/master/doc/route.md)
Cannot talk to rtnetlink: Operation not supported

**Comment by Hagb** [comment]
> arm64使用的dev-7.6.7，提示升级客户端

arm64 版本启动时加上 `DISABLE_PKG_VERSION_XML=1` 参数。

> amd64版本7.6.7登陆和短信验证顺利，但不能转发socks5

amd64 版本在 m1、m2 上不可用
