### ISSUE TITLE
容器关闭重启后 ,easy connect 就显示版本不一致 . 

### ISSUE THREAD

**Issue by czetao** [Hagb/docker-easyconnect#272]
<img width="768" alt="image" src="https://github.com/Hagb/docker-easyconnect/assets/43066081/c8d95add-50ea-4d83-87e6-9a365af308b1">

**Comment by Hagb** [comment]
应该是 easyconnect 更新了。刚才已经重新构建并 push 了，可以 `docker pull hagb/docker-easyconnect:7.6.7` 后再试试

**Comment by czetao** [comment]
机器是mac m2 的, 我翻之前是说的用带dev的镜像,这个更新有到dev的吗

**Comment by Hagb** [comment]
> 机器是mac m2 的, 我翻之前是说的用带dev的镜像,这个更新有到dev的吗

哦继续用 `dev` 的镜像，运行的时候加上 `-e DISABLE_PKG_VERSION_XML=1` 参数

**Comment by czetao** [comment]
我多用用看看还会不会,目前看来可以了
