### ISSUE TITLE
vnc中connected 但容器log中没有登陆成功字样 且不能正常使用

### ISSUE THREAD

**Issue by R3habDroid** [Hagb/docker-easyconnect#276]

**Comment by R3habDroid** [comment]
Error: ipv4: FIB table does not exist.
Flush terminated
Error: Missing goto target for action goto.
WARNING: logging deactivated (can't log to stdout when daemonized)
ln: failed to create symbolic link '/usr/share/sangfor/EasyConnect/resources/conf/ConfModuleMap.xml': File exists
ln: failed to create symbolic link '/usr/share/sangfor/EasyConnect/resources/conf/LogConf.xml': File exists
ln: failed to create symbolic link '/usr/share/sangfor/EasyConnect/resources/conf/Module.xml': File exists
ln: failed to create symbolic link '/usr/share/sangfor/EasyConnect/resources/conf/SurpportBrowser.xml': File exists
ln: failed to create symbolic link '/usr/share/sangfor/EasyConnect/resources/conf/Version.xml': File exists
ln: failed to create symbolic link '/usr/share/sangfor/EasyConnect/resources/conf/easy_connect.json': File exists
ln: failed to create symbolic link '/usr/share/sangfor/EasyConnect/resources/conf/need_hook_dns_server.ini': File exists
ln: failed to create symbolic link '/usr/share/sangfor/EasyConnect/resources/conf/pkg_version.xml': File exists
/
Cleaning stale pidfile '/root/.vnc/780ddb82e52a:1.pid'!
Cleaning stale X11 lock '/tmp/.X11-unix/X1'!

New Xtigervnc server '780ddb82e52a:1 (root)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /tmp/tigervnc.2GECDU/passwd 780ddb82e52a:1 to connect to the VNC server.

(node:145) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:145) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:145) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by R3habDroid** [comment]
容器内ping：
root@780ddb82e52a:/# curl https://200.10.1.101
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by R3habDroid** [comment]
root@780ddb82e52a:/# ip route
default via 172.17.0.1 dev eth0
2.0.1.0/24 dev tun0 proto kernel scope link src 2.0.1.224
100.60.1.31 dev tun0 scope link
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.9
200.10.1.97 dev tun0 scope link
200.10.1.117 dev tun0 scope link
200.10.1.138 dev tun0 scope link

**Comment by R3habDroid** [comment]
run命令：

docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -e PASSWORD=xxxx -v /usr/bin/curl:/usr/bin/curl  -v $HOME/.ecdata:/root -p 5902:5902 -p 1082:1082 -p 8889:8889 hagb/docker-easyconnect:7.6.3

**Comment by Hagb** [comment]
我看你 close 了，是可以了吗？

**Comment by R3habDroid** [comment]
> 

不好意思 是我自己操作的问题

**Comment by dfowl** [comment]
@R3habDroid 您好，我在docker run的时候也遇到了同样的报错，想知道是如何解决的
<img width="838" alt="docker-error" src="https://github.com/Hagb/docker-easyconnect/assets/56057865/a40ed52d-2ed9-4fa4-9155-803a8147524d">

**Comment by R3habDroid** [comment]
@dfowl  下个tigervnc试试，我之前是用的realvnc 可以vnc7.6.3，但不能vnc7.6.7，换了tigervnc就可以了。

**Comment by Hagb** [comment]
> @Hagb @R3habDroid 您好，我在docker run的时候也遇到了同样的报错，想知道是如何解决的

从输出来看都是正常的输出…… 使用上正常吗？

**Comment by dfowl** [comment]
该问题已经解决，因为iptables需要root权限才行，docker run要在root下执行
