### ISSUE TITLE
Web登陆问题

### ISSUE THREAD

**Issue by Lee8150951** [Hagb/docker-easyconnect#291]
配置web登陆后访问https://127.0.0.1:54530报错：
`{"type":"","result":"-100","message":"","debug":"http query is empty"}`
请问这个问题是什么原因，应该如何解决呢？

**Comment by Hagb** [comment]
这是正常现象，这个地址只是给 web 登录页面提供相关 api 的，而不是登录页面本身。登录页面可以通过访问你连接的服务器来打开。

**Comment by Lee8150951** [comment]
> 这是正常现象，这个地址只是给 web 登录页面提供相关 api 的，而不是登录页面本身。登录页面可以通过访问你连接的服务器来打开。

非常感谢您的回答！您的意思是我在宿主机访问web登陆页面就能调用docker中的easy connect吗？

**Comment by Hagb** [comment]
> > 这是正常现象，这个地址只是给 web 登录页面提供相关 api 的，而不是登录页面本身。登录页面可以通过访问你连接的服务器来打开。
> 
> 非常感谢您的回答！您的意思是我在宿主机访问web登陆页面就能调用docker中的easy connect吗？

是的

**Comment by Lee8150951** [comment]
> > > 这是正常现象，这个地址只是给 web 登录页面提供相关 api 的，而不是登录页面本身。登录页面可以通过访问你连接的服务器来打开。
> > 
> > 
> > 非常感谢您的回答！您的意思是我在宿主机访问web登陆页面就能调用docker中的easy connect吗？
> 
> 是的

好的，但是我发现一个问题就是我们的web登陆页面会检测本地是否安装有easy connect，否则会弹到ec的下载页面。另外就算我扫码成功，似乎也没有什么反应😫

**Comment by Hagb** [comment]
> > > > 这是正常现象，这个地址只是给 web 登录页面提供相关 api 的，而不是登录页面本身。登录页面可以通过访问你连接的服务器来打开。
> > > 
> > > 
> > > 非常感谢您的回答！您的意思是我在宿主机访问web登陆页面就能调用docker中的easy connect吗？
> > 
> > 
> > 是的
> 
> 好的，但是我发现一个问题就是我们的web登陆页面会检测本地是否安装有easy connect，否则会弹到ec的下载页面。另外就算我扫码成功，似乎也没有什么反应😫

检测本地是否安装 easyconnect 应该就是通过上面那个地址。你在浏览器能够正常访问那个地址不？（即，得到 ` {"type":"","result":"-100","message":"","debug":"http query is empty"}`）
打开服务器的登录页面的时候可以在浏览器 f12 工具的网络那儿看看它有没有访问 `127.0.0.1:54530`

**Comment by Lee8150951** [comment]
> > > > > 这是正常现象，这个地址只是给 web 登录页面提供相关 api 的，而不是登录页面本身。登录页面可以通过访问你连接的服务器来打开。
> > > > 
> > > > 
> > > > 非常感谢您的回答！您的意思是我在宿主机访问web登陆页面就能调用docker中的easy connect吗？
> > > 
> > > 
> > > 是的
> > 
> > 
> > 好的，但是我发现一个问题就是我们的web登陆页面会检测本地是否安装有easy connect，否则会弹到ec的下载页面。另外就算我扫码成功，似乎也没有什么反应😫
> 
> 检测本地是否安装 easyconnect 应该就是通过上面那个地址。你在浏览器能够正常访问那个地址不？（即，得到 ` {"type":"","result":"-100","message":"","debug":"http query is empty"}`） 打开服务器的登录页面的时候可以在浏览器 f12 工具的网络那儿看看它有没有访问 `127.0.0.1:54530`

是的，它访问了该地址，并且我在safari中能够正常访问这个地址，得到`{"type":"","result":"-100","message":"","debug":"http query is empty"}`信息

**Comment by Hagb** [comment]
它访问了之后有没有正常完成请求？宿主机看起来是 mac 吧，不知道需不需要把浏览器的 mac 地址伪装成 Linux 的（只是我的一种猜测）

**Comment by Lee8150951** [comment]
> 它访问了之后有没有正常完成请求？宿主机看起来是 mac 吧，不知道需不需要把浏览器的 mac 地址伪装成 Linux 的（只是我的一种猜测）

是的，没有正常完成请求，宿主机是Mac

**Comment by Hagb** [comment]
> 是的，没有正常完成请求，宿主机是Mac

这里没有正常完成请求有更多的细节吗？
比如说有没有拿到 http 状态码和 response body

**Comment by Lee8150951** [comment]
> 

没有拿到状态码和response body，但是我在浏览器中直接访问请求的地址的时候是请求成功的，且能够得到某些信息

**Comment by Hagb** [comment]
> > 
> 
> 没有拿到状态码和response body，但是我在浏览器中直接访问请求的地址的时候是请求成功的，且能够得到某些信息

有给出原因吗？

**Comment by Lee8150951** [comment]
> > > 
> > 
> > 
> > 没有拿到状态码和response body，但是我在浏览器中直接访问请求的地址的时候是请求成功的，且能够得到某些信息
> 
> 请求失败有给出原因吗？

我尝试在控制台fetch了一下这个地址，显示了错误：`net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH`，另外如果使用接口工具对这个地址发起请求也是类似的错误：`write EPROTO 5268290856:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:705:`，没理解错的话应该是证书那一块出了问题

**Comment by Lee8150951** [comment]
谢谢作者，我已经成功解决了问题。问题的根结在于ssl，需要将浏览器安全等级降至最低才能实现

**Comment by wzgrx** [comment]
> 谢谢作者，我已经成功解决了问题。问题的根结在于ssl，需要将浏览器安全等级降至最低才能实现

这个怎么调整，求大佬详细说一下，非常感谢

**Comment by zvictorliu** [comment]
> 谢谢作者，我已经成功解决了问题。问题的根结在于ssl，需要将浏览器安全等级降至最低才能实现

同问
