### ISSUE TITLE
是否可以增加带用户名密码认证的sock5链接选项？

### ISSUE THREAD

**Issue by wenxiao2012** [Hagb/docker-easyconnect#292]
是否可以增加带用户名密码认证的sock5链接选项？

**Comment by Hagb** [comment]
可使用 `SOCKS_USER` 和 `SOCKS_PASSWD` 环境变量，参看 [`doc/usage.md`](https://github.com/Hagb/docker-easyconnect/blob/master/doc/usage.md)

**Comment by wenxiao2012** [comment]
感谢提醒，已经按照说明测试成功！

**Comment by jiucenglou** [comment]
@Hagb 请问能增加带用户名和密码认证的https链接选项么
