### ISSUE TITLE
版本升级问题

### ISSUE THREAD

**Issue by Cheukfung** [Hagb/docker-easyconnect#3]
请问如何升级easyconnect的版本呢

**Comment by Hagb** [comment]
Hi. 刚刚对 Dockerfile 进行了更新，可以参照新的文档 https://github.com/Hagb/docker-easyconnect#pull-or-build 来部署更新版本 EasyConnect 的 image。
如果正常运行`7.6.3`以外的版本，欢迎反馈，我会将该版本加入到[已经过测试的版本](https://github.com/Hagb/docker-easyconnect#%E5%B7%B2%E7%BB%8F%E8%BF%87%E6%B5%8B%E8%AF%95%E7%9A%84%E7%89%88%E6%9C%AC)。
如果有任何问题欢迎继续回复。

**Comment by Cheukfung** [comment]
非常感谢，已经可以了！感谢你的付出！
