### ISSUE TITLE
Mac 上运行约 20min 后容器自行关闭

### ISSUE THREAD

**Issue by xiaoyang-chen** [Hagb/docker-easyconnect#30]
RT, mac 10.15.7，docker 19.03.13
运行后一直报这个日志警告，
![image](https://user-images.githubusercontent.com/61339960/107874577-8279df00-6ef5-11eb-9a92-c7600a5cdebf.png)
每次运行大概20min左右，容器就会自行关闭，日志也只有(node:39) DeprecationWarning: Calling an asynchronous function without callback is deprecated.这一条日志，

两个问题：
1. 运行大概20min左右后，容器自行关闭，日志仅有(node:39) DeprecationWarning: Calling an asynchronous function without callback is deprecated. 无其他日志
2. 一直打这条日志(node:39) DeprecationWarning: Calling an asynchronous function without callback is deprecated. 调用异步函数时缺少回调函数，这个日志感觉已经成为无效日志了

**Comment by xiaoyang-chen** [comment]
@Hagb

**Comment by xiaoyang-chen** [comment]
用该代码仓库构建的镜像

**Comment by Hagb** [comment]
别的 mac 用户也有反映这个情况，但是别的平台上好像没有出现这种现象……（我没有 mac 也无法测试）
这个报错是正常的，其他正常使用的平台上也这句报错有，应该是和这个容器自行关闭关系不大

**Comment by Hagb** [comment]
尝试下新的纯命令行 `cli` 版能不能正常使用？

**Comment by xiaoyang-chen** [comment]
> 尝试下新的纯命令行 `cli` 版能不能正常使用？

@Hagb 显示“Rand Code is enabled, we don't support it in terminal version!”
公司用的vpn需要输入验证码，cli版本应该是不支持，所以提示了这个，
我在最新的master分支打包了vncless版本，这个问题依然存在

**Comment by Hagb** [comment]
这个问题我没什么头绪…… 能否试下 vnc 版本能不能正常使用？

**Comment by xiaoyang-chen** [comment]
> 这个问题我没什么头绪…… 能否试下 vnc 版本能不能正常使用？

@Hagb vnc版本的现象和vncless版本的现象一样，都是运行约 20min 后容器自行关闭

**Comment by Hagb** [comment]
现在还存在这种现象吗？

**Comment by xiaoyang-chen** [comment]
换公司了，easyconnect都不用了，之前的账号前公司回收了

**Comment by xiaoyang-chen** [comment]
close issue?

**Comment by Hagb** [comment]
没有再收到复现的报告了。因此先 close 了
