### ISSUE TITLE
[讨论&建议]构建一个纯CLI登录的docker image

### ISSUE THREAD

**Issue by shmilee** [Hagb/docker-easyconnect#36]
接 https://github.com/Hagb/docker-easyconnect/issues/35#issuecomment-791847999
在[7.6.8(CLI)](https://github.com/shmilee/scripts/releases/download/v0.0.1/easyconn_7.6.8.2-ubuntu_amd64.deb)的基础上，我们应该可以为`7.6.3`,`7.6.7`分别构建一个纯CLI登录的image。

* 仍基于 debian:buster-slim
* 最好不要 dpkg 安装7.6.8(CLI)，因为里面有许多mac上的文件。
  只保留 `/usr/share/sangfor/EasyConnect/resources/bin`(甚至是只留`ECAgent` 和 `easyconn` )
* 同样`7.6.3`,`7.6.7` 安装包内`/usr/share/sangfor/EasyConnect/resources/`的文件， 按 https://github.com/Hagb/docker-easyconnect/issues/35#issuecomment-791926286 保留需要的
* ldd所用命令， 排查 apt-get 安装的软件，同时删除不需要的依赖库
* 简化启动脚本，只保留CLI相关的内容

不确定的：
如果说7.6.8(CLI)和7.6.3的 CSClient   EasyMonitor  svpnservice能通用，那三个版本和在一块，体积也可能不会很大。
三版本构建一个image也不错。

**Comment by Hagb** [comment]
目前初步做了一个镜像在 [`cli` 分支](https://github.com/Hagb/docker-easyconnect/tree/cli)，仅在 `7.6.3` 上测试过。构建纯命令行容器时对原本的图形界面前端做了裁剪（[`Dockerfile.cli`](https://github.com/Hagb/docker-easyconnect/blob/cli/Dockerfile.cli)），但直接使用 `7.6.8` 的包时多余的部分未作裁剪。

>  如果说7.6.8(CLI)和7.6.3的 CSClient EasyMonitor svpnservice能通用，那三个版本和在一块，体积也可能不会很大。

目前我不太确定版本是由什么决定的（是那几个可执行文件还是其他配置文件，还是两者均是？）
`EasyMonitor`  或许可以剔除，现在我唯一观察到它的行为是确保 `ECAgent` 存活。

**Comment by shmilee** [comment]
可能就下面这几个文件吧
```
[$] strings ECAgent |grep -i version |grep resources
/usr/share/sangfor/EasyConnect/resources/conf/Version.xml
!inputUrl.empty(/usr/share/sangfor/EasyConnect/resources/conf/pkg_version.xml
```

**Comment by shmilee** [comment]
除了conf, 其他文件都选用的`7.6.8`的，https://github.com/shmilee/scripts/commit/eecc77eedf05bcdc3a5ff796647e4514e1e8701b
我这边测试三个版本登录都正常的。7.6.3登录学校。另两个登录天河。
镜像包含三个版本与只包含7.6.8相比，也就多了10k而已。

其他:
* [EasyMonitor可以删](https://github.com/shmilee/scripts/blob/eecc77eedf05bcdc3a5ff796647e4514e1e8701b/easyconnect-in-docker/only-cli/get_cli_resources.sh#L49)
* 下载50多M的7.6.3, 7.6.8，[只提取5k的conf用](https://github.com/shmilee/scripts/blob/eecc77eedf05bcdc3a5ff796647e4514e1e8701b/easyconnect-in-docker/only-cli/get_cli_resources.sh#L64), 实在是亏/(ㄒoㄒ)/~~

**Comment by Hagb** [comment]
那太好了！强！
> 我这边测试三个版本登录都正常的。7.6.3登录学校。另两个登录天河。

你的 7.6.3 如果登录后不关掉 ECAgent 的话，能不能保持登录？（我这儿它发一会儿心跳包就会导致 vpn 断开）

**Comment by Hagb** [comment]
> 下载50多M的7.6.3, 7.6.8，[只提取5k的conf用](https://github.com/shmilee/scripts/blob/eecc77eedf05bcdc3a5ff796647e4514e1e8701b/easyconnect-in-docker/only-cli/get_cli_resources.sh#L64), 实在是亏/(ㄒoㄒ)/~~

或许可以直接分发它的 conf

**Comment by shmilee** [comment]
> 那太好了！强！
> 
> > 我这边测试三个版本登录都正常的。7.6.3登录学校。另两个登录天河。
> 
> 你的 7.6.3 如果登录后不关掉 ECAgent 的话，能不能保持登录？（我这儿它发一会儿心跳包就会导致 vpn 断开）

我这边测试一个多小时，没发现问题。
测试顺便还发现之前漏了一点：因为用了7.6.8的 ECAgent ，之前7.6.3登录的问题就不用处理了。 https://github.com/shmilee/scripts/commit/23d7a4835e2d3a9f511f7cd668b6cd051358aa42

**Comment by Hagb** [comment]
> > 那太好了！强！
> > > 我这边测试三个版本登录都正常的。7.6.3登录学校。另两个登录天河。
> > 
> > 
> > 你的 7.6.3 如果登录后不关掉 ECAgent 的话，能不能保持登录？（我这儿它发一会儿心跳包就会导致 vpn 断开）
> 
> 我这边测试一个多小时，没发现问题。
> 测试顺便还发现之前漏了一点：因为用了7.6.8的 ECAgent ，之前7.6.3登录的问题就不用处理了。 [shmilee/scripts@23d7a48](https://github.com/shmilee/scripts/commit/23d7a4835e2d3a9f511f7cd668b6cd051358aa42)

刚刚试着把 `bin` 里面的文件全套换成 7.6.8 的之后，确实没心跳包的问题了。之前出问题大概是因为混用不同版本的可执行文件。
