### ISSUE TITLE
如何少创建容器

### ISSUE THREAD

**Issue by skychan** [Hagb/docker-easyconnect#4]
每次 docker run 之后，就会创建新的容器，所以尝试使用了 -d 参数，但是在结束掉容器之后，使用 docker start 并不能继续使用，需要怎么解决呢?

**Comment by skychan** [comment]
> 每次 docker run 之后，就会创建新的容器，所以尝试使用了 -d 参数，但是在结束掉容器之后，使用 docker start 并不能继续使用，需要怎么解决呢?

说实话，我找到问题的根源并自己解决了。就讲一下思路，觉得能改进就好了。

其实主要的问题是 vnc 开启后，在 /tmp 下面会多一些锁，而使用 `docker stop` 后，这些锁还存在，而阻止运行的关键是两个：

1. /tmp/.X1-lock
2. /tmp/.X11-unix

因此，只要把他们删除即可。为了方便，我修改了容器中 `/usr/local/bin/start.sh` 文件，将`rm -rf /tmp/` 添加在最前面，然后就成功了。

具体来说，首次运行：

```
docker run -d --name ec --device /dev/net/tun --cap-add NET_ADMIN -ti -e PASSWORD=xxxx -v $HOME/.ecdata:/root -p 127.0.0.1:5901:5901 -p 127.0.0.1:1080:1080 hagb/docker-easyconnect
```

对，我用了 `-d` 并将其命名为 "ec"

然后用完：

```
docker stop ec
```

之后又想用，直接：

```
docker start ec
```

即可。

希望作者能将 `docker-easyconnect/docker-root/usr/local/bin/start.sh` 进行修改，这样就方便了。

**Comment by Hagb** [comment]
感谢 @skychan ！
更改了 `docker-root/usr/local/bin/start.sh`。

**Comment by Cheng-2v** [comment]
我是在Windows 10上dockers 跑的 EasyConnect 7.6.7版本，我在启动container的时候，多加了选项 --detach --name EasyConnect，此时我可以docker stop EasyConnect，但是不可以docker start EasyConnect, 这是怎么回事啊？
