### ISSUE TITLE
掉线自动重新登陆的次数

### ISSUE THREAD

**Issue by cecial** [Hagb/docker-easyconnect#50]
现在有个应用场景是docker里面运行EC，掉线后会自动重新登陆。
如果我在另外一台PC上登陆相同的账号，会把docker里面的踢掉，然后docker自动登陆把PC上登陆的踢掉。
能不能设一个变量，限制docker自动登陆的次数，比如3次。这样我PC登陆3次就可以暂时把docker停掉了。
谢谢。

**Comment by Hagb** [comment]
试试 `develop` 分支最新的 commit（https://github.com/Hagb/docker-easyconnect/commit/696f9210f29789d9940d274a9dbf25f40ac99740 ）行不行？

**Comment by cecial** [comment]
> 试试 [`develop`](https://github.com/Hagb/docker-easyconnect/tree/develop) 分支最新的 commit（[696f921](https://github.com/Hagb/docker-easyconnect/commit/696f9210f29789d9940d274a9dbf25f40ac99740) ）行不行？
> 加上环境变量参数 `-e MAX_RETRY=最大重连次数`

我是在群晖里面docker跑的，最新的分支怎么试？

**Comment by Hagb** [comment]
刚刚更新了镜像，尝试使用最新镜像？
带上环境变量参数 `MAX_RETRY=最大重连次数`（如 `MAX_RETRY=2`）

**Comment by cecial** [comment]
> 刚刚更新了镜像，尝试使用最新镜像？
> 带上环境变量参数 `MAX_RETRY=最大重连次数`（如 `MAX_RETRY=2`）

忘记说了，我用cli模式跑的，vnc模式会提示版本和服务器不一致，需要更新。cli没有问题。
我看docker hub 上cli的没有更新？其他都有更新了

**Comment by Hagb** [comment]
> 我看docker hub 上cli的没有更新？其他都有更新了

emmm 确实，之前忘了给 cli 分支推送…… 现在好了。

**Comment by cecial** [comment]
> > 我看docker hub 上cli的没有更新？其他都有更新了
> 
> emmm 确实，之前忘了给 cli 分支推送…… 现在好了。

好滴，过会试试

**Comment by cecial** [comment]
> 刚刚更新了镜像，尝试使用最新镜像？
> 带上环境变量参数 `MAX_RETRY=最大重连次数`（如 `MAX_RETRY=2`）

已经可以了，到达次数后容器停止。谢谢啦~
