### ISSUE TITLE
解决容器网络的连通性问题，为内网其他机器提供SOCKS5代理

### ISSUE THREAD

**Issue by lrbnew** [Hagb/docker-easyconnect#54]
使用了CLI命令行镜像。拟运行为SOCKS代理服务器供内网其他机器使用

遇到问题类似于以下issue：
https://github.com/Hagb/docker-easyconnect/issues/20

可以联通127.0.0.1:1080，即 nc -w3 -4 -v localhost 1080完全正常，能为宿主机提供127.0.0.1:1080 socks5 代理服务。
但是不能在局域网其他机器连接1080代理端口，甚至不能在本机联通 localIP:1080

**排查过程**
查看容器内路由表，发现缺少了连接局域网的路由。
添加路由后排除了故障（172地址为Docker0网卡地址）
`ip route add 192.168.0.0/16 via 172.17.0.1 table local`

**推荐的解决方案**
为一劳永逸，把路由修改脚本添加到镜像中，参考以下步骤。

修改Dockerfile.cli文件，最后一行修改为
`CMD /local-route.sh && _EC_CLI=1 start.sh`

之后重建镜像。

启动前可以根据自身网络情况设计local-route.sh脚本，并通过volume方式挂载到/local-route.sh

比如我的脚本内容类似于：
`ip route add 192.168.0.0/16 via 172.17.0.1 table local`

启动命令类似于

`docker run --rm  --device /dev/net/tun --cap-add NET_ADMIN -ti \
-v $PWD/.easyconn:/root/.easyconn \
-v $PWD/local-route.sh:/local-route.sh \
-v $PWD/logs:/usr/share/sangfor/EasyConnect/resources/logs/ \
-p 1080:1080  -e EC_VER=7.6.3 -e EXIT=1  --name  easyvpn\
vpn/docker-easyconnect`

现在可以在局域网内使用socks5代理服务走EasyConnect的VPN线路了。

**Comment by lrbnew** [comment]
这几行只是添加了路由策略标记，并没有实际的路由条目。
如果ＥＣ自动生成的路由搞乱了系统，那么只能手动修改路由补救。

**Comment by Hagb** [comment]
> 这几行只是添加了路由策略标记，并没有实际的路由条目。
> 如果ＥＣ自动生成的路由搞乱了系统，那么只能手动修改路由补救。

这里的想法是把初始路由表备份到表 `2`，然后 `ip rule add fwmark 1 table 2` 使带标记的连接走表 `2`。EC 应该只会修改表 `main`。

**Comment by lrbnew** [comment]
这个要看EC的实现了，它不是开源的我们只能推测。
从我最近在win10和Ubuntu安装ＥＣ的体验看，都把路由表搞坏了。不得已才到ＧｉｔＨｕｂ找镜像

**Comment by Hagb** [comment]
现在 https://github.com/Hagb/docker-easyconnect/commit/f124a1eedc964bac375767dbbf00ccb1a6cc64dd 用了一个类似的思路，不过将应用初始路由表的范围限定在从本机的 `1080`（socks）和 `5901`（vnc）端口发出的连接
