### ISSUE TITLE
群辉NAS上无法使用tun设备

### ISSUE THREAD

**Issue by Ryanznoco** [Hagb/docker-easyconnect#59]
![企业微信截图_20210619024456](https://user-images.githubusercontent.com/17562936/122604336-61deb300-d0a8-11eb-990a-085850743b88.png)

**Comment by Hagb** [comment]
这是因为这里用了 iptables-legacy，这个报错是正常现象（我还是改下代码让它不出现为好）。
除此之外能正常使用不？

**Comment by Ryanznoco** [comment]
> 这是因为这里用了 iptables-legacy，这个报错是正常现象（我还是改下代码让它不出现为好）。
> 除此之外能正常使用不？

日志显示登录成功但socket代理连不上

**Comment by Hagb** [comment]
在容器内执行
``` shell
ip route del 172.17.0.1 # 这句可能会报错
ip route add 172.17.0.1 dev eth0
```
之后能不能连上？

**Comment by Ryanznoco** [comment]
> 在容器内执行
> 
> ```shell
> ip route del 172.17.0.1 # 这句可能会报错
> ip route add 172.17.0.1 dev eth0
> ```
> 
> 之后能不能连上？

![image](https://user-images.githubusercontent.com/17562936/122645420-1c27f600-d14d-11eb-83ed-3513b1c8d35c.png)
还是不行

**Comment by Ryanznoco** [comment]
我开始没有/dev/net/tun这个设备，是通过mknod /dev/net/tun c 10 200命令添加的设备，现在日志显示登录成功，但telnet端口都不通，报telnet: Unable to connect to remote host: Connection refused

**Comment by Hagb** [comment]
> 我开始没有/dev/net/tun这个设备，是通过mknod /dev/net/tun c 10 200命令添加的设备，现在日志显示登录成功，但telnet端口都不通，报telnet: Unable to connect to remote host: Connection refused

运行容器的命令是什么？

**Comment by Ryanznoco** [comment]
> > 我开始没有/dev/net/tun这个设备，是通过mknod /dev/net/tun c 10 200命令添加的设备，现在日志显示登录成功，但telnet端口都不通，报telnet: Unable to connect to remote host: Connection refused
> 
> 运行容器的方式是什么？有什么参数？

 docker run --name hagb-docker-easyconnect1 --device /dev/net/tun --cap-add NET_ADMIN -ti -v /volume2/docker/easyconnect/.easyconn:/root/.easyconn -p 127.0.0.1:10807:1080 -e EC_VER=7.6.8 -e IPTABLES_LEGACY=1 -e CLI_OPTS="-d ** -u ** -p **" hagb/docker-easyconnect:cli

**Comment by Hagb** [comment]
> 我开始没有/dev/net/tun这个设备，是通过mknod /dev/net/tun c 10 200命令添加的设备

这里说的没有 /dev/net/tun，是指宿主机里吗？

> 现在日志显示登录成功，但telnet端口都不通，报telnet: Unable to connect to remote host: Connection refused

连接后在容器里运行`busybox ifconfig`的输出里面有没有`tun0`？如果有，那`ip route get telnet服务器地址`得到的输出里面有没有`dev tun0`？

telnet 是在何处运行的？

**Comment by Ryanznoco** [comment]
> > 我开始没有/dev/net/tun这个设备，是通过mknod /dev/net/tun c 10 200命令添加的设备
> 
> 这里说的没有 /dev/net/tun，是指宿主机里吗？
> 
> > 现在日志显示登录成功，但telnet端口都不通，报telnet: Unable to connect to remote host: Connection refused
> 
> 连接后在容器里运行`busybox ifconfig`的输出里面有没有`tun0`？如果有，那`ip route get telnet服务器地址`得到的输出里面有没有`dev tun0`？
> 
> telnet 是在何处运行的？

![image](https://user-images.githubusercontent.com/17562936/122646897-197ccf00-d154-11eb-86d3-74350a034ef1.png)

**Comment by Hagb** [comment]
> 我开始没有/dev/net/tun这个设备，是通过mknod /dev/net/tun c 10 200命令添加的设备

宿主机的环境是？宿主机中执行 `sudo ip tuntap del dev tun0 mode tun` 报错吗？

**Comment by Ryanznoco** [comment]
> > 我开始没有/dev/net/tun这个设备，是通过mknod /dev/net/tun c 10 200命令添加的设备
> 
> 宿主机的环境是？宿主机中执行 `sudo ip tuntap del dev tun0 mode tun` 报错吗？

![image](https://user-images.githubusercontent.com/17562936/122650438-919fc080-d165-11eb-8113-ed14b3f2c164.png)
宿主机是群辉NAS

**Comment by Hagb** [comment]
试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？
如果可以执行，再运行容器能否成功？（此外，需要在什么地方连接容器的 socks？）

**Comment by Ryanznoco** [comment]
> 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？
> 如果可以执行，再运行容器能否成功？（此外，需要在什么地方连接容器的 socks？）

这两个命令都可以执行成功，执行了之后运行容器一样telnet端口不通，我现在是在windows主机上测试，最终目的是要在NAS的其它容器里连接VPN

**Comment by Hagb** [comment]
> > 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？
> > 如果可以执行，再运行容器能否成功？（此外，需要在什么地方连接容器的 socks？）
> 
> 这两个命令都可以执行成功，执行了之后运行容器一样telnet端口不通，我现在是在windows主机上测试，最终目的是要在NAS的其它容器里连接VPN

如果运行容器的参数中端口设置依然是 `-p 127.0.0.1:10807:1080`，那么无法在 NAS 本机以外的其他地方访问容器的 socks，可以把 127.0.0.1 改为 0.0.0.0 或 NAS 在局域网中的 ip。
此外，因为容器中路由表的问题，没有在容器中给局域网设置路由表时在其它主机上也可能会连不上容器的 socks。

---

容器中 `busybox ifconfig` 的结果此时有没有出现 tun0？

**Comment by Ryanznoco** [comment]
> > > 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？
> > > 如果可以执行，再运行容器能否成功？（此外，需要在什么地方连接容器的 socks？）
> > 
> > 
> > 这两个命令都可以执行成功，执行了之后运行容器一样telnet端口不通，我现在是在windows主机上测试，最终目的是要在NAS的其它容器里连接VPN
> 
> 如果运行容器的参数中端口设置依然是 `-p 127.0.0.1:10807:1080`，那么无法在 NAS 本机以外的其他地方访问容器的 socks，可以把 127.0.0.1 改为 0.0.0.0 或 NAS 在局域网中的 ip。
> 此外，因为容器中路由表的问题，没有在容器中给局域网设置路由表时在其它主机上也可能会连不上容器的 socks。
> 
> 容器中 `busybox ifconfig` 的结果此时有没有出现 tun0？

有了，现在我在NAS主机上测试，报错如下
![image](https://user-images.githubusercontent.com/17562936/122651973-bd737400-d16e-11eb-86ca-95cabac5d79a.png)
容器日志如下
![image](https://user-images.githubusercontent.com/17562936/122651992-de3bc980-d16e-11eb-9f6e-d48be08b2e09.png)

**Comment by Ryanznoco** [comment]
> > > > 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？
> > > > 如果可以执行，再运行容器能否成功？（此外，需要在什么地方连接容器的 socks？）
> > > 
> > > 
> > > 这两个命令都可以执行成功，执行了之后运行容器一样telnet端口不通，我现在是在windows主机上测试，最终目的是要在NAS的其它容器里连接VPN
> > 
> > 
> > 如果运行容器的参数中端口设置依然是 `-p 127.0.0.1:10807:1080`，那么无法在 NAS 本机以外的其他地方访问容器的 socks，可以把 127.0.0.1 改为 0.0.0.0 或 NAS 在局域网中的 ip。
> > 此外，因为容器中路由表的问题，没有在容器中给局域网设置路由表时在其它主机上也可能会连不上容器的 socks。
> > 容器中 `busybox ifconfig` 的结果此时有没有出现 tun0？
> 
> 有了，现在我在NAS主机上测试，报错如下
> ![image](https://user-images.githubusercontent.com/17562936/122651973-bd737400-d16e-11eb-86ca-95cabac5d79a.png)
> 容器日志如下
> ![image](https://user-images.githubusercontent.com/17562936/122651992-de3bc980-d16e-11eb-9f6e-d48be08b2e09.png)

google了一下这个问题好像是容器时间不对造成的，我看了容器里的时间确实不对，请问怎么修改容器时区呢

**Comment by Ryanznoco** [comment]
> > > > > 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？
> > > > > 如果可以执行，再运行容器能否成功？（此外，需要在什么地方连接容器的 socks？）
> > > > 
> > > > 
> > > > 这两个命令都可以执行成功，执行了之后运行容器一样telnet端口不通，我现在是在windows主机上测试，最终目的是要在NAS的其它容器里连接VPN
> > > 
> > > 
> > > 如果运行容器的参数中端口设置依然是 `-p 127.0.0.1:10807:1080`，那么无法在 NAS 本机以外的其他地方访问容器的 socks，可以把 127.0.0.1 改为 0.0.0.0 或 NAS 在局域网中的 ip。
> > > 此外，因为容器中路由表的问题，没有在容器中给局域网设置路由表时在其它主机上也可能会连不上容器的 socks。
> > > 容器中 `busybox ifconfig` 的结果此时有没有出现 tun0？
> > 
> > 
> > 有了，现在我在NAS主机上测试，报错如下
> > ![image](https://user-images.githubusercontent.com/17562936/122651973-bd737400-d16e-11eb-86ca-95cabac5d79a.png)
> > 容器日志如下
> > ![image](https://user-images.githubusercontent.com/17562936/122651992-de3bc980-d16e-11eb-9f6e-d48be08b2e09.png)
> 
> google了一下这个问题好像是容器时间不对造成的，我看了容器里的时间确实不对，请问怎么修改容器时区呢

我临时修改了一下容器的时区，重启之后确实可以了，这个时区问题是否需要更新一下镜像呢？
感谢作者一路帮忙解决，点赞

**Comment by Ryanznoco** [comment]
> > > > > 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？
> > > > > 如果可以执行，再运行容器能否成功？（此外，需要在什么地方连接容器的 socks？）
> > > > 
> > > > 
> > > > 这两个命令都可以执行成功，执行了之后运行容器一样telnet端口不通，我现在是在windows主机上测试，最终目的是要在NAS的其它容器里连接VPN
> > > 
> > > 
> > > 如果运行容器的参数中端口设置依然是 `-p 127.0.0.1:10807:1080`，那么无法在 NAS 本机以外的其他地方访问容器的 socks，可以把 127.0.0.1 改为 0.0.0.0 或 NAS 在局域网中的 ip。
> > > 此外，因为容器中路由表的问题，没有在容器中给局域网设置路由表时在其它主机上也可能会连不上容器的 socks。
> > > 容器中 `busybox ifconfig` 的结果此时有没有出现 tun0？
> > 
> > 
> > 有了，现在我在NAS主机上测试，报错如下
> > ![image](https://user-images.githubusercontent.com/17562936/122651973-bd737400-d16e-11eb-86ca-95cabac5d79a.png)
> > 容器日志如下
> > ![image](https://user-images.githubusercontent.com/17562936/122651992-de3bc980-d16e-11eb-9f6e-d48be08b2e09.png)
> 
> google了一下这个问题好像是容器时间不对造成的，我看了容器里的时间确实不对，请问怎么修改容器时区呢

我临时修改了一下容器的时区，重启之后确实可以了，这个时区问题是否需要更新一下镜像呢？
感谢作者一路帮忙解决，点赞

**Comment by Ryanznoco** [comment]
这个容器比windows客户端稳定，windows连接多了EC会掉线，容器500+sock5代理500个连接也没有遇到掉线

**Comment by Hagb** [comment]
> > > 有了，现在我在NAS主机上测试，报错如下
> > > ![image](https://user-images.githubusercontent.com/17562936/122651973-bd737400-d16e-11eb-86ca-95cabac5d79a.png)
> > > 容器日志如下
> > > ![image](https://user-images.githubusercontent.com/17562936/122651992-de3bc980-d16e-11eb-9f6e-d48be08b2e09.png)
> > 
> > 
> > google了一下这个问题好像是容器时间不对造成的，我看了容器里的时间确实不对，请问怎么修改容器时区呢
> 
> 我临时修改了一下容器的时区，重启之后确实可以了，这个时区问题是否需要更新一下镜像呢？
> 感谢作者一路帮忙解决，点赞

好奇怪… 不知道里面是什么原理…（我查了查原帖是 tor 的例子吗？tor 本身确实是需要时间同步。而且即使有关系，按理来说只要时间戳同步，时区应该是没影响的。）

方便的话可以将时区设置去掉再试试吗？vpn 连接成功后等多几秒再连 socks。

**Comment by Ryanznoco** [comment]
> > > > 有了，现在我在NAS主机上测试，报错如下
> > > > ![image](https://user-images.githubusercontent.com/17562936/122651973-bd737400-d16e-11eb-86ca-95cabac5d79a.png)
> > > > 容器日志如下
> > > > ![image](https://user-images.githubusercontent.com/17562936/122651992-de3bc980-d16e-11eb-9f6e-d48be08b2e09.png)
> > > 
> > > 
> > > google了一下这个问题好像是容器时间不对造成的，我看了容器里的时间确实不对，请问怎么修改容器时区呢
> > 
> > 
> > 我临时修改了一下容器的时区，重启之后确实可以了，这个时区问题是否需要更新一下镜像呢？
> > 感谢作者一路帮忙解决，点赞
> 
> 好奇怪… 不知道里面是什么原理…（我查了查，原帖是 tor 的例子吗？tor 本身确实需要时间同步。而且即使有关系，按理来说只要时间戳同步，时区应该是没影响的。）
> 
> 方便的话可以将时区设置去掉再试试吗？vpn 连接成功后等多几秒再连 socks。

我是看的[这个帖子](https://stackoverflow.com/questions/11246770/tor-curl-cant-complete-socks5-connection-to-0-0-0-00)，稍等我试下

**Comment by Ryanznoco** [comment]
> > > > 有了，现在我在NAS主机上测试，报错如下
> > > > ![image](https://user-images.githubusercontent.com/17562936/122651973-bd737400-d16e-11eb-86ca-95cabac5d79a.png)
> > > > 容器日志如下
> > > > ![image](https://user-images.githubusercontent.com/17562936/122651992-de3bc980-d16e-11eb-9f6e-d48be08b2e09.png)
> > > 
> > > 
> > > google了一下这个问题好像是容器时间不对造成的，我看了容器里的时间确实不对，请问怎么修改容器时区呢
> > 
> > 
> > 我临时修改了一下容器的时区，重启之后确实可以了，这个时区问题是否需要更新一下镜像呢？
> > 感谢作者一路帮忙解决，点赞
> 
> 好奇怪… 不知道里面是什么原理…（我查了查，原帖是 tor 的例子吗？tor 本身确实需要时间同步。而且即使有关系，按理来说只要时间戳同步，时区应该是没影响的。）
> 
> 方便的话可以将时区设置去掉再试试吗？vpn 连接成功后等多几秒再连 socks。

确实不改时区也可以了，之前不知道是什么情况

**Comment by Hagb** [comment]
解决方法已写入 [doc/faq.md](https://github.com/Hagb/docker-easyconnect/blob/master/doc/faq.md)

**Comment by Bistutu** [comment]
> 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？ 如果可以执行，再运行容器能否成功？（此外，连接容器 socks 的客户端是否在 NAS 上？）

我用的是阿里云的服务器，也是遇到一样的问题，到这一步并没有出现tun0，而且尝试了issue中的其他方式都没能成功
<img width="682" alt="image" src="https://user-images.githubusercontent.com/91378285/192177449-1770a5dd-f964-4de6-aa54-14a622a39a5d.png">

**Comment by Hagb** [comment]
> > 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？ 如果可以执行，再运行容器能否成功？（此外，连接容器 socks 的客户端是否在 NAS 上？）
> 
> 我用的是阿里云的服务器，也是遇到一样的问题，到这一步并没有出现tun0，而且尝试了issue中的其他方式都没能成功 <img alt="image" width="682" src="https://user-images.githubusercontent.com/91378285/192177449-1770a5dd-f964-4de6-aa54-14a622a39a5d.png">

@Bistutu 看看 `find /dev -name "tun*"`

**Comment by Bistutu** [comment]
> > > 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？ 如果可以执行，再运行容器能否成功？（此外，连接容器 socks 的客户端是否在 NAS 上？）
> > 
> > 
> > 我用的是阿里云的服务器，也是遇到一样的问题，到这一步并没有出现tun0，而且尝试了issue中的其他方式都没能成功 <img alt="image" width="682" src="https://user-images.githubusercontent.com/91378285/192177449-1770a5dd-f964-4de6-aa54-14a622a39a5d.png">
> 
> @Bistutu 看看 `find /dev -name "tun*"`

我分别在宿主机以及docker里面执行，结果是这个。
![image](https://user-images.githubusercontent.com/91378285/192217572-e7116df7-ccdb-45b7-a37b-5cbaa335f6db.png)
<img width="845" alt="image" src="https://user-images.githubusercontent.com/91378285/192217857-d0731b4a-7b01-4cea-b68f-58443fffefe2.png">

**Comment by Hagb** [comment]
> > 试试 `sudo modprobe tun` 或 `sudo insmod /lib/modules/tun.ko` 能不能执行？ 如果可以执行，再运行容器能否成功？（此外，连接容器 socks 的客户端是否在 NAS 上？）
> 
> 我用的是阿里云的服务器，也是遇到一样的问题，到这一步并没有出现tun0，而且尝试了issue中的其他方式都没能成功 <img alt="image" width="682" src="https://user-images.githubusercontent.com/91378285/192177449-1770a5dd-f964-4de6-aa54-14a622a39a5d.png">

@Bistutu tun0 是在 EasyConnect 登录之后才会出现。登录 EasyConnect 的时候（以及之后）现象如何？
