### ISSUE TITLE
请问在macOS下如何转发所有（或部分）流量到socks5代理中？

### ISSUE THREAD

**Issue by fengyuentau** [Hagb/docker-easyconnect#60]
我的运行指令是：
```shell
$ docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -v $HOME/.easyconn:/root/.easyconn -p 127.0.0.1:1083:1080 -e EC_VER=7.6.3 hagb/docker-easyconnect:cli
```

端口挂在1083是因为已经有其他软件占用了1080端口。通过1083端口，我可以成功ssh over proxy到内网的机器，但是配置System Preferences -> Network -> advanced -> Proxies -> SOCKS proxy为127.0.0.1:1083无法在浏览器上访问内网。而通过swtichyomega我可以单独配置浏览器访问内网web服务。

除了浏览器访问内网web服务之外，我还有用microsoft remote desktop远程桌面至内网机器的需求。请问大家有什么好办法配置吗？

**Comment by Hagb** [comment]
试试 [proxychains](https://github.com/rofl0r/proxychains-ng)？

**Comment by fengyuentau** [comment]
> 试试 [proxychains](https://github.com/rofl0r/proxychains-ng)？

尝试了proxychains，但是没成功。conf里面就写了`socks5  127.0.0.1 1083`。

**Comment by fengyuentau** [comment]
我用ssh端口转发的方式成功代理到远程桌面了，可以参考https://serverfault.com/a/214847。

**Comment by sylph520** [comment]
> 我的运行指令是：
> 
> ```shell
> $ docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -v $HOME/.easyconn:/root/.easyconn -p 127.0.0.1:1083:1080 -e EC_VER=7.6.3 hagb/docker-easyconnect:cli
> ```
> 
> 端口挂在1083是因为已经有其他软件占用了1080端口。通过1083端口，我可以成功ssh over proxy到内网的机器，但是配置System Preferences -> Network -> advanced -> Proxies -> SOCKS proxy为127.0.0.1:1083无法在浏览器上访问内网。而通过swtichyomega我可以单独配置浏览器访问内网web服务。
> 
> 除了浏览器访问内网web服务之外，我还有用microsoft remote desktop远程桌面至内网机器的需求。请问大家有什么好办法配置吗？

你好，请问你怎么通过socks5 代理 ssh到内网机器啊？谢谢。网页用switchyomega没问题，ssh不太会设置。local环境是windows，remote是linux。谢谢！

**Comment by fengyuentau** [comment]
@sylph520 我在mac下用下面的命令，但是windows的话可能要通过wsl来使用。

```
ssh -L 1083:127.0.0.1:1083 username@ip # 创建ssh隧道，不要关闭
ssh -o ProxyCommand="nc -X 5 -x 127.0.0.1:1083 %h %p" # 

```

**Comment by sylph520** [comment]
好的，谢谢，linux下的nc好像没有-X选项，不过去掉-X 可以用你的命令连接到内网有独立ip（只是不让外网连接🙃）的机器上了👍
