### ISSUE TITLE
VPN地址报错

### ISSUE THREAD

**Issue by fanties** [Hagb/docker-easyconnect#61]
命令行版本运行后，输入VPN地址就报错：
auth failed, please check if the vpn address is valid and reachable!
login failed!
svpn stop!
auto login is disabled

昨天我用这个运行时没问题的，今天就不行了，我重新换个环境也不不行。
我在windows下载客户端，填写地址是可以登录成功的。
不过windows客户端输入vpn地址之后，今天好像还加载了一会儿SSL相关的什么东西，是不是新的镜像还需要下载什么组件？

**Comment by Hagb** [comment]
运行容器的环境中能不能访问 vpn 的地址？（比如 `curl 地址 -v -k` 有没有输出 vpn 页面的 html）

**Comment by fanties** [comment]
> 运行容器的环境中能不能访问 vpn 的地址？（比如 `curl 地址 -v -k` 有没有输出 vpn 页面的 html）

通过curl vpn地址是可以打印html页面的

**Comment by Hagb** [comment]
这个问题以前还没有见过哩… 试试 gui 版行不行？

**Comment by fanties** [comment]
GUI版本没问题，可以登录连接网络。就是服务器GUI太占用内存了

**Comment by fanties** [comment]
重装后不知道为啥又没问题了，cli版本

**Comment by geosmart** [comment]
ubuntu上docker cli 7.6.7
同样的问题

**Comment by bentleyxia** [comment]
> 重装后不知道为啥又没问题了，cli版本

同样的问题，请问重装了什么？

**Comment by DerZc** [comment]
求问，一般学校的vpn地址都是给的https://vpn.**u.edu.cn ，这个怎么查对应的ip地址啊

**Comment by Hagb** [comment]
> 求问，一般学校的vpn地址都是给的https://vpn.**u.edu.cn ，这个怎么查对应的ip地址啊

如果学校用的是深信服的 vpn，一般就是直接用这个地址就可以了

**Comment by DerZc** [comment]
> > 求问，一般学校的vpn地址都是给的https://vpn.**u.edu.cn ，这个怎么查对应的ip地址啊
> 
> @DerZc 如果学校用的是深信服的 vpn，一般就是直接用这个地址就可以了

感谢回复，请问如果只在docker里面使用easyconnect的话应该下载哪个版本的easyconnect呢，我在地址里面填了[https://vpn.**u.edu.cn](https://vpn.%2A%2Au.edu.cn/)然后就直接登录失败了

**Comment by Hagb** [comment]
> > > 求问，一般学校的vpn地址都是给的https://vpn.**u.edu.cn ，这个怎么查对应的ip地址啊
> > 
> > 
> > @DerZc 如果学校用的是深信服的 vpn，一般就是直接用这个地址就可以了
> 
> 感谢回复，请问如果只在docker里面使用easyconnect的话应该下载哪个版本的easyconnect呢，我在地址里面填了[https://vpn.**u.edu.cn](https://vpn.%2A%2Au.edu.cn/)然后就直接登录失败了

@DerZc 先在浏览器中访问这个地址，看看是不是 EasyConnect 的 vpn。如果它确实是的话，会跳转到下载页面给出客户端下载地址，然后可以从下载地址可以判断版本（地址无版本号的是 `7.6.3`）

**Comment by DerZc** [comment]
> > > > 求问，一般学校的vpn地址都是给的https://vpn.**u.edu.cn ，这个怎么查对应的ip地址啊
> > > 
> > > 
> > > @DerZc 如果学校用的是深信服的 vpn，一般就是直接用这个地址就可以了
> > 
> > 
> > 感谢回复，请问如果只在docker里面使用easyconnect的话应该下载哪个版本的easyconnect呢，我在地址里面填了[https://vpn.**u.edu.cn](https://vpn.%2A%2Au.edu.cn/)然后就直接登录失败了
> 
> @DerZc 先在浏览器中访问这个地址，看看是不是 EasyConnect 的 vpn。如果它确实是的话，会跳转到下载页面给出客户端下载链接，然后可以从下载地址可以判断版本（地址无版本号的是 `7.6.3`）

求问您在docker里面是怎么解决这个问题的啊
`System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down`

**Comment by Hagb** [comment]
> 求问您在docker里面是怎么解决这个问题的啊 `System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down`

@DerZc  我没有遇到这个问题。你是在 wsl2 里面吗？如果是的话可以直接用 `dockerd` 来开启 docker 守护进程。
为避免 off-topic，有进一步问题请单独开一个 issue。
