### ISSUE TITLE
同时封装 VPN 软件

### ISSUE THREAD

**Issue by kylesliu** [Hagb/docker-easyconnect#68]
平时代码开发较多，每个程序都配置比较麻烦。是否可以在docker封装下 L2TP 等VPN server呢

**Comment by Hagb** [comment]
> 平时代码开发较多，每个程序都配置比较麻烦。是否可以在docker封装下 L2TP 等VPN server呢

是想设成全局的透明代理还是？可能 L2TP 不一定好办法

**Comment by yushaye** [comment]
> 平时代码开发较多，每个程序都配置比较麻烦。是否可以在docker封装下 L2TP 等VPN server呢

可以搭配开源代理软件netch，支持按进程、ip规则走socket5代理。

**Comment by Hagb** [comment]
> 平时代码开发较多，每个程序都配置比较麻烦。是否可以在docker封装下 L2TP 等VPN server呢

这类方案比较重，而且网络配置上会让现在容器内的网络情况变得更加复杂（为了处理容器内的路由和防火墙费了很大劲）。因此目前不考虑加入此类功能
