### ISSUE TITLE
Socks5 代理监听 ipv6 地址

### ISSUE THREAD

**Issue by lyc8503** [Hagb/docker-easyconnect#74]
想通过家中的另一台服务器将 EasyConnect 转为 Socks5 代理并再次开放到公网.

可是移动家庭宽带没有 ipv4 公网 ip, 只能使用 ipv6 ddns. 目前 Socks5 代理监听的地址是 0.0.0.0/0, ipv6 无法连接, 是否能修改使其监听 [::]? 这样如果 Docker 也修改配置启用 ipv6 的话, ipv4 和 ipv6 就都可以访问了 Socks5 代理了.

**Comment by Hagb** [comment]
感谢反馈。方才已经在 [8aaafa7](https://github.com/Hagb/docker-easyconnect/commit/8aaafa73af5e0631fc980ab7001f6061481d966b) 解决了，使用最新版镜像即可
