### ISSUE TITLE
Next authentication is "SMS Authentication"  But we don't support it

### ISSUE THREAD

**Issue by ycilry** [Hagb/docker-easyconnect#78]
Digest: sha256:f4201bf05b8b1e88316dfa27a8e450140c5ca46821bab3fc681d266db5b9cba0
Status: Downloaded newer image for hagb/docker-easyconnect:cli
WARNING: logging deactivated (can't log to stdout when daemonized)
auto login is disabled
Authenticate failed, reason: Invalid username or password!
Please reinput!
username: ******
password: *********
Next authentication is "SMS Authentication"
But we don't support it
user "*******" login FAILED!

**Comment by TomYule** [comment]
> CLI 版不支持某些功能，请尝试使用 GUI 版

GUI版本在哪里
