### ISSUE TITLE
VNC连进去输入中文用户名不支持怎么处理？

### ISSUE THREAD

**Issue by missops** [Hagb/docker-easyconnect#80]
![image](https://user-images.githubusercontent.com/35713413/139220964-4da6edd1-8a4b-4e3f-ac21-c77f596645fd.png)

vnc连进去之后，用户名是中文不支持输入，怎么处理 ？

**Comment by Hagb** [comment]
有的 vnc 客户端能支持剪切板共享，此外亦可借用 `ECPASSWORD` 环境变量来传递用户名到剪切板（加上 `-e ECPASSWORD=用户名` 参数）

**Comment by penfree** [comment]
@Hagb 剪贴板共享粘贴过去的是乱码怎么破
