### ISSUE TITLE
威联通docker下sock5端口和http端口无法打开

### ISSUE THREAD

**Issue by OctoberCK** [Hagb/docker-easyconnect#81]
--device命令在nas的docker下无法使用，就算把本容器桥接至主路由开放所有端口，sock5隧道也无法建立。

**Comment by Hagb** [comment]
看看 `/lib/modules` 下有没有 tun.ko？
```shell
find /lib/modules -name tun.ko
```

如果无，那可能比较难搞。如果有的话，看看能不能切换到 root 用户并运行
``` shell
insmod 上一条命令输出的路径
```

**Comment by OctoberCK** [comment]
modules里存在tun.ko，但

> 看看 `/lib/modules` 下有没有 tun.ko？
> 
> ```shell
> find /lib/modules -name tun.ko
> ```
> 
> 如果无，那可能比较麻烦（需要自己编译模块）。
> 
> 如果有的话：
> 
> 看看能不能切换到 root 用户并运行
> 
> ```shell
> insmod 上一条命令输出的路径
> ```
> 
> 如果不能切换用户，也可以给 docker 加上 `-v /lib/modules:/lib/modules:ro --privileged` 参数并在容器里运行 insmod

且已经使用insmod插入tun.ko模块，重启容器后1080和8888端口仍未打开。

**Comment by Hagb** [comment]
`--device` 参数有没有使用？

**Comment by OctoberCK** [comment]
> `--device` 参数有没有使用？

使用了，但由于使用端口映射总是无法连接，所以docker网络我使用的是host模式，而非NAT模式

**Comment by OctoberCK** [comment]
> `--device` 参数有没有使用？

非常感谢，重新映射端口后隧道已经打开了，命令127.0.0.1在威联通下需去掉或改0.0.0.0即可，谢谢您。
