### ISSUE TITLE
即使连接服务器也要要求升级，但是升级不了

### ISSUE THREAD

**Issue by kof8855** [Hagb/docker-easyconnect#82]
用的7.6.7版本，提示升级但是升级不了

**Comment by Hagb** [comment]
连接的 easyconnect 服务器有给出客户端不？有的话能否提供一下

**Comment by kof8855** [comment]
> 连接的 easyconnect 服务器有给出客户端不？有的话能否提供一下

是在线升级的，即使下载了服务器页面的客户，安装完登录后也得自动更新一遍。哎

**Comment by kof8855** [comment]
> 连接的 easyconnect 服务器有给出客户端不？有的话能否提供一下

linux和windows版的版本

http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb


![image](https://user-images.githubusercontent.com/57129756/142590122-93623c61-ddc8-4494-be1c-1ec24edd97c6.png)

![image](https://user-images.githubusercontent.com/57129756/142589951-eb89a17d-40ef-4924-bf4f-b35313fb00a4.png)

**Comment by kof8855** [comment]
就这样一直update

![image](https://user-images.githubusercontent.com/57129756/142594996-2f95e9f0-53aa-4d8e-9b71-92d3ff53dcd5.png)

**Comment by kof8855** [comment]
![image](https://user-images.githubusercontent.com/57129756/142595635-6f75775f-58e4-4cb7-a442-ffc8a5e0ab93.png)

**Comment by Hagb** [comment]
不知道 windows 版本要不要下载更新

**Comment by Q11shiyi** [comment]
同问，我也是出现这个情况，没办法连接上

**Comment by Hagb** [comment]
emmm 这个应该是深信服的锅了，我这里恐怕没法解决

**Comment by Hagb** [comment]
我看 heauag 解决了 7.6.3 版本的这个问题

https://github.com/Hagb/docker-easyconnect/issues/87#issuecomment-996415180

或许可以试试 7.6.7 能不能通过这个 dockerfile 来解决？（其中的下载地址换成 7.6.7 的 http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb）

**Comment by pumbf** [comment]
> 我看 heauag 解决了 7.6.3 版本的一个表现类似的问题
> 
> [#87 (comment)](https://github.com/Hagb/docker-easyconnect/issues/87#issuecomment-996415180)
> 
> 或许可以试试 7.6.7 能不能通过这个 dockerfile 来解决？（其中的下载地址换成 7.6.7 的 [http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb）](http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb%EF%BC%89)

试过可以使用

**Comment by Hagb** [comment]
重新构建了一下 dockerhub 上的镜像，现在 dockerhub 上的版本也应该可以用了

**Comment by kof8855** [comment]
> 重新构建了一下 dockerhub 上的镜像，现在 dockerhub 上的版本也应该可以用了

哎  我这边重新拉了镜像  情况还是一样。我们公司的版本搞特殊么
