### ISSUE TITLE
mac和windows环境下7.6.7版本会有不同吗？

### ISSUE THREAD

**Issue by Taoja** [Hagb/docker-easyconnect#85]
我用mac安装docker运行7.6.7版本可以正常使用ec
但是用window环境安装docker运行7.6.7 就会提示客户端和服务端版本不一致
命令都一样
windows环境有安装ec

**Comment by Homura37** [comment]
请问这个问题你解决了吗，我也遇到同样的问题。
在wsl2里面提示版本有不对，但原生Linux里面正常。

**Comment by Homura37** [comment]
> 请问这个问题你解决了吗，我也遇到同样的问题。 在wsl2里面提示版本有不对，但原生Linux里面正常。

我又安装了一个 Debian 11 版本的 WSL2 可以正常使用了，很奇怪。

**Comment by Taoja** [comment]
> 请问这个问题你解决了吗，我也遇到同样的问题。 在wsl2里面提示版本有不对，但原生Linux里面正常。

windows版每次删除conf目录就行了，只是没办法保存用户名和服务器配置
