### ISSUE TITLE
Challeng Authentication

### ISSUE THREAD

**Issue by Q11shiyi** [Hagb/docker-easyconnect#86]
Next authentication is "Challeng Authentication"
But we don't support it
目前不支持挑战码登录吗

**Comment by Hagb** [comment]
试试用图形化客户端？

**Comment by Q11shiyi** [comment]
公司服务器要连接VPN，没有图形化界面呢

**Comment by Hagb** [comment]
带 vnc 的容器可以在没有图形界面的系统中运行，然后远程用 vnc 客户端连接过去操作。
