### ISSUE TITLE
The EasyConnect version is too low. Please update the client to the latest version.

### ISSUE THREAD

**Issue by heauag** [Hagb/docker-easyconnect#87]
The EasyConnect version is too low. Please update the client to the latest version.
![image](https://user-images.githubusercontent.com/77401487/146482075-3ea12fde-26db-4311-a4f6-54a88427d7b9.png)

**Comment by Boltzmachine** [comment]
I also encountered this problem yesterday.

**Comment by heauag** [comment]
> 
[root@k8s-slaver docker-easyconnect-master]# cat Dockerfile
FROM debian:buster-slim

ARG BUILD_ENV=local

RUN if [ "${BUILD_ENV}" = "local" ]; then sed -i s/deb.debian.org/mirrors.cqu.edu.cn/ /etc/apt/sources.list; fi &&\
    apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        libgtk2.0-0 libx11-xcb1 libxtst6 libnss3 libasound2 libdbus-glib-1-2 iptables xclip\
        dante-server tigervnc-standalone-server tigervnc-common dante-server psmisc flwm x11-utils\
        busybox libssl-dev iproute2 tinyproxy-bin systemd-sysv lsb-release

ARG EC_URL=http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb

RUN cd tmp &&\
    busybox wget "${EC_URL}" -O EasyConnect.deb &&\
    dpkg -i EasyConnect.deb && rm EasyConnect.deb

COPY ./docker-root /

RUN rm -f /usr/share/sangfor/EasyConnect/resources/conf/easy_connect.json &&\
    mv /usr/share/sangfor/EasyConnect/resources/conf/ /usr/share/sangfor/EasyConnect/resources/conf_backup &&\
    ln -s /root/conf /usr/share/sangfor/EasyConnect/resources/conf

#ENV TYPE="" PASSWORD="" LOOP=""
#ENV DISPLAY

VOLUME /root/ /usr/share/sangfor/EasyConnect/resources/logs/

CMD ["start.sh"]

你可以试试用这个脚本重新打一个镜像

**Comment by Boltzmachine** [comment]
可以用 谢谢！

**Comment by imic07** [comment]
@Boltzmachine 可以上传个你打包好的镜像吗？

**Comment by imic07** [comment]
> > 
> 
> [root@k8s-slaver docker-easyconnect-master]# cat Dockerfile FROM debian:buster-slim
> 
> ARG BUILD_ENV=local
> 
> RUN if [ "${BUILD_ENV}" = "local" ]; then sed -i s/deb.debian.org/mirrors.cqu.edu.cn/ /etc/apt/sources.list; fi && apt-get update && apt-get install -y --no-install-recommends --no-install-suggests libgtk2.0-0 libx11-xcb1 libxtst6 libnss3 libasound2 libdbus-glib-1-2 iptables xclip dante-server tigervnc-standalone-server tigervnc-common dante-server psmisc flwm x11-utils busybox libssl-dev iproute2 tinyproxy-bin systemd-sysv lsb-release
> 
> ARG EC_URL=http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb
> 
> RUN cd tmp && busybox wget "${EC_URL}" -O EasyConnect.deb && dpkg -i EasyConnect.deb && rm EasyConnect.deb
> 
> COPY ./docker-root /
> 
> RUN rm -f /usr/share/sangfor/EasyConnect/resources/conf/easy_connect.json && mv /usr/share/sangfor/EasyConnect/resources/conf/ /usr/share/sangfor/EasyConnect/resources/conf_backup && ln -s /root/conf /usr/share/sangfor/EasyConnect/resources/conf
> 
> #ENV TYPE="" PASSWORD="" LOOP="" #ENV DISPLAY
> 
> VOLUME /root/ /usr/share/sangfor/EasyConnect/resources/logs/
> 
> CMD ["start.sh"]
> 
> 你可以试试用这个脚本重新打一个镜像

有没有Manjaro下的Dockerfile呢

**Comment by Hagb** [comment]
看来是 sangfor 在相同的下载地址上放了新的包
#90

**Comment by Hagb** [comment]
重新构建了一下 dockerhub 上的镜像，现在 dockerhub 上的版本也应该可以用了
