### ISSUE TITLE
client version and server software version is not matching

### ISSUE THREAD

**Issue by yulongzhang62** [Hagb/docker-easyconnect#88]
vnc连接时提示客户端和服务器软件版本不一致

**Comment by Hagb** [comment]
试试使用 https://github.com/Hagb/docker-easyconnect/issues/87#issuecomment-996415180 的 Dockerfile 行不行？
其中 EasyConnect 下载链接换成你所用版本的连接

**Comment by yulongzhang62** [comment]
EasyConnect不知道改使用那个版本合适，使用低版本会提示版本太低，换成7.6.7又会提示客户端和服务器软件版本不一致

**Comment by Hagb** [comment]
> EasyConnect不知道改使用那个版本合适，使用低版本会提示版本太低，换成7.6.7又会提示客户端和服务器软件版本不一致

看看你服务器给出的客户端下载地址

**Comment by yulongzhang62** [comment]
[](url
![QQ截图20211218132117](https://user-images.githubusercontent.com/30460973/146630740-875ba7c0-7623-4aa7-a4e7-63122f0321d2.png)
)

**Comment by yulongzhang62** [comment]
EC_URL=http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb

**Comment by Hagb** [comment]
那使用你的服务器给出的下载地址

**Comment by yulongzhang62** [comment]
请问有7.6.6版本的下载地址吗？

**Comment by Cheukfung** [comment]
> vnc连接时提示客户端和服务器软件版本不一致

删掉.ecdata下面的文件就可以了

**Comment by Hagb** [comment]
@yulongzhang62 尝试下清除 .ecdata 内容并使用最新容器？

**Comment by Thendytx** [comment]
我也遇到了同样（或类似）的问题。
在我的x64win11机器上运行的容器中，第二次运行时就会提示version not matching。
由于服务器给出的linux版本也是7.6.7_3.deb，因此我没有多做改动，使用了readme中提到的图形界面版的安装命令。
暂时的解决方法是按照 @Cheukfung 所提到的删除.ecdata下的文件，这样就不会提示not matching，但这样做会理所当然地失去所有使用数据，需要重新输入vpn地址、账号和密码。
我是一个容器新手，如果有什么愚蠢言论还请指教。
希望有更简单方便的解决方案，或是对该问题的进一步解释。

**Comment by kongfei605** [comment]
```sed -i 's/7.6.7.5/7.6.7.1/g'  ~/.ecdata/conf/pkg_version.xml```  问题可解

 #[issue124 ](https://github.com/Hagb/docker-easyconnect/issues/124#issuecomment-1075832610)
