### ISSUE TITLE
请问谁有7.6.6下载地址

### ISSUE THREAD

**Issue by yulongzhang62** [Hagb/docker-easyconnect#89]

**Comment by Hagb** [comment]
是 7.6.6 的服务器吗？服务器应该会提供客户端下载地址的。

**Comment by glide-the** [comment]
服务器提供的是install-sh。。。

**Comment by Hagb** [comment]
> 服务器提供的是install-sh。。。

@glide-the 请问方便提供吗？
另外如果这个install-sh 的下载地址是用 sangfor.com 这样的公开域名提供的，也请最好提供下载地址。

**Comment by Hagb** [comment]
> 这个脚本根本不能用的。 不过我今天使用了这个仓库的运行链接成功了 不过似乎是java的版本和系统不兼容，某些网络还是无法访问 https://github.com/Jimleerx/EasyConnectForLinux

emmm 用浏览器和 java 的应该是很老的 easyconnect 版本了，在我的认识里。运行方式和现在有的比较多的版本大相径庭
