### ISSUE TITLE
easyconnect deb 版本更新，以及新版 easyconnect 阻止容器开放端口

### ISSUE THREAD

**Issue by imic07** [Hagb/docker-easyconnect#90]
你好，我之前使用的是7.6.3版本，很稳定，但是这两天使用的时候提示我升级，然后就不能用了. 我下载了deb安装包发现版本是7.6.3.1了，希望打包个,下面是不同的发行版本地址

http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb
http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x86.deb
http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.rpm

![image](https://user-images.githubusercontent.com/16321067/146707401-88c891fd-a3ae-4c68-ab60-d43978bce6b7.png)

**Comment by imic07** [comment]
希望能提供个Manjaro下的构建镜像的脚本

**Comment by yushaye** [comment]
> 

你好，可以上传下7.6.3.1的deb包吗，我也遇到同样问题。

**Comment by imic07** [comment]
> > 
> 
> 你好，可以上传下7.6.3.1的deb包吗，我也遇到同样问题。

就是上面里面的链接,下载就行

**Comment by Hagb** [comment]
emmm… 这么说破案了… 这个地址和 7.6.3 的地址是相同的，看来是地址相同但内容更新了……
http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb 7.6.3.0
http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb 7.6.3.1

感谢感谢，之前真的百思不得其解（顺带这个问题我用学校的服务器每复现出来）
这样的话用 dockerfile 重新构建一下就行了

**Comment by yushaye** [comment]
感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了

**Comment by imic07** [comment]
> 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了

你启动的命令是什么呢？我打包出来的镜像，执行报错：
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "start.sh": executable file not found in $PATH: unknown.

**Comment by happydts** [comment]
同是这个错
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "start.sh": executable file not found in $PATH: unknown.

**Comment by mac-zhou** [comment]
> 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了

修改一下detect-iptables.sh

```shell
#!/bin/bash
# 不支持 nftables 时使用 iptables-legacy
## 感谢 @BoringCat https://github.com/Hagb/docker-easyconnect/issues/5
if { [ -z "$IPTABLES_LEGACY" -a -z "$(iptables-legacy-save)" ] && iptables-nft-save ; } 1>/dev/null 2>/dev/null
then
	update-alternatives --set iptables /usr/sbin/iptables-nft
	update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
else
	update-alternatives --set iptables /usr/sbin/iptables-legacy
	update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
fi

# 7.6.3.1 版本开始使用iptables来阻止本地端口访问，无法使用代理，暴力删除，因为不知道它什么时候又会加上去
while true; do 
	iptables -t filter -D SANGFOR_VIRTUAL -j DROP 1>/dev/null 2>/dev/null
	iptables-legacy -t filter -D SANGFOR_VIRTUAL -j DROP 1>/dev/null 2>/dev/null
	sleep 5
done 2>/dev/null &
````

**Comment by mac-zhou** [comment]
> > 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了
> 
> 你启动的命令是什么呢？我打包出来的镜像，执行报错： docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "start.sh": executable file not found in $PATH: unknown.

```shell
git clone https://github.com/Hagb/docker-easyconnect; cd docker-easyconnect
# 修改detect-iptables.sh 后打包
docker build -t hagb/docker-easyconnect:7.6.3.1 --build-arg EC_URL='http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb' .```

**Comment by imic07** [comment]
@mac-zhou 我是按照文档中给的教程打包的：
```
# https://github.com/Hagb/docker-easyconnect/blob/master/doc/build.md
# 带 VNC 服务端
git clone https://github.com/hagb/docker-easyconnect.git
cd docker-easyconnect
EC_VER=7.6.3  # 此变量填写 ec_urls 文件夹中的版本，`7.6.3`或`7.6.7`
docker image build --build-arg EC_URL=$(cat ec_urls/${EC_VER}.txt) --tag hagb/docker-easyconnect -f Dockerfile .
```

现在按照你给的， 先修改了docker-easyconnect-master/docker-root/usr/local/bin/detect-iptables.sh,然后执行
```
cd docker-easyconnect
# 修改detect-iptables.sh 后打包
docker build -t hagb/docker-easyconnect:7.6.3.1 --build-arg \
EC_URL='http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb' .
```
打包成功后运行 还是报同样的错误.

docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "start.sh": executable file not found in $PATH: unknown.


你能上传个你打包好的镜像吗？
```
 docker save -o easy.tar hagb/docker-easyconnect:7.6.3.1
```

**Comment by imic07** [comment]
@mac-zhou 我是按照文档中给的教程打包的(Ubuntu)：
```
# https://github.com/Hagb/docker-easyconnect/blob/master/doc/build.md
# 带 VNC 服务端
git clone https://github.com/hagb/docker-easyconnect.git
cd docker-easyconnect
EC_VER=7.6.3  # 此变量填写 ec_urls 文件夹中的版本，`7.6.3`或`7.6.7`
docker image build --build-arg EC_URL=$(cat ec_urls/${EC_VER}.txt) --tag hagb/docker-easyconnect -f Dockerfile .
```

现在按照你给的， 先修改了docker-easyconnect-master/docker-root/usr/local/bin/detect-iptables.sh,然后执行
```
cd docker-easyconnect
# 修改detect-iptables.sh 后打包
docker build -t hagb/docker-easyconnect:7.6.3.1 --build-arg \
EC_URL='http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb' .
```
打包成功后运行 还是报同样的错误.

docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "start.sh": executable file not found in $PATH: unknown.


你能上传个你打包好的镜像吗？
```
 docker save -o easy.tar hagb/docker-easyconnect:7.6.3.1
```

**Comment by Hagb** [comment]
> @mac-zhou 我是按照文档中给的教程打包的(Ubuntu)：
> 
> ```
> # https://github.com/Hagb/docker-easyconnect/blob/master/doc/build.md
> # 带 VNC 服务端
> git clone https://github.com/hagb/docker-easyconnect.git
> cd docker-easyconnect
> EC_VER=7.6.3  # 此变量填写 ec_urls 文件夹中的版本，`7.6.3`或`7.6.7`
> docker image build --build-arg EC_URL=$(cat ec_urls/${EC_VER}.txt) --tag hagb/docker-easyconnect -f Dockerfile .
> ```
> 
> 现在按照你给的， 先修改了docker-easyconnect-master/docker-root/usr/local/bin/detect-iptables.sh,然后执行
> 
> ```
> cd docker-easyconnect
> # 修改detect-iptables.sh 后打包
> docker build -t hagb/docker-easyconnect:7.6.3.1 --build-arg \
> EC_URL='http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb' .
> ```
> 
> 打包成功后运行 还是报同样的错误.
> 
> docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "start.sh": executable file not found in $PATH: unknown.
> 
> 你能上传个你打包好的镜像吗？
> 
> ```
>  docker save -o easy.tar hagb/docker-easyconnect:7.6.3.1
> ```

是在什么操作系统、什么文件系统下操作的？感觉有点像是 start.sh 的可执行权限没了

**Comment by imic07** [comment]
@mac-zhou 我打包是在Ubuntu,  执行是在Manjaro下执行的.

**Comment by mac-zhou** [comment]
> @mac-zhou @Hagb 我打包是在Ubuntu, 执行是在Manjaro下执行的. 在Ubuntu(刚下的Lts版本)下执行也是报错.
> 
> ```
> docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -e PASSWORD=xxxx -v $HOME/.ecdata:/root -p 127.0.0.1:5901:5901 -p 127.0.0.1:1080:1080 hagb/docker-easyconnect:7.6.3.1
> ```

看着你流程不太对呀，我一般是如下执行
```
docker save hagb/docker-easyconnect:7.6.3.1 | gzip > docker-easyconnec.tgz
docker load --input  docker-easyconnec.tgz
```

**Comment by imic07** [comment]
@mac-zhou 我导入来的.  把你打包的镜像上传个呢，我试下你的 .

**Comment by Hagb** [comment]
> @mac-zhou @Hagb 我打包是在Ubuntu, 执行是在Manjaro下执行的. 在Ubuntu(刚下的Lts版本)下执行也是报错.
> 
> ```
> docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -e PASSWORD=xxxx -v $HOME/.ecdata:/root -p 127.0.0.1:5901:5901 -p 127.0.0.1:1080:1080 hagb/docker-easyconnect:7.6.3.1
> ```

试一下
```bash
docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -e PASSWORD=xxxx -v $HOME/.ecdata:/root -p 127.0.0.1:5901:5901 -p 127.0.0.1:1080:1080 hagb/docker-easyconnect:7.6.3.1 bash /usr/local/bin/start.sh
```
行不行？

**Comment by Hagb** [comment]
> 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了

我这里没有复现出来，如果你那儿还能复现的话请单独开一个 issue 来处理这件事。

**Comment by imic07** [comment]
@Hagb 
![image](https://user-images.githubusercontent.com/16321067/146889219-e4688c5d-7fe5-4c41-b613-2ce7ca1e01c1.png)

**Comment by Hagb** [comment]
@imic07  看起来确实是可执行权限丢失了，你这个 `/data` 是不是在不支持 unix 权限的文件系统上？
如果不是的话，试试 `git checkout -- .`  之后再进行构建

**Comment by mac-zhou** [comment]
> > 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了
> 
> @yushaye 我这里没有复现出来，如果你那儿还能复现的话请单独开一个 issue 来处理这件事。

这个问题取决于服务段下发的策略，我这边连上后，easyconnet会在最后加个DROP的规则

**Comment by yushaye** [comment]
> > 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了
> 
> 修改一下detect-iptables.sh
> 
> ```shell
> #!/bin/bash
> # 不支持 nftables 时使用 iptables-legacy
> ## 感谢 @BoringCat https://github.com/Hagb/docker-easyconnect/issues/5
> if { [ -z "$IPTABLES_LEGACY" -a -z "$(iptables-legacy-save)" ] && iptables-nft-save ; } 1>/dev/null 2>/dev/null
> then
> 	update-alternatives --set iptables /usr/sbin/iptables-nft
> 	update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
> else
> 	update-alternatives --set iptables /usr/sbin/iptables-legacy
> 	update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
> fi
> 
> # 7.6.3.1 版本开始使用iptables来阻止本地端口访问，无法使用代理，暴力删除，因为不知道它什么时候又会加上去
> while true; do 
> 	iptables -t filter -D SANGFOR_VIRTUAL -j DROP 1>/dev/null 2>/dev/null
> 	iptables-legacy -t filter -D SANGFOR_VIRTUAL -j DROP 1>/dev/null 2>/dev/null
> 	sleep 5
> done 2>/dev/null &
> ```

可以使用了，感谢大佬！

**Comment by imic07** [comment]
@Hagb 
![image](https://user-images.githubusercontent.com/16321067/146889787-af34f937-3d4d-4282-a529-e6d65cf204e2.png)

**Comment by Hagb** [comment]
@yushaye 

> @Hagb ![image](https://user-images.githubusercontent.com/16321067/146889787-af34f937-3d4d-4282-a529-e6d65cf204e2.png)

试试在家目录进行构建吧（`cd `切换回家目录）

**Comment by Hagb** [comment]
> 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了

能否试试使用原来的 Dockerfile，在 `docker-root/usr/local/sbin/` 新建一个文件 `iptables`，内容为：
```
#!/bin/bash 
[ "$*" = "-t filter -A SANGFOR_VIRTUAL -j DROP" ] && exit 0
exec /usr/sbin/iptables "$@"
```
并加上可执行权限 `chmod +x`，之后再进行构建，看看能不能解决？

**Comment by Hagb** [comment]
> 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了

@yushaye 这个应该可以被刚刚加的 b6c00df81ce962dcb97f0c38e9ac702a276452ab 修复。

带有新版 EasyConnect 的新镜像已经推送到 docker hub

**Comment by yushaye** [comment]
> 

测试该方案登录vpn后仍然无法访问容器端口

**Comment by yushaye** [comment]
> > 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了
> 
> @yushaye 这个应该可以被刚刚加的 [b6c00df](https://github.com/Hagb/docker-easyconnect/commit/b6c00df81ce962dcb97f0c38e9ac702a276452ab) 修复。
> 
> 带有新版 EasyConnect 的新镜像已经推送到 docker hub

测试该方案登录vpn后仍然无法访问容器端口

**Comment by mac-zhou** [comment]
> @yushaye
> 
> > 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了
> 
> 能否试试使用原来的 Dockerfile，在 `docker-root/usr/local/sbin/` 新建一个文件 `iptables`，内容为：
> 
> ```
> #!/bin/sh 
> [ "$*" = "-t filter -A SANGFOR_VIRTUAL -j DROP" ] && exit 0
> exec /usr/sbin/iptables "$@"
> ```
> 
> 并加上可执行权限 `chmod +x`，之后再进行构建，看看能不能解决？

可以用这方法 学习了👍

**Comment by Hagb** [comment]
> > > 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了
> > 
> > 
> > @yushaye 这个应该可以被刚刚加的 [b6c00df](https://github.com/Hagb/docker-easyconnect/commit/b6c00df81ce962dcb97f0c38e9ac702a276452ab) 修复。
> > 带有新版 EasyConnect 的新镜像已经推送到 docker hub
> 
> 测试该方案登录vpn后仍然无法访问容器端口

后来有推了一个修复的 8c13666。这里测试是从源码构建还是用 dockerhub 上的预编译包？

**Comment by yushaye** [comment]
> > > > 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了
> > > 
> > > 
> > > @yushaye 这个应该可以被刚刚加的 [b6c00df](https://github.com/Hagb/docker-easyconnect/commit/b6c00df81ce962dcb97f0c38e9ac702a276452ab) 修复。
> > > 带有新版 EasyConnect 的新镜像已经推送到 docker hub
> > 
> > 
> > 测试该方案登录vpn后仍然无法访问容器端口
> 
> 后来又推了一个修复的 [8c13666](https://github.com/Hagb/docker-easyconnect/commit/8c13666f27a66fe24c91f49f047b3a88f1908635)。这里测试是从源码构建还是用 dockerhub 上的预编译包？

测试新修复仍然不能访问容器端口，从源码构建的镜像。

**Comment by mac-zhou** [comment]
我的情况是 规则是在 iptables-legacy 不在iptables-nft

**Comment by mac-zhou** [comment]
> > > > > 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了
> > > > 
> > > > 
> > > > @yushaye 这个应该可以被刚刚加的 [b6c00df](https://github.com/Hagb/docker-easyconnect/commit/b6c00df81ce962dcb97f0c38e9ac702a276452ab) 修复。
> > > > 带有新版 EasyConnect 的新镜像已经推送到 docker hub
> > > 
> > > 
> > > 测试该方案登录vpn后仍然无法访问容器端口
> > 
> > 
> > 后来又推了一个修复的 [8c13666](https://github.com/Hagb/docker-easyconnect/commit/8c13666f27a66fe24c91f49f047b3a88f1908635)。这里测试是从源码构建还是用 dockerhub 上的预编译包？
> 
> 测试新修复仍然不能访问容器端口，从源码构建的镜像。

你加上 IPTABLES_LEGACY 环境变量 我估计就可以了

**Comment by mac-zhou** [comment]
看了一下 /usr/share/sangfor/EasyConnect/resources/logs/Util.log, 优先使用iptables-legacy
```
[INFO][systemCmdReal-91][init_iptables_exec-114] systemCmd system(cmd) cmd:iptables-legacy -V
[INFO][init_iptables_exec-115]init_iptables_exec cmd:iptables-legacy -V success, will take 'iptables-legacy' as executor
[INFO][systemCmdReal-91][init_iptables_exec-124] systemCmd system(cmd) cmd:iptables-legacy-save -V
```
同时我测试删除iptables-legacy后， EC使用了iptables-nft

@Hagb 是否考虑只保留1个版本的iptables 目前保留2个版本是什么的原因呢？

**Comment by Hagb** [comment]
> > > > > > 感谢，7.6.3.1的包可以登录了，但是会屏蔽容器的端口，5901和1080都无法访问了
> > > > > 
> > > > > 
> > > > > @yushaye 这个应该可以被刚刚加的 [b6c00df](https://github.com/Hagb/docker-easyconnect/commit/b6c00df81ce962dcb97f0c38e9ac702a276452ab) 修复。
> > > > > 带有新版 EasyConnect 的新镜像已经推送到 docker hub
> > > > 
> > > > 
> > > > 测试该方案登录vpn后仍然无法访问容器端口
> > > 
> > > 
> > > 后来又推了一个修复的 [8c13666](https://github.com/Hagb/docker-easyconnect/commit/8c13666f27a66fe24c91f49f047b3a88f1908635)。这里测试是从源码构建还是用 dockerhub 上的预编译包？
> > 
> > 
> > 测试新修复仍然不能访问容器端口，从源码构建的镜像。
> 
> 你加上 IPTABLES_LEGACY 环境变量 我估计就可以了

> @Hagb 是否考虑只保留1个版本的iptables 目前保留2个版本是什么的原因呢？

@mac-zhou 因为两者所用的内核组件不同，宿主机使用其中一个时另一个不会生效或无法设置（不能通用）。而 docker-easyconnect 的用户中，两种情况都有。

[`docker-root/usr/local/bin/detect-iptables.sh`](https://github.com/Hagb/docker-easyconnect/blob/master/docker-root/usr/local/bin/detect-iptables.sh) 就是为了实现自动检测当前机器所用的是哪一个并自动设置。目前用 iptables-legacy 的多是非桌面系统（如路由器、NAS 的系统、wsl 等），桌面系统大多数都是 iptables-nft，在加入 detect-iptables.sh 后似乎大多可以检测出来，wsl 似乎是其中一个例外（wsl 前面有朋友反应过一些问题，但是因为我没有测试 wsl 的环境所以后来没做太多修复）。

**Comment by Hagb** [comment]
> 看了一下 /usr/share/sangfor/EasyConnect/resources/logs/Util.log, 优先使用iptables-legacy
> 
> ```
> [INFO][systemCmdReal-91][init_iptables_exec-114] systemCmd system(cmd) cmd:iptables-legacy -V
> [INFO][init_iptables_exec-115]init_iptables_exec cmd:iptables-legacy -V success, will take 'iptables-legacy' as executor
> [INFO][systemCmdReal-91][init_iptables_exec-124] systemCmd system(cmd) cmd:iptables-legacy-save -V
> ```
> 
> 同时我测试删除iptables-legacy后， EC使用了iptables-nft

emmm EasyConnect 是显式地调用了 `iptables-legacy` 和 `iptables-nft` 吗？（更新前应该是调用 `iptables` 的）

**Comment by mac-zhou** [comment]
> > 看了一下 /usr/share/sangfor/EasyConnect/resources/logs/Util.log, 优先使用iptables-legacy
> > ```
> > [INFO][systemCmdReal-91][init_iptables_exec-114] systemCmd system(cmd) cmd:iptables-legacy -V
> > [INFO][init_iptables_exec-115]init_iptables_exec cmd:iptables-legacy -V success, will take 'iptables-legacy' as executor
> > [INFO][systemCmdReal-91][init_iptables_exec-124] systemCmd system(cmd) cmd:iptables-legacy-save -V
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 同时我测试删除iptables-legacy后， EC使用了iptables-nft
> 
> emmm EasyConnect 是显式地调用了 `iptables-legacy` 和 `iptables-nft` 吗？（更新前应该是调用 `iptables` 的）

从测试结果来看是的 且还是调用了绝对路径的iptables-legacy 因为我同时增加了 /usr/local/sbin/iptables-legacy 并无效果

https://github.com/Hagb/docker-easyconnect/blob/8c13666f27a66fe24c91f49f047b3a88f1908635/docker-root/usr/local/bin/start.sh#L41

建议不管它优先用啥版本，2个版本里都删除
```zsh
( while true; do sleep 5 ; /usr/sbin/iptables-nft -D SANGFOR_VIRTUAL -j DROP 2>/dev/null ; /usr/sbin/iptables-legacy -D SANGFOR_VIRTUAL -j DROP 2>/dev/null ; done )&
```

**Comment by Hagb** [comment]
> 从测试结果来看是的 且还是调用了绝对路径的iptables-legacy 因为我同时增加了 /usr/local/sbin/iptables-legacy 并无效果

这个 `/usr/local/sbin/iptables-legacy` 有没有加可执行权限？顺带看看 `echo $PATH` 的输出。
 
> 建议不管它优先用啥版本，2个版本里都删除
> ```bash
> ( while true; do sleep 5 ; /usr/sbin/iptables-nft -D SANGFOR_VIRTUAL -j DROP 2>/dev/null ; /usr/sbin/iptables-legacy -D SANGFOR_VIRTUAL -j DROP 2>/dev/null ; done )&
> ```

如果它会多次调用的话，这种方式有一个问题是它加入 DROP 规则和我们删除规则之间有一段 5 秒以内的空隙，这段时间内使用容器开出来的代理会受影响（如果它只加一次的话也会有影响，但是会小一些）。

**Comment by mac-zhou** [comment]
> > 从测试结果来看是的 且还是调用了绝对路径的iptables-legacy 因为我同时增加了 /usr/local/sbin/iptables-legacy 并无效果
> 
> 这个 `/usr/local/sbin/iptables-legacy` 有没有加可执行权限？顺带看看 `echo $PATH` 的输出。
> 
> > 建议不管它优先用啥版本，2个版本里都删除
> > ```shell
> > ( while true; do sleep 5 ; /usr/sbin/iptables-nft -D SANGFOR_VIRTUAL -j DROP 2>/dev/null ; /usr/sbin/iptables-legacy -D SANGFOR_VIRTUAL -j DROP 2>/dev/null ; done )&
> > ```
> 
> 如果它会多次调用的话，这种方式有一个问题是它加入 DROP 规则和我们删除规则之间有一段 5 秒以内的空隙，这段时间内使用容器开出来的代理会受影响（如果它只加一次的话也会有影响，但是会小一些）。

```
root@e2cbe4a272cc:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

/usr/local/sbin/iptables-legacy 是有执行权限的，且当时我还加了行 `echo $@` 作为调试的，手工执行iptables-legacy 是有输出的

**Comment by mac-zhou** [comment]
> 
> 如果它会多次调用的话，这种方式有一个问题是它加入 DROP 规则和我们删除规则之间有一段 5 秒以内的空隙，这段时间内使用容器开出来的代理会受影响（如果它只加一次的话也会有影响，但是会小一些）。

那替换掉/usr/sbin/iptables-nft 和 /usr/sbin/iptables-legacy ？

**Comment by Hagb** [comment]
> > 如果它会多次调用的话，这种方式有一个问题是它加入 DROP 规则和我们删除规则之间有一段 5 秒以内的空隙，这段时间内使用容器开出来的代理会受影响（如果它只加一次的话也会有影响，但是会小一些）。
> 
> 那替换掉/usr/sbin/iptables-nft 和 /usr/sbin/iptables-legacy ？

可以试试？（我没有调试条件，这也是维护这个项目最麻烦的地方之一了）

**Comment by mac-zhou** [comment]
> > > 如果它会多次调用的话，这种方式有一个问题是它加入 DROP 规则和我们删除规则之间有一段 5 秒以内的空隙，这段时间内使用容器开出来的代理会受影响（如果它只加一次的话也会有影响，但是会小一些）。
> > 
> > 
> > 那替换掉/usr/sbin/iptables-nft 和 /usr/sbin/iptables-legacy ？
> 
> 可以试试？（我没有调试条件，这也是维护这个项目最麻烦的地方之一了）

试了一下 可以😄

**Comment by mac-zhou** [comment]
在 docker-root/usr/local/sbin/ 下新建2个文件，分别为iptables-legacy和iptables-nft 并给执行权限
`iptables-nft`
```zsh
#!/bin/sh
[ "$*" = "-t filter -A SANGFOR_VIRTUAL -j DROP" ] && exit 0
exec /usr/local/bin/iptables-nft "$@"
```
`iptables-legacy`
```zsh
#!/bin/sh
[ "$*" = "-t filter -A SANGFOR_VIRTUAL -j DROP" ] && exit 0
exec /usr/local/bin/iptables-legacy "$@"
```
`docker-root/usr/local/bin/detect-iptables.sh` 添加一些内容，最终内容如下：
```zsh
#!/bin/bash
if [ -f /usr/sbin/xtables-nft-multi ]; then
	ln -s -f /usr/sbin/xtables-nft-multi  /usr/local/bin/iptables-nft
	ln -s -f /usr/local/sbin/iptables-nft /usr/sbin/iptables-nft
fi

if [ -f /usr/sbin/xtables-legacy-multi ]; then
	ln -s -f /usr/sbin/xtables-legacy-multi /usr/local/bin/iptables-legacy
	ln -s -f /usr/local/sbin/iptables-legacy /usr/sbin/iptables-legacy
fi

# 不支持 nftables 时使用 iptables-legacy
## 感谢 @BoringCat https://github.com/Hagb/docker-easyconnect/issues/5
if { [ -z "$IPTABLES_LEGACY" -a -z "$(iptables-legacy-save)" ] && iptables-nft-save ; } 1>/dev/null 2>/dev/null
then
	update-alternatives --set iptables /usr/sbin/iptables-nft
	update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
else
	update-alternatives --set iptables /usr/sbin/iptables-legacy
	update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
fi
```
`docker-easyconnect/docker-root/usr/local/bin/start.sh` 注释或者删除掉第41行
```zsh
# ( while true; do sleep 5 ; iptables -D SANGFOR_VIRTUAL -j DROP 2>/dev/null ; done )&
```

**Comment by mac-zhou** [comment]
@yushaye 你试试看

**Comment by imic07** [comment]
终于可以了

```sh
#使用 X11 socket 而无 VNC 服务端
git clone https://github.com/hagb/docker-easyconnect.git
cd docker-easyconnect
EC_VER=7.6.3  # 此变量填写 ec_urls 文件夹中的版本，`7.6.3`或`7.6.7`
docker image build --build-arg EC_URL=$(cat ec_urls/${EC_VER}.txt) --tag hagb/docker-easyconnect -f Dockerfile.vncless .


#注意：如果用最新的deb打包后执行还是报错需要升级，那么需要删除easyconnect的缓存文件
rm -rf ~/.ecdata

```

**Comment by Hagb** [comment]
> 在 docker-root/usr/local/sbin/ 下新建2个文件，分别为iptables-legacy和iptables-nft 并给执行权限 `iptables-nft`
> 
> ```shell
> #!/bin/sh
> [ "$*" = "-t filter -A SANGFOR_VIRTUAL -j DROP" ] && exit 0
> exec /usr/local/bin/iptables-nft "$@"
> ```
> 
> `iptables-legacy`
> 
> ```shell
> #!/bin/sh
> [ "$*" = "-t filter -A SANGFOR_VIRTUAL -j DROP" ] && exit 0
> exec /usr/local/bin/iptables-legacy "$@"
> ```
> 
> `docker-root/usr/local/bin/detect-iptables.sh` 添加一些内容，最终内容如下：
> 
> ```shell
> #!/bin/bash
> if [ -f /usr/sbin/xtables-nft-multi ]; then
> 	ln -s -f /usr/sbin/xtables-nft-multi  /usr/local/bin/iptables-nft
> 	ln -s -f /usr/local/sbin/iptables-nft /usr/sbin/iptables-nft
> fi
> 
> if [ -f /usr/sbin/xtables-legacy-multi ]; then
> 	ln -s -f /usr/sbin/xtables-legacy-multi /usr/local/bin/iptables-legacy
> 	ln -s -f /usr/local/sbin/iptables-legacy /usr/sbin/iptables-legacy
> fi
> 
> # 不支持 nftables 时使用 iptables-legacy
> ## 感谢 @BoringCat https://github.com/Hagb/docker-easyconnect/issues/5
> if { [ -z "$IPTABLES_LEGACY" -a -z "$(iptables-legacy-save)" ] && iptables-nft-save ; } 1>/dev/null 2>/dev/null
> then
> 	update-alternatives --set iptables /usr/sbin/iptables-nft
> 	update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
> else
> 	update-alternatives --set iptables /usr/sbin/iptables-legacy
> 	update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
> fi
> ```
> 
> `docker-easyconnect/docker-root/usr/local/bin/start.sh` 注释或者删除掉第41行
> 
> ```shell
> # ( while true; do sleep 5 ; iptables -D SANGFOR_VIRTUAL -j DROP 2>/dev/null ; done )&
> ```

感谢修复，方便提交一个 pr 吗？
另外感觉将 `/usr/local/bin/iptables-nft` 链接到 `/usr/sbin/xtables-nft-multi`  是不是没有太大必要，`iptables-nft` 可以直接调用 `/usr/sbin/usr/sbin/xtables-nft-multi`。（legacy 的情形同理）

**Comment by mac-zhou** [comment]
> 
> 感谢修复，方便提交一个 pr 吗？ 另外感觉将 `/usr/local/bin/iptables-nft` 链接到 `/usr/sbin/xtables-nft-multi` 是不是没有太大必要，`iptables-nft` 可以直接调用 `/usr/sbin/xtables-nft-multi`。（legacy 的情形同理）

哦 也行 不过得带arg 比如 /usr/sbin/xtables-nft-multi iptables-nft 就等同于 /usr/sbin/iptables-nft

我再测试一下后 提交PR

**Comment by Hagb** [comment]
@mac-zhou 刚刚又看了看，如果再把 `iptables-legacy` 和 `iptables-nft` 脚本放到 `docker-root/usr/sbin/` 下好像还可以省去 `docker-root/usr/local/bin/detect-iptables.sh` 的修改。（仅供参考）

**Comment by yushaye** [comment]
@Hagb @mac-zhou 两位大佬，最新的提交测试可以正常使用了。
