### ISSUE TITLE
7.6.7图形版 VNC登录之后页面卡死，导致无法代理

### ISSUE THREAD

**Issue by liuzza** [Hagb/docker-easyconnect#92]
7.6.7图形版 VNC登录之后页面卡死，再次连接VNC 显示无法连接， 代理业务使用， 
日志如下
`
WARNING: logging deactivated (can't log to stdout when daemonized)
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
Cleaning stale pidfile '/root/.vnc/d060928abff8:1.pid'!
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.

New 'd060928abff8:1 (root)' desktop at :1 on machine d060928abff8

Starting applications specified in flwm
Log file is /root/.vnc/d060928abff8:1.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd d060928abff8:1 to connect to the VNC server.

[2021-12-22 02:19:42][E][  98][Register]cms client connect failed.
sslservice.sh start ...
197
start CSClient seccess!
227 201
CSClient is running now, kill it.
start svpnservice seccess!
`

**Comment by Hagb** [comment]
见 https://github.com/Hagb/docker-easyconnect/issues/90#issuecomment-999233830
