### ISSUE TITLE
部分情况下版本正确却提示版本过老，需要更新

### ISSUE THREAD

**Issue by sasaju** [Hagb/docker-easyconnect#95]
我在服务器端使用过很久一段时间的vnc版本（EasyConnect：7.6.3），但是最近一次却突然提示版本过老。
![image](https://user-images.githubusercontent.com/21136684/148006259-ce865535-09e5-4c93-beae-af9d5226cd0c.png)
我在本地跑起的docker，同样的版本，却可以正常进入
![image](https://user-images.githubusercontent.com/21136684/148006346-1f633a03-1c95-48b8-8989-584aabbb6f1d.png)

服务器系统版本：Debian9 64位
本地系统版本：Manjaro GNOME 41.2 64位

我在服务器上已经尝试重装docker、重新拉取镜像，但是依然无效
使用7.6.7版本的vnc版，提示版本不匹配

**Comment by sasaju** [comment]
cli版本在服务器端可以正常登录

**Comment by sasaju** [comment]
![image](https://user-images.githubusercontent.com/21136684/148007538-88a99ff4-d5f7-4e72-907f-bc56b4f1eb12.png)
在提示版本过老时时，后台输出也没什么变化

**Comment by Hagb** [comment]
这应该是 EasyConnect 前阵子的一个小版本更新所致，使用最新容器或者重新构建（不使用缓存）应该可以解决
https://github.com/Hagb/docker-easyconnect/issues/90#issuecomment-998162839

**Comment by Hagb** [comment]
> 我在服务器上已经尝试重装docker、重新拉取镜像，但是依然无效
> 使用7.6.7版本的vnc版，提示版本不匹配

哦不好意思，这句话我给看漏了。有没有做进行持久化（挂载 `/root`）？如果有的话看看尝试清空持久化目录后启动容器并登录。

**Comment by sasaju** [comment]
> 

感谢，清除~/.ecdata目录后就好了
