### ISSUE TITLE
万人血书增加对7.6.8的GUI支持

### ISSUE THREAD

**Issue by lithromantic** [Hagb/docker-easyconnect#96]
RT，能否支持以下7.6.8的GUI，公司强制最新版本且需要验证验证码登录

**Comment by Hagb** [comment]
emmm… 这个东西其实不取决于我加不加，关键现在没拿到 7.6.8 的 GUI 客户端。
公司的 VPN 服务器有没有提供 7.6.8 的客户端下载？如果有的话希望能提供一下（最好是下载地址，如果方便的话）

**Comment by Hagb** [comment]
与 #46 重复
