### ISSUE TITLE
mac m1 是否支持了呢？

### ISSUE THREAD

**Issue by liuzza** [Hagb/docker-easyconnect#99]
由于公司链接easyconnect 会断外网，之前测试过这个镜像，但是显示登录成功，然后就失败了 一直循环

**Comment by liuzza** [comment]
请问一下现在支持了吗？

**Comment by Hagb** [comment]
请问是和 #113 同一问题吗？

**Comment by ErickWei** [comment]
> 请问一下现在支持了吗？

我使用了VNC版本的，可以正常部署和使用，浏览器可以正常配置socks使用，但是有些软件的socks是不管用的，不知道为什么。最后使用了proxifier这个软件做代理。

但是会感觉有点点不稳定，偶尔会断连。

**Comment by liuzza** [comment]
@ErickWei  非常感谢， 我已经明白了

**Comment by Hagb** [comment]
现在有 arm64 原生版本，可以试一试：https://github.com/Hagb/docker-easyconnect/issues/25#issuecomment-1256860002

**Comment by Hagb** [comment]
可以试一下使用 `hagb/docker-easyconnect:dev-7.6.7` 这个镜像（应该要加 `-e DISABLE_PKG_VERSION_XML=1` 参数）
